### ISSUE TITLE
Getting ERROR: Exception raised at randomly with v7.17.4

### ISSUE THREAD

**Issue by Surb109** [springfall2008/batpred#1022]
**Describe the bug**
Using predbat v7.17.4 will randomly will get ERROR: Exception raised, at which point the Predbat HTML plan schedule will not display. Randomly after some time, the error will clear and the html plan will show again

**Expected behavior**

**Predbat version**
7.17.4

**Environment details**

- Inverter - Growatt Min8000tl-x
- Givenergy All-In-One

**Screenshots**
![image](https://github.com/springfall2008/batpred/assets/65631626/590ad6b1-e817-4a65-b428-78d897b26b1a)

**Log file**
[appdaemon copy.log](https://github.com/springfall2008/batpred/files/15141820/appdaemon.copy.log)

**Comment by springfall2008** [comment]
Your issue here is Home Assistant disconnecting from AppDaemon, leading to fetching bad data.

However I should probably try to catch some of those errors.

**Comment by Surb109** [comment]
Appreciate the the update. As long as this isn't going an issue, happy to wait for this to be addressed in a future update
