### ISSUE TITLE
Octopus Intelligent - Unusual plan created when car charging

### ISSUE THREAD

**Issue by nickgee31** [springfall2008/batpred#1027]
**Describe the bug**
Last night I plugged my car in which is on Octopus Intelligent Go. Predbat recognised the car charging slots however it didn't charge my FoxESS battery during those times. At times it states the battery is idle and it will somehow hold the SOC however this didn't happen and the battery ended up discharging to the car at times. It is entirely possible that I am just missing a setting here but thought I'd post in here in case. I. had also tried downgrading to V7.17.0 to see if that helped but a similar plan was created.

**Expected behavior**
I would expect that when the car is charging that the battery is also charging. In the screenshot below, I would expect 23:30 to be charging, 00:00 to discharge and then 00:30 to 01:30 to be charging again, and so on.

**Predbat version**

V7.17.6

**Environment details**

- Inverter and battery setup - FoxESS - 
[apps.yaml.log](https://github.com/springfall2008/batpred/files/15146291/apps.yaml.log)
- Standard HAOS installer or Docker - Standard HAOS install
- Anything else?

**Screenshots**
![IMG_0507 (1)](https://github.com/springfall2008/batpred/assets/110033252/3d951eeb-a8e0-4931-8357-9767f994296c)

**Log file**
[predbat.log](https://github.com/springfall2008/batpred/files/15146262/predbat.log)

**Comment by nickgee31** [comment]
Just another example of a similar thing from last night in case it helps: 
[predbat.log](https://github.com/springfall2008/batpred/files/15160089/predbat.log)

![IMG_0509](https://github.com/springfall2008/batpred/assets/110033252/65682cb0-aecc-4330-963e-c25cf6b7a8a1)

**Comment by nickgee31** [comment]
Out of interest I went back to an even earlier version (V7.16.17) as it mentioned about car planning changes. Things seem a lot better on V7.16.17:
<img width="541" alt="Screenshot 2024-04-30 at 20 23 48" src="https://github.com/springfall2008/batpred/assets/110033252/b93028f0-4d28-4c3f-b120-d0dde0a774c6">

Compared to the latest version, V7.17.6: 

<img width="470" alt="Screenshot 2024-04-30 at 20 25 52" src="https://github.com/springfall2008/batpred/assets/110033252/7aa42a67-fb7a-464e-847c-8b79d6d75699">

So it does seem like something changed in an update to make the plan worse. I'll stay on the older version for now but happy to test any improvements.

**Comment by nickgee31** [comment]
For what it's worth I've been through all the versions and the version I can get the 'normal' plan on is way back on V7.16.16 
<img width="541" alt="Screenshot 2024-04-30 at 20 23 48" src="https://github.com/springfall2008/batpred/assets/110033252/85e220ae-0535-4608-8e5c-e20d8bf4faff">

I've been able to replicate this odd behaviour on two different Predbat set ups, with both a GE and a FoxESS inverter so don't think it's limited to the inverter type. I'll stick on this version and happy to test any changes if it's able to be spotted what changed.

**Comment by phiebs** [comment]
What's you're Metric Battery Cycle Cost set to? I've had this before and it was set a bit too low (1p/kWh) and I had to tweak this up to 2.4p/kWh to get it to stop trying to discharge to the grid/car. YMMV!

**Comment by tractor137** [comment]
I've been having the same issue and have just downgraded from 7.17.10 to 7.16.16 which seems to have solved the problem for now

**Comment by springfall2008** [comment]
I think the issue here is that your inverter isn't supporting the mode where discharge is disabled while the car charges and hence the plan is sensible (holding the battery during car charging) but it doesn't happen.

As you have Fox I think we should look at how its configured, and then add it to the documentation once correct. Can you share how you set it up?

**Comment by springfall2008** [comment]
I've just made a fix on main which I will release soon which will prevent any type of forced discharge during a car charging slot if 'allow car charging from battery' is off.

**Comment by nickgee31** [comment]
Hi @springfall2008,

Just tested this on my GivEnergy AC3 inverter.

On version V7.16.16 this is the plan: 
<img width="538" alt="Screenshot 2024-05-06 at 19 31 14" src="https://github.com/springfall2008/batpred/assets/110033252/4e84cad1-a453-42b6-a321-5bfd6414be15">


And on V7.18.0 this is the plan: 
<img width="468" alt="Screenshot 2024-05-06 at 19 32 28" src="https://github.com/springfall2008/batpred/assets/110033252/4e40bf0d-b82a-4414-904f-385415f4ed1f">


I can confirm that I have 'allow car charging from battery' to off. Here is the predbat.log if it is any help: 
[predbat.log](https://github.com/springfall2008/batpred/files/15225019/predbat.log)

**Comment by tractor137** [comment]
I'm still experiencing the same problem - I've been trying each of the new releases but having to keep reverting to 7.16.16. The plan it creates in new versions is fine until I plug the car in, then It recalculates and throws in either unused charge slots or freeze charges.

**Comment by pacemaker82** [comment]
+1 here for me too, seeing odd behaviour where the plan intends to keep the charge of the battery during car charge, but then decides to change that plan when the slot opens, setting it to Idle, then discharging the battery to the car. (GivEnergy AC 3 w/ 9.5 kWh battery)

**Comment by nickgee31** [comment]
Hopefully this is helpful @springfall2008.

I've been through all the versions and the tipping point is V7.16.4 and it looks like the only change is https://github.com/springfall2008/batpred/pull/1013. Going back to V7.16.3 results in a normal plan.

**Comment by springfall2008** [comment]
Interesting, it maybe there is a mistake in this change around the freeze, let me remove that bit...

**Comment by springfall2008** [comment]
There's a potential fix on 'main' for testing

**Comment by nickgee31** [comment]
Just tested main and all looks good now! 

<img width="476" alt="Screenshot 2024-05-14 at 09 24 42" src="https://github.com/springfall2008/batpred/assets/110033252/6721f5ca-4668-43e6-a4b3-95657f78e89b">

Thank you for your help @springfall2008
