### ISSUE TITLE
Car charging does not use the new pause method implement in #360 when holding battery

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#1029]
**Describe the bug**
As discussed, it appears that car charging has not implemented the new pause methodology introduced in #360 .

This means there is a higher lever of battery leakage during car charging if the battery is not charging.

**Expected behavior**
Set the slot to freeze charge if the car is charging and option to charge from battery is false

**Predbat version**
V7.17.6

- Standard HAOS installer or Docker

**Screenshots**
![Screenshot_2024-04-29-12-40-38-991_io homeassistant companion android~2](https://github.com/springfall2008/batpred/assets/106986397/38e80936-2f35-43ca-ae7e-69ba71159255)
![Screenshot_2024-04-29-12-40-56-974_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/882a144c-a9b0-4838-8015-a328480c78bd)
![Screenshot_2024-04-29-12-40-50-236_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/792044f1-9ae5-48ec-96e3-6e26b1077761)

**Log file**
Not required, cause is known

**Comment by mpartington** [comment]
Another bug spotted yesterday, that may also be car charging related, but perhaps a more general error.

Both the car and battery have been charging, but as the battery hits 100%, Predbat switches enable charge off and discharge freeze on. This allows the battery to supply the car (and house) despite being in a car charging slot and the rates being low.

It does this a few times
[appdaemon.log](https://github.com/springfall2008/batpred/files/15184331/appdaemon.log)

![Screenshot_2024-05-02-06-39-53-650_com android chrome](https://github.com/springfall2008/batpred/assets/106986397/abe0be52-9904-480c-b3d4-15d27013fe69)

I assume it's Predbat making the change, I can't find any automation triggering at those times
![Screenshot_2024-05-02-07-15-23-118_com android chrome](https://github.com/springfall2008/batpred/assets/106986397/391c2b36-58dc-44b4-b32d-3314a030efb8)

**Comment by mpartington** [comment]
Edit.. It is Predbat driving this behaviour. I have no automations that change the battery discharge rates

![Screenshot_2024-05-02-07-32-51-727_com android chrome](https://github.com/springfall2008/batpred/assets/106986397/1ec0f768-3bf1-4077-a4ed-bb553c87b49e)

**Comment by mpartington** [comment]
So looking at the logs, is there a timing (and possible logic) issue - does Predbat know the car is charging at the start of the run?

The issue seems to be the order in which Predbat does stuff, and probably the speed my RPI4 processes commands.  

When SoC reaches 100% Predbat selects PauseDischarge (04:27:41), which allows the battery to discharge.  It then realises the car is charging and it needs to hold the battery.  So it subsequently adjusts (04:28:06) the battery reserve level to 100% (which is absolutely fine on my inverter)

This means there is a 30 second burst of discharge from the battery. 

Next run, Predbat realises the SoC is not at 100%, so Disables pause and lets the battery charge back up. Rinse and repeat....

What is maybe not clear is why this behaviour stops after 4.30, but I suspected this might be due to the change in rates at that point, but appears not - 4 til am 5 is 10.1p


2024-05-02 04:27:31.569481 INFO pred_bat: Inverter 0 Turning off scheduled charge
2024-05-02 04:27:41.635158 INFO pred_bat: Inverter 0 Wrote inverter_mode to PauseDischarge successfully
2024-05-02 04:27:41.641274 INFO pred_bat: **Inverter 0 set pause mode to PauseDischarge**
2024-05-02 04:36:08.301358 INFO pred_bat: Disabling battery discharge while the car 0 is charging


2024-05-02 04:27:51.690505 INFO pred_bat: Car charging from battery is off, next slot for car 0 is 05-02 04:25:00 - 05-02 05:00:00

2024-05-02 04:28:06.465867 INFO pred_bat: Disabling battery discharge while the car 0 is charging
2024-05-02 04:28:06.528985 INFO pred_bat: Resetting charging SOC as we are not within the window or charge is disabled and inverter_soc_reset is enabled (now 05-02 04:25:00 target set_soc_minutes 30 charge start time 05-02 04:00:00)
2024-05-02 04:28:06.552062 INFO pred_bat: Inverter 0 Current Target SOC is 100 already at target
2024-05-02 04:28:06.575660 INFO pred_bat: Adjust reserve to target charge 100 % (set_reserve_enable is true)
2024-05-02 04:28:06.584686 INFO pred_bat: Inverter 0 Current Reserve is 4.0 % and new target is 100 %
2024-05-02 04:28:17.754618 INFO pred_bat: Set inverter 0 reserve 100 via REST successful on retry 0
2024-05-02 04:28:17.864858 INFO pred_bat: Completed run status Hold charging, Hold for car

**Comment by springfall2008** [comment]
I've released a fix

**Comment by mpartington** [comment]
possible issue, did not hold, but turned on home battery charging despite home battery at 100%. Had same effect though, and battery did not discharge to car

charge started 15:48 - 16:00 

[appdaemon.log](https://github.com/springfall2008/batpred/files/15210160/appdaemon.log)

<img width="329" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/e76188a0-1614-4c03-a505-cc8dfbeaada1">

**Comment by springfall2008** [comment]
For reference, the battery was charging it started at 97% so I think it worked correctly:

>Charge window will be: 2024-05-04 15:30:00+01:00 - 2024-05-04 16:00:00+01:00 - current soc 97 target 100

**Comment by mpartington** [comment]
Agree, user error! I forgot I bumped the charge soon as I plugged in, so
the battery drained a few %

**Comment by springfall2008** [comment]
Hopefully fixed, please re-open if not
