### ISSUE TITLE
Predbat charging at expensive rate

### ISSUE THREAD

**Issue by jacekowski** [springfall2008/batpred#1040]
**Describe the bug**
For some reason, predbat decided to charge today at relatively expensive rate (20p, well above export rate) on a day with 50kWh solar forecast.

**Expected behavior**

Do nothing.

**Predbat version**

latest 7.17.7

**Screenshots**
![image](https://github.com/springfall2008/batpred/assets/9898247/f994f57e-c5b5-41da-aaca-c66670fca49e)

**Comment by RobinCu** [comment]
Can you check if there was any significant draw from the grid?  The limit was set to 48%, SOC already at 47%, PV was forecast to exceed load and the cost for the 30-minute period decreased slightly.  It might have just been a blip in the calculation run.

**Comment by jacekowski** [comment]
It has charged from the grid (not much, but it did)

**Comment by jacekowski** [comment]
I've got it doing another stupid thing, it's preventing battery from discharging now. 
![image](https://github.com/springfall2008/batpred/assets/9898247/27053a1c-7a8e-488c-aa8c-0e65b0cbb6e9)

**Comment by mpartington** [comment]
What are your values for these:
<img width="278" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/d3838d08-78a1-41be-9dc3-eb05e445c5ca">
<img width="284" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/8c1654a2-da57-45e4-9dc3-7d233c3b21bd">
<img width="285" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/23047aa8-48ab-4536-9d9f-66f5d49fa0e6">

I tried to explain why holding charge is sensible in issue #1035, however it may be your inputs above are a little high and are forcing this at higher rates than you would like.

Ultimately if you don't freeze, then you will recharge your battery on lost solar, which is valued at 15p/kwh. You will also have round trip losses if you discharge the battery + whatever value you've used in the battery metric.

**Comment by jacekowski** [comment]
0.04 for all loss values and i don't have battery cycle cost entity.

Accounting for losses, it should use battery for anything above 17p, but it is doing freeze charge even at 19p+ rates.

**Comment by mpartington** [comment]
Strange, it was doing this for me at the very high 25p+ peak rates, but Trefor put a fix in that seems to have worked. Might be worth uploading a log filewith a few cycles in debug mode next time you catch it

**Comment by mpartington** [comment]
Looks like.mine.has also decided to do similar..Doesn't make sense, as can top up on solar for less cost. Slot force to Idle as was actually charging
![Screenshot_2024-05-05-15-48-11-029_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/a0fce6ed-3e63-411c-bad7-91ec09eece7f)

**Comment by mpartington** [comment]
logs.. 

[appdaemon.log](https://github.com/springfall2008/batpred/files/15214283/appdaemon.log)
[appdaemon1.log](https://github.com/springfall2008/batpred/files/15214286/appdaemon1.log)


At 19:35 , the plan goes nuts and starts to use grid at high rates and also plan on charging at high rates.  moving back a few versions, then reinstalling v7.7.12 restored the plan to something sensible
![download](https://github.com/springfall2008/batpred/assets/106986397/579d2f40-c636-4e5c-9caf-8de54673a85b)


and back to normal

<img width="312" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/360bb93e-1cdc-4a60-8fa7-a85e7012ce9f">

**Comment by mpartington** [comment]
With debug for the latest change 21:25 is the relevant run

[appdaemon.log](https://github.com/springfall2008/batpred/files/15214493/appdaemon.log)

**Comment by springfall2008** [comment]
The issue seems to relate to the use of metric battery cycle when its non-zero, testing a fix now

**Comment by springfall2008** [comment]
Fix on main for testing

**Comment by mpartington** [comment]
@springfall2008  Logs for the 0.5p and 2p battery metric.  
The 2p seems to be planning to hold at very high rates around19:00 (>21p)
[appdaemon1.log](https://github.com/springfall2008/batpred/files/15219277/appdaemon1.log)

Plans run around 10:30, so across 2 log files unfortunately

**Comment by jacekowski** [comment]
I've changed my settings slightly to limit battery charge rate (to start exporting early and not waste any solar), by making battery_rate_max an entity and using node-red to adjust it. Now that i have it set to 2000, predbat comes up with plan to force charge.

![image](https://github.com/springfall2008/batpred/assets/9898247/c611b2d3-68a7-45b6-b0e6-77827ba22f4a)
