### ISSUE TITLE
REOPENED: Rounding issue preventing Predbat switching off car charging slot at correct time in Manual SoC mode

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#1048]
**Describe the bug**
Predbat scheduled 3 slots last night 05:00 to 05:30 , 06:00 to 06:30 and 08:00 to 08:30.  However the second slot incorrectly continued until 07:00.

A bit of background to the set up... I use Car Manual SoC as sometimes the car api stops reporting the SoC, so find this a safer approach. As you know Trefor, in this mode it will assume the amount of kWh delivered based on the charge rate.

You can see at 05:30, Predbat stops accumulating the kWh, and the logs confirm it is at target.    However the charge slot was not switched off and the plan also did not show an active slot planned.  It seems like parts of Predbat realised it should not be charging, but the state of 'binary_sensor.predbat_car_charging_slot' was not changed to off as expected

As the difference in cost for this unplanned slot was negligible to the one that was planned later, I let it continue. At 06:00, Predbat finally switched off  

**Expected behavior**
binary_sensor.predbat_car_charging_slot to turn off at the end of a planned slot

I think it may be due to this rounding:
2024-05-05 06:31:09.184482 INFO pred_bat: Car charging Manual SOC current is 32.26 next is 32.260999999999996

It will never meet the target (as it stops accumulating soc_kwh), so keeps adding another 5 min slot

at 7am, these values somehow align, the binary sensor is switched off and my charge stops
2024-05-05 07:00:24.039204 INFO pred_bat: Car charging Manual SOC current is 32.26 next is 32.26

**Predbat version**

v7.17.10

**Environment details**

- Standard HAOS 

**Screenshots**
.
<img width="189" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/749d3474-c743-47c8-ae50-f01ae1fa86ae">

<img width="722" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/2f510d8d-b7b8-4e40-989f-269fd15aea20">

![image](https://github.com/springfall2008/batpred/assets/106986397/2afeb619-7b71-4842-bfc5-44f5cfe85e15)

**Log file**
[appdaemon.log](https://github.com/springfall2008/batpred/files/15211971/appdaemon.log)

**Comment by springfall2008** [comment]
Potential fix on main

**Comment by springfall2008** [comment]
Now released

**Comment by mpartington** [comment]
Still an issue with rounding.  Car should have switched off at 03:00, but slot remained active.  I looked in Predbat log and same issue :

2024-05-14 03:02:54.984694 INFO pred_bat: Car charging Manual SOC current is 48.48 next is **48.485**
[appdaemon1.log](https://github.com/springfall2008/batpred/files/15302661/appdaemon1.log)

Running the beta version on main (v7.18.7)

**Comment by springfall2008** [comment]
Further fix on main
