### ISSUE TITLE
Enhance predbat status with time information

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#105]
The predbat status would be more useful if it additionally showed time information in it, eg "Idle, last run at hh:mm" or "Charging, started at hh:mm to xx:yy"
This would give a simple status confirmation that predbat is still running ok and when major activities started
![image](https://github.com/springfall2008/batpred/assets/142018870/868490e8-3384-462b-8038-dbc4cd0ff0fc)

**Comment by springfall2008** [comment]
Have you see the display of status inside HA as it gives all the times and states? In fact I was thinking the 'at xxx' bit shouldn't be there on the messages so the same command shows in the same colour more than once.

For Charging I could add the end time maybe, e.g. Charging until 12:31?

![image](https://github.com/springfall2008/batpred/assets/48591903/81f41b63-ec7d-4310-b4ef-bcb61606c244)

**Comment by gcoan** [comment]
Yes I've seen that, thank you.  

The problem is that in the example above, Idle was set 4 hours ago and of course predbat has been running ever since, its just the status hasn't changed.

It was where I was fiddling with the settings/apps.yaml and waiting for predbat to run, and found there wasn't an easy way of seeing when it last ran without opening the file editor, logfile, scrolling to the end.  Then repeating when it hadnt yet run.

Trade-off of putting too much information in the status that the simple history line will get very cluttered as time based things change.  Even with 'charging to' I've noticed that it charges to a level, stops charging then 5 minutes later charges a bit more so its going to get very cluttered 
![image](https://github.com/springfall2008/batpred/assets/142018870/d21c7af4-ed07-4eb6-9280-c59b905a827e)

**Comment by springfall2008** [comment]
How about I add the last updated time to attributes of status e.g:

![image](https://github.com/springfall2008/batpred/assets/48591903/0360a3e2-2af7-40c7-9473-b356b725e5f8)

**Comment by gcoan** [comment]
Yes that would be useful and would mean the history bar graph remained clear of clutter

**Comment by springfall2008** [comment]
Now added
