### ISSUE TITLE
Hass.get history issue with latest update

### ISSUE THREAD

**Issue by stefanwest1** [springfall2008/batpred#1084]
**Describe the bug**
Since the latest update, I’m getting the following error.
ERROR: Exception raised Hass.get_history() takes 1 positional argument but 2 were given

**Expected behavior**

**Predbat version**

7.18.6

**Environment details**

- Appdaemon Docker

**Screenshots**

I can’t copy the log file right now as I’m on my phone so the best I can do is upload a screenshot

![IMG_0467](https://github.com/springfall2008/batpred/assets/42491252/7719b9d9-1962-40bb-8fcc-91b069ed9e97)

**Comment by stefanwest1** [comment]
Dropping back to 7.18.2 fixes the issue

**Comment by PianSom** [comment]
I had the same issue (using Appdeamon Docker) and the same solution

**Comment by sammort** [comment]
Just wanted to +1 this issue for me, also running AppDaemon as a Docker container

**Comment by springfall2008** [comment]
Now fixed on main for testing https://github.com/springfall2008/batpred/pull/1093
