### ISSUE TITLE
PauseCharge was not switched off when a charge window was planned/enabled, so battery would not charge

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#1085]
**Describe the bug**
Spotted that my battery was not charging, despite Predbat planning to do so.  Looking at the logs I can see Predbat switches :
2024-05-12 13:01:36.183835 INFO pred_bat: Inverter 0 Wrote inverter_mode to PauseCharge successfully

In later runs, it changes the status to 'charging', however does not switch charge pause off, so the battery remains in limbo until I manually unpause it

**Expected behavior**
Set the pause feature to disabled and allow battery to charge

**Predbat version**

v7.18.6

**Environment details**

- Standard HAOS installer 

**Screenshots**
<img width="856" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/e8e84dec-c905-4a49-b44d-800df20f0cbb">

**Log file**
[appdaemon.log](https://github.com/springfall2008/batpred/files/15286436/appdaemon.log)

**Comment by gcoan** [comment]
I had exactly the same at 11am this morning 

The battery was paused charging at 8:07, ignoring the accidental change I made then reverted at 9:34, predbat started charging at 11:00 but the pause charge wasn't removed - I manually removed it at 11:03

Predbat 7.18.1

![image](https://github.com/springfall2008/batpred/assets/142018870/33c731b1-f62d-414f-a735-86dd669bcbe4)

![image](https://github.com/springfall2008/batpred/assets/142018870/c8e92e4e-a4fa-419d-9618-43e0610b14ef)

Givtcp logs showing no attempt to change the pause 
![image](https://github.com/springfall2008/batpred/assets/142018870/c822bbc3-6ace-4cb2-a652-1fb142bc28cb)
![image](https://github.com/springfall2008/batpred/assets/142018870/d0ca0a61-fe70-405d-81b7-5263353dcd52)
![image](https://github.com/springfall2008/batpred/assets/142018870/1f3b8359-1b69-4bf1-949a-9c0602eaad95)

**Comment by gcoan** [comment]
@springfall2008 I see you are working on a fix for this.  Do you need my logfile from the above?

**Comment by springfall2008** [comment]
The fix is already on main

**Comment by mpartington** [comment]
Will reopen if not fixed
