### ISSUE TITLE
Query about the accuracy of suggested charge and discharge rate from the 'auto generate charge curve' routines

### ISSUE THREAD

**Issue by PianSom** [springfall2008/batpred#1104]
I have an AIO, and GivTCP returns `number.givtcp_SERIALNO_battery_charge_rate` and `...discharge_rate` as both being 6kW. Looking at actual experience reported by GivTCP my battery is actually discharging at around 6.27kW and is charging at around 5.8kW

However the `input_number.predbat_battery_rate_max_scaling_discharge` and charge settings suggested by Predbat seem to bear little resemblance to these values. I am using the Predbat suggested values, but Geoffrey thought it may be worth checking that the Predbat suggestions are correct?

![Screenshot 2024-05-16 at 13 14 54](https://github.com/springfall2008/batpred/assets/25636191/bc0128d1-2d7f-4a45-bade-dfe68a9665fa)

**Comment by PianSom** [comment]
Not least because the actual discharge rate reported is 5% MORE than the rated value! Hence the question.

(Wasn't really querying the curves.)

**Comment by springfall2008** [comment]
Probably down to losses, maybe you set them too high?
