### ISSUE TITLE
Predbat Savings sensors innaccurate

### ISSUE THREAD

**Issue by Mikebert4** [springfall2008/batpred#1106]
We're moving to Octopus Agile soon, and so I've installed PredBat to help manage our Solar/Battery system - because it's absolutely awesome. 

Install is a GivEnergy Gen1 Hybrid, communicating through GivTCP.

Our current Electricity rates are flat - same value 24h a day. It's pretty clear that there's not a lot for PredBat to be doing - the PV system gathers what energy it can, when the battery is full it exports, when the house load exceeds the PV generation, the battery kicks in until it's empty. Rinse and repeat. Predbat has thus been "idle" for pretty much the entire time - there's no cost benefit to holding charge, or charging the battery from the grid. All is as it should be.

However, over the last couple of days, with the creation of the savings sensors, I've noticed that these sensors are reporting savings from predbat (when in fact there's no optimisation to be done).

Predbat Plan
![image](https://github.com/springfall2008/batpred/assets/344660/b5d4e620-6044-48a6-9de6-fdb39339c377)

Predbat cost predictions showing no change between base and optimised:
![image](https://github.com/springfall2008/batpred/assets/344660/533ff9fd-a6dc-478c-8769-c0f2fb3ce360)

Predbat Savings numbers (I've stacked the bar graphs - so there's a little more going on here, but the values are still the raw ones)
![image](https://github.com/springfall2008/batpred/assets/344660/a300105c-8464-4173-9cff-0366bb31a5f6)

**Comment by springfall2008** [comment]
I've not tried a single fixed rate, maybe its trying to compare it against 24/7 charging I'll look

**Comment by springfall2008** [comment]
Closing this old issue, feel free to open a new one if still an issue
