### ISSUE TITLE
Multi-threading for Region Optimisation 

### ISSUE THREAD

**Issue by dochtie** [springfall2008/batpred#1118]
**Is your feature request related to a problem? Please describe.**
I noticed my predbat runs were taking 2-3 times longer and it seems the region optimisation phase is taking much longer than normal.

**Describe the solution you'd like**
Could the CPU pool be used to speed this up?

**Describe alternatives you've considered**
Fast plan is now removed as an option. Second pass disabled.

**Additional context**
A pi home asssitant green will take greater than 5 mins for a single pass whereas before including a second pass it was 2-2.5 mins.

**Comment by springfall2008** [comment]
Fixed in v7.19.6
