### ISSUE TITLE
Afternoon discharge on IOG

### ISSUE THREAD

**Issue by nickgee31** [springfall2008/batpred#1178]
**Describe the bug**
Quite often there is a short discharge in the afternoon when on the IOG tariff. Solar will then charge the battery back up to 100%. There doesn't seem to be any change in behaviour with having the 'Inverter Hybrid' option toggled either off or on.

**Expected behavior**
That the discharge is left until very late in the day in case it is required. Also is inefficient to force discharge and then charge battery back up with solar.

**Predbat version**

V7.22.2

**Environment details**

- GivEnergy Gen2 5.0kW + 9.5kW battery
- Predbat Addon

**Screenshots**

<img width="490" alt="Screenshot 2024-06-04 at 11 59 56" src="https://github.com/springfall2008/batpred/assets/110033252/902748eb-0da7-4135-935d-bddfb8be8d2b">
<img width="479" alt="Screenshot 2024-06-04 at 12 00 10" src="https://github.com/springfall2008/batpred/assets/110033252/cf83901a-11dd-49ca-822a-fe3f50fcbbe3">

**Log file**
[predbat.log](https://github.com/user-attachments/files/15550392/predbat.log)

**Comment by springfall2008** [comment]
Can run you with debug enabled and provide that logfile please?

**Comment by nickgee31** [comment]
No problem, just run that for you. There's a force discharge scheduled for tomorrow at 15:30 too. Let me know if you need anything else

<img width="495" alt="Screenshot 2024-06-04 at 20 17 33" src="https://github.com/springfall2008/batpred/assets/110033252/9a23268e-7244-426d-b711-c06d49f362b9">

[predbat-2.log](https://github.com/user-attachments/files/15569382/predbat-2.log)

**Comment by springfall2008** [comment]
Not sure I get it, the calculation claims the export at 15:30 improves the cost slightly but it really can't do.

Do you have the power chart, can you show it for that period too please?

**Comment by springfall2008** [comment]
Okay I think I sort of understand the logic now, you could discharge more than the planned nightly discharge, but in the 10% scenario doing so would run out of battery.

However some extra discharge earlier in the case where the battery won't get back to 100% again will have the same sort of impact on the normal scenario but less so on the 10% case as the load will be higher and that comes off the same export amount.

I'm thinking that ignoring metric keep in the 10% scenario maybe a good idea, will have a tinker when I get time

**Comment by springfall2008** [comment]
Actually metric keep is already ignored in the 10% case...

Can you try something and adjust 'metric_battery_value_scaling' down to say 0.8 and see what plan you get?

**Comment by nickgee31** [comment]
Sorry just got round to trying it, slot had moved to 16:00.

Before: 
<img width="486" alt="Screenshot 2024-06-05 at 13 19 02" src="https://github.com/springfall2008/batpred/assets/110033252/665ce0f8-9750-4133-9664-15a877ab6698">

After: 
<img width="486" alt="Screenshot 2024-06-05 at 13 19 55" src="https://github.com/springfall2008/batpred/assets/110033252/50921d96-8e11-4bcc-9222-eb1baee4ccb8">

**Comment by nickgee31** [comment]
Think I spoke too soon, it came back

<img width="483" alt="Screenshot 2024-06-05 at 13 36 19" src="https://github.com/springfall2008/batpred/assets/110033252/13db62eb-48a7-471c-a10d-685d9a068804">

**Comment by springfall2008** [comment]
Interesting, I have some ideas on how to fix it, but its not a bug as such it relates to how the 10% scenario works (I think).

**Comment by nickgee31** [comment]
No worries, it doesn't cause too much of a problem really but just thought it was worth mentioning. Let me know if I can be of any help at all

**Comment by springfall2008** [comment]
Would you mind testing the version on 'main' (just select main from the update drop down menu) and see if it changes at all?

**Comment by nickgee31** [comment]
Apologies only got round to testing this today, unfortunately still an afternoon discharge today

**Comment by springfall2008** [comment]
There is a new release that's worth trying
