### ISSUE TITLE
set_reserve_hold missing from example_dashboard

### ISSUE THREAD

**Issue by iainfogg** [springfall2008/batpred#118]
Hi @springfall2008 - not sure if it's intentional, but `set_reserve_hold` is missing from the example_dashboard, yet it appears in the instructions for configuring for various tariffs. Happy to add it back in if you like, just wanted to check first in case it was removed for a reason (in which case it probably needs to come out of the tariff instructions).

**Comment by springfall2008** [comment]
I probably just forgot it, feel free :)
