### ISSUE TITLE
Agile import w/loss calculation incorrect with plung pricing

### ISSUE THREAD

**Issue by Surb109** [springfall2008/batpred#1190]
**Describe the bug**
With Octopuse during price plunging the Import rate with loss caluclulation seem to be incorrect.

e.g. when Import rate is -2.03 with a 5% battery loss charge, the value is showing as -2.14

**Expected behavior**
With Import rate -2.03 with a 5% loss expect Import rate to be -1.93.
The import rate after losses should be higher not lower.

When Import rates are negative need to subtract the 5% loss instead of adding the 5% loss when prices are positive.

**Predbat version**

v7.22.3

**Environment details**

- Growatt Inverter and Givenergy All-in-one
- Home Assistant Container (Docker)

**Screenshots**
![2024-06-07_18-25-17](https://github.com/springfall2008/batpred/assets/65631626/2da53902-5023-4ee3-9752-ddcbb10a9863)

**Log file**

**Comment by gcoan** [comment]
I raised the same problem a couple of months ago, see https://github.com/springfall2008/batpred/issues/881

In short, the calculation is correct

**Comment by Surb109** [comment]
Thanks for the pointer, I did try and search for similar issues before posting, but didn't find anything.

I've taken alook at #881 and I'm still trying to understand the logic. 
If the maths has been proven to be correct, I'll leave it at that.
