### ISSUE TITLE
'load actual' in predbat is much higher than the GivTCP sensor value.

### ISSUE THREAD

**Issue by philkendall** [springfall2008/batpred#1204]
**Describe the bug**
'load actual' in predbat is much higher than the GivTCP sensor value.
History of predbat.load_energy_h0
![image](https://github.com/springfall2008/batpred/assets/58569471/0464353d-1e36-42e2-a5dd-37d4eb4066ef)
(Ignore the little spike at 20:17; this was caused by me trying to debug and changing a value incorrectly)

History of GivTCP Load Energy Today KwH
![image](https://github.com/springfall2008/batpred/assets/58569471/5e2a68f1-afae-496c-b317-327a90317b4c)

Load scaling is set to 1.0
![image](https://github.com/springfall2008/batpred/assets/58569471/ed0e01d8-006f-4566-8d80-0e40ceb7ca77)

This is causing the in-day adjustment graph to show a massive increase in load, which is not reflecting reality.
![image](https://github.com/springfall2008/batpred/assets/58569471/a01e18ea-fdc1-489b-9e4c-55f258ed1fca)

**Expected behavior**
With the load scaling at 1.0, I expected the 'load actual' to match that current value provided by GivTCP.

**Predbat version**

7.22.4

**Environment details**

- GIV-AC3.0 and GivEnergy 9.5kWh battery
- Standard HAOS installer
- Anything else?

**Screenshots**
Settings:
![image](https://github.com/springfall2008/batpred/assets/58569471/483228d9-c787-46f9-a3b3-f1095e7816c7)
![image](https://github.com/springfall2008/batpred/assets/58569471/d4dc8cfd-029f-456d-9062-b85f1827d256)
![image](https://github.com/springfall2008/batpred/assets/58569471/9b6d9b2c-590d-4819-80a7-9271c0411062)
![image](https://github.com/springfall2008/batpred/assets/58569471/e3b30517-e1ab-406e-a5af-e3b6ecf257a9)

**Log file**
[predbat.log](https://github.com/user-attachments/files/15778263/predbat.log)

**Comment by springfall2008** [comment]
Did you get the edit at all as I don't recognise this string?

2024-06-10 20:19:45.574344 INFO pred_bat: Mins Now: 1215 Latest Entry: 81.4431 Current Entry: 72.5141

**Comment by springfall2008** [comment]
This is odd as mine seem identical.

What does apps.yaml set your load_today to?

![image](https://github.com/springfall2008/batpred/assets/48591903/7b710135-8e4c-4307-8e04-84352e72f0b5)

**Comment by springfall2008** [comment]
Actually I take that back, actually mine are higher its just not as much as yours.

I think I know why, as the GivTCP entities sometimes go down which Predbat doesn't allow...

**Comment by springfall2008** [comment]
I'll have a go at fixing this soon, still think its working around a bug in GE kit..

**Comment by springfall2008** [comment]
Fix on 'main' for testing

**Comment by philkendall** [comment]
Thanks for looking into it so quickly.

Yes, that extra log line was added by me; I was interested in the data that went into the calculation.

I'm not at my PC right now, so I'll give the fix a test tomorrow and report back

**Comment by philkendallsimba** [comment]
I've put the fix in, and so far so good. As of 09:45 this morning, the load actual is reading the correct value.

![image](https://github.com/springfall2008/batpred/assets/59607530/53b47055-06b9-4a30-9863-dfae26f8bbe7)

![image](https://github.com/springfall2008/batpred/assets/59607530/484f8018-fc1a-481f-8cbb-c7960c63fd19)

I shall continue to monitor.
Thanks.
