### ISSUE TITLE
Predbat dashboard isn't being written

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#1211]
**Describe the bug**
Originally raised on #1210, it caused me to look at my own /config/predbat_dashboard.yaml

The dashboard isn't being written to despite the logfile saying it is

**Expected behavior**
Dashboard written each predbat run (or even after every restart would be just as good)

**Predbat version**
8.0.0 but has been broken since 7.17.0?

**Environment details**
HAOS 2024.5.5
Gen 1 hybrid, 9.5 battery

**Screenshots**
Logfile says dashboard is being written to:
![image](https://github.com/springfall2008/batpred/assets/142018870/23191257-f061-44d9-a68a-df3e1a91bba9)

However filename clearly hasn't been updated for months:
![image](https://github.com/springfall2008/batpred/assets/142018870/f0171677-5e6a-4cdb-bddc-cf4c1b9a38be)

And the file hasn't been written to for ages:
![image](https://github.com/springfall2008/batpred/assets/142018870/ce50a6a1-3a84-40da-92b2-f2c6292062f7)

[predbat_dashboard.yaml.txt](https://github.com/user-attachments/files/15849137/predbat_dashboard.yaml.txt)

**Comment by springfall2008** [comment]
I think you are looking in the wrong place it was moved to the addons_config area?

**Comment by gcoan** [comment]
Yes thanks, I will delete my defunct one from /config and update the documentation to make it clearer where to find it.  I looked everywhere but there !
