### ISSUE TITLE
Merge notifications from multiple inverter activity together

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#125]
When predbat is managing multiple inverters, each notification is sent separately for each inverter.

If possible can these be combined, e.g. “Inverter 0 and Inverter 1 Target Reserve changed to 46”

It would also cut down on notifications if there was some “buffer window” on the change as to whether a new notification was sent or not.  E.g. notifications are currently set when reserve changed to 44 then 45 then 46

![IMG_4914](https://github.com/springfall2008/batpred/assets/142018870/6983ee21-87f2-4329-b578-19cd31776161)

**Comment by springfall2008** [comment]
Good point, I wonder if it can just say Inverter N as it does the same thing to all of them anyhow

**Comment by gcoan** [comment]
I don't have any particular preference. If the same activity is applied for all inverters then it doesn't make any benefit to notify per inverter

**Comment by gcoan** [comment]
changes to notifications have delivered this
