### ISSUE TITLE
Clarification about switch.predbat_iboost_gas

### ISSUE THREAD

**Issue by mogons57** [springfall2008/batpred#1283]
**Is your feature request related to a problem? Please describe.**
It is not clear in the documentation when switch.predbat_iboost_gas is on what electricity rates are being referred to in 
"When enabled will control the solar diverter to only operate when electric rates are lower than gas rates."

**Describe the solution you'd like**
I'm trying to setup things so that when I have spare solar and my export rate is lower than the gas import rate my iboost (actually an EDDI but essentially the same) is triggered to start diverting power. i.e. divert rather than export if export price lower than gas price. 

**Describe alternatives you've considered**
This does not seem to be working (and I've played with the gas price weighting to try to force this to work) so I'm thinking the price being referred to is the electricity import rate. 

**Additional context**
I can see arguments for using the electricity import rate to trigger iboost doing a "boost" from the grid (as I suspect predbat does now) however if would also be good to be able to use the export rate to trigger iboost "diverting".

Therefore might an extra switch be included to decide which rate the gas is being compared with (the choice of what to do then being configured by the user in an automation). Or is there the possibility of a new option something like "iBoost divert when export lower than gas", with the existing "iBoost when electricity cheaper than gas" being changed to "iBoost when import electricity cheaper than gas" to clarify the difference.

**Comment by springfall2008** [comment]
I've re-worked the iboost now, new version on 'main' for testing which includes export rate filtering and export rate higher than gas option

**Comment by mogons57** [comment]
Just had a look at the new code (and not sure I understand all of it) but If I've not misread things there is only one sensor to use to drive the iboost settings i.e. **binary_sensor.predbat_iboost_active**.  

My current automation to change the control mode of the iboost/eddi [off or divert] is:

alias: Solar Diverter (Eddi)
description: Start/stop solar diverter based on Predbat determined slots
trigger:
  - platform: state
    entity_id:
      - binary_sensor.predbat_iboost_active
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.predbat_iboost_active
            state: "True"
        sequence:
          - service: select.select_option
            metadata: {}
            data:
              option: Normal
            target:
              entity_id: select.myenergi_eddi_#####_operating_mode
      - conditions:
          - condition: state
            entity_id: binary_sensor.predbat_iboost_active
            state: "False"
        sequence:
          - service: select.select_option
            data:
              option: Stopped
            target:
              entity_id: select.myenergi_eddi_#####_operating_mode
mode: single

but is there another sensor I can use to tell me whether I should be setting divert (just use excess solar) or boost (heat at full rate) mode i.e. control to iboost to [off, divert, boost]?

**Comment by springfall2008** [comment]
Good point, I probably should add that.

**Comment by springfall2008** [comment]
Adding on 'main' attributes 'solar' and 'full' to the iboost_active sensor for this purpose
