### ISSUE TITLE
Using predbat with battery only setup?

### ISSUE THREAD

**Issue by pootle** [springfall2008/batpred#130]
I have a battery only setup with heat pump heating, This looks really good, but just wondering if it will cope with a battery only setup.

Could I run without solcast? clearly much of that is irrelevant, but picking up some forecast info to give an idea of additional power needed in cold weather would be good.

**Comment by springfall2008** [comment]
You can certainly run Predbat without Solcast, just comment out those config lines.

There isn't anything to forecast heat pump usage, it would be based on historical usage. If you have a way to forecast heat pumps it might be something that could be added but I wouldn't know what formula to use.

**Comment by springfall2008** [comment]
Closing for now, feel free to open new questions
