### ISSUE TITLE
Sunsynk inverter charge current 0A after grid charge slot or during solar not allowing the battery to charge from solar.

### ISSUE THREAD

**Issue by tmh88** [springfall2008/batpred#1313]
**Describe the bug**
After grid charge or during solar production (non-scheduled grid charge slot) the battery current drops to 0A not allowing the battery to charge from solar.

**Expected behavior**
I would expect the battery charge current to remain to allow charging of the battery via solar.

The sunsynk inverters charge from solar and discharge from battery along as the battery SOC > SOC setpoint for that time slot.

Both gird & solar charging of the battery is controlled by the max charge current and only charge from grid if grid charge is checked and battery SOC is < SOC setpoint.

Discharging is controlled by max discharge current & workmode selected. Limit to Home, and don't discharge battery to grid. Only if "Selling First" is selected then the battery will export to the grid.

I have followed the example yaml file in the repo.

**Predbat version**

8.3.0

**Environment details**

- Sunsynk Inverter and battery
- Standard HAOS installer
- app.yaml
[apps.txt](https://github.com/user-attachments/files/16254888/apps.txt)

**Screenshots**
![image](https://github.com/user-attachments/assets/9c9b5ec2-f7b2-4151-9165-f251e3d9648f)

![image](https://github.com/user-attachments/assets/0df7fc23-7687-4fe3-9923-bb339a88b484)

![image](https://github.com/user-attachments/assets/7866e33d-44af-468a-86b5-653e28a6e573)

**Log file**
[Logs 16-07-24 8-30.txt](https://github.com/user-attachments/files/16254889/Logs.16-07-24.8-30.txt)

**Comment by springfall2008** [comment]
So you are saying to start/stop a grid charge you have to change the target SOC to minimum for charge from solar only and to the target for grid charging?

**Comment by springfall2008** [comment]
Please test the version on 'main' which should have a fix for this issue

**Comment by tmh88** [comment]
> So you are saying to start/stop a grid charge you have to change the target SOC to minimum for charge from solar only and to the target for grid charging?

in short yes, there is also a check box for the time slot to enable/disable grid charging but i can write an automation based on the output binary_sensor.predbat_charging

**Comment by tmh88** [comment]
> Please test the version on 'main' which should have a fix for this issue

thank you, looks promising so far will leave it on test and let you know
![image](https://github.com/user-attachments/assets/372fa19b-14ab-4d4b-975f-4a7591353624)

if this works, i can write up and upload my configs and automations if that helps?

**Comment by springfall2008** [comment]
> > Please test the version on 'main' which should have a fix for this issue
> 
> thank you, looks promising so far will leave it on test and let you know ![image](https://private-user-images.githubusercontent.com/64529041/349645423-372fa19b-14ab-4d4b-975f-4a7591353624.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0ODMzMTYsIm5iZiI6MTcyMTQ4MzAxNiwicGF0aCI6Ii82NDUyOTA0MS8zNDk2NDU0MjMtMzcyZmExOWItMTRhYi00ZDRiLTk3NWYtNGE3NTkxMzUzNjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEzNDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YWVmYWMwZGE0NDJhZWM1MmVjYzdjZTI4ZWM3NDFlN2JlY2EzYzE2ZTEyZThhZTAyMmIxOThlNTM0NGY1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gFpSqRKEhvyuJL_Lb73QXNwXtPkA9gj7LwV49uVfTQQ)
> 
> if this works, i can write up and upload my configs and automations if that helps?

Yes please

**Comment by tmh88** [comment]
@springfall2008 log file as discussed
[Log 21-07-24.txt](https://github.com/user-attachments/files/16323592/Log.21-07-24.txt)

**Comment by springfall2008** [comment]
Not sure I see why, the discharge rate is set back to full at 8:30 when charging stops?

2024-07-21 08:30:18.082555: Switch sensor.predbat_SK_0_scheduled_charge_enable is now off
2024-07-21 08:30:18.082694: Inverter 0 Wrote scheduled_charge_enable to False successfully and got off
2024-07-21 08:30:18.082730: Inverter 0 Turning off scheduled charge
2024-07-21 08:30:18.082803: Inverter 0 Call service template charge_stop_service = {'service': 'input_select.select_option', 'entity_id': 'input_select.test_sunsynk_work_mode', 'option': 'Limited to Home'}
2024-07-21 08:30:18.082856: Inverter 0 Call service input_select/select_option with data {'entity_id': 'input_select.test_sunsynk_work_mode', 'option': 'Limited to Home'}
2024-07-21 08:30:18.097567: Inverter 0 current discharge rate is 0.0 and new target is 6444
2024-07-21 08:30:23.123127: Inverter 0 Wrote 6444 to discharge_rate, successfully now 6444
2024-07-21 08:30:28.154124: Inverter 0 Wrote 120.0 to timed_discharge_current, successfully now 120.0
2024-07-21 08:30:28.154347: Not setting charging SOC as we are not within the window (now 07-21 08:30:00 target set_soc_minutes 30 charge start time 07-22 01:30:00)
2024-07-21 08:30:28.154417: Inverter 0 Current Target SOC is 10 already at target
2024-07-21 08:30:28.177420: Will not recompute the plan, it is 5.0 minutes old and max age is 10 minutes

Then after that you restart Predbat (no sure why):

2024-07-21 08:30:28.177499: iBoost model today updated to 0.0
2024-07-21 08:30:28.219728: Completed run status Idle
2024-07-21 08:30:29.469701: Info: record_status Idle
2024-07-21 08:30:29.481902: Saved current settings to /config/predbat_config.json
2024-07-21 08:34:03.731458: Stopping Predbat
2024-07-21 08:34:03.731670: Predbat terminating
2024-07-21 08:34:03.731875: Predbat terminated
2024-07-21 08:34:03.815786: Info: Web socket stopping
2024-07-21 08:34:03.817448: Info: Web socket stopping
2024-07-21 08:34:35.671295: Loading apps.yaml
2024-07-21 08:34:35.698699: Predbat: Startup predbat

**Comment by springfall2008** [comment]
So what's happening is once you reach your charged SOC it turns off discharge to hold the battery at that level and then turns it back on when the charging period ends

**Comment by tmh88** [comment]
> So what's happening is once you reach your charged SOC it turns off discharge to hold the battery at that level and then turns it back on when the charging period ends

The target soc was 10% and my batteries never dropped below 55% so I would expect it to discharge the batteries until 10%. Then hold at setpoint ?

![Screenshot_20240721_104502_Home Assistant.jpg](https://github.com/user-attachments/assets/60305582-e639-4ca2-a917-d78766b6f402)

**Comment by tmh88** [comment]
Battery soc wouldn't have dropped below 72% if predbat was controlling the inverter, currently just using test entities whilst testing

**Comment by springfall2008** [comment]
Oh I see, I know why I believe its a setting that perhaps shouldn't be that way, let me try a fix on main

**Comment by springfall2008** [comment]
Fix on main for testing

**Comment by tmh88** [comment]
@springfall2008 Thankyou, do i need to change to the sunsynk branch? dosent seem to be pulled into the main branch?

did you get anywhere with allowing the charge current to change when charging from solar?

**Comment by springfall2008** [comment]
did the fix work?

**Comment by tmh88** [comment]
> did the fix work?

Hi @springfall2008 yes the fix worked, been running for about a week or so now. I've also uploaded my configs for other if you want to add it to the documents.

Thanks for all your help and hard work
