### ISSUE TITLE
Pause mode not working on latest AIO firmware

### ISSUE THREAD

**Issue by dochtie** [springfall2008/batpred#1316]
**Describe the bug**
After updating to D0.612-A0.612 and BMS10 predbat is no longer able to control pause mode.

I am also unable to control pause mode directly via GivTCP so not really a predbat issue.

Raising for awareness and if anyone knows a temp workaround. As far as I know you can’t roll back a GE firmware update.

**Expected behavior**
Pause mode should work via GIVTCP. Pause mode works as normal through GE cloud portal.

**Predbat version**

8.3.0

**Environment details**

D0.612-A0.612 and BMS10 
AIO 

**Screenshots**

**Log file**
![IMG_9115](https://github.com/user-attachments/assets/7d11a186-8a8d-4122-a271-c124daee587c)

**Comment by gcoan** [comment]
Are you on the main GivTCP release or the beta?  I believe the beta has better aio support

**Comment by dochtie** [comment]
> Are you on the main GivTCP release or the beta? I believe the beta has better aio support

I’m on the main. Is the beta pretty stable do you know?

**Comment by dochtie** [comment]
@gcoan I gave it a try and it works on the beta (via GivTCP anyway). Thanks for pointing me in that direction!

**Comment by springfall2008** [comment]
Not a predbat issue as such, closing
