### ISSUE TITLE
Entities not found in PV Forecast vs Actual Chart Template

### ISSUE THREAD

**Issue by DarrenJCraddock** [springfall2008/batpred#1330]
**Describe the bug**
I have created all the charts using the code from charts template and the apexcharts-card.
They all appear to be working apart from the PV Forecast vs Actual chart which has the following errors:
Entity not available: sensor.givtcp_sa2243g277_pv_power
Entity not available: sensor.givtcp_sa2243g277_energy_today_kwh

These look to be hardcoded to a specific inverter. All other graphs seem to be ok, so are there generic sensor names that should be used instead?

**Comment by DarrenJCraddock** [comment]
I've changed for my specific inverter ID, but I'm wondering why this only needs to be done for this chart.

**Comment by gcoan** [comment]
yes they should be changed for your specific inverter id

I'll change the charts to make this clearer

**Comment by gcoan** [comment]
Closed with PR 1377
