### ISSUE TITLE
Addon Directory not found

### ISSUE THREAD

**Issue by tinagreenwood** [springfall2008/batpred#1367]
Hi,
I have run the Predbat Install and pressed the Start button. When I then go to the File Editor I cant find the /Addon_configs/ folder and hence can’t edit the Yaml config file as per the instructions. Could you please recommend what I have done wrong ?

**Comment by gcoan** [comment]
Suspect you have not followed the install documentation fully, in particular the need to turn the Enforce Basepath option to off if you are using File Editor

see https://springfall2008.github.io/batpred/install/#editing-configuration-files-in-home-assistant

**Comment by tinagreenwood** [comment]
Thank you for such a quick response. Much appreciated. On 15 Aug 2024, at 21:54, Geoffrey Coan ***@***.***> wrote:﻿
Suspect you have not followed the install documentation fully, in particular the need to turn the Enforce Basepath option to off if you are using File Editor
see https://springfall2008.github.io/batpred/install/#editing-configuration-files-in-home-assistant
