### ISSUE TITLE
Iboost Today Attribute Remains At Zero

### ISSUE THREAD

**Issue by nbullus** [springfall2008/batpred#1378]
**Describe the bug**
The **predbat.iboost_best** entity contains the total predicted iBoost charge across the whole Predbat plan (36 hours in my case). The **today** attribute on this sensor should hold just the predicted iBoost total for today, but remains at zero.

**Expected behavior**
 The **today** attribute on this sensor should update at midnight and hold the predicted iBoost total for today. In the example screenshots below, this should be set as 6.5 kWh for today and update to 9.75 kWh at midnight. The attribute should also be updated if the the predicated iBoost charge changes with any plan changes.

**Predbat version**

8.3.5

**Environment details**

- GivEnergy AIO
- Standard HAOS installer

**Screenshots**

![image](https://github.com/user-attachments/assets/8b0dde7b-a789-41df-a9d3-9b1711eee7bd)

![image](https://github.com/user-attachments/assets/52113c94-fa86-428a-8060-95f2ebb564a4)

![image](https://github.com/user-attachments/assets/7e6dc996-91c3-44a8-9286-5c92bbca8e27)

**Log file**

Not needed. Trefor has already established the root cause.

**Comment by springfall2008** [comment]
Fixed on main for the next release

**Comment by nbullus** [comment]
Tested on main and planned iBoost over next 36 hrs shows correct figures in Today attribute.

**Comment by springfall2008** [comment]
Release as v8.3.7
