### ISSUE TITLE
Feature suggestion: battery headroom

### ISSUE THREAD

**Issue by psimonkey** [springfall2008/batpred#14]
Great project - thanks for all the hard work.  I have a suggestion for a feature.  I'd like to be able to leave space in the battery when it charges from the grid.

I have a 3.6 kW hybrid inverter with a 9.5 kWh battery and 4.4 kW of PV.  I'm on the Octopus Flux tariff.  In the middle of the day, if my battery is full and the PV is generating (for example) 4.4 kW, then 3.6 kW goes to the grid, but the remaining 800 W is lost.  If there was space in the battery, some would go to the grid and some to the battery, and nothing would be lost.  I can't see a way of doing that with the current config options.

The simplest implementation I can think of would be a "best_soc_max" that sets the maximum that'll charge from the grid, leaving some space for the surplus later in the day.  Along with that, setting the battery charge power to (for my example case) 800 W would mean at max PV generation 3.6 kW goes to the grid and the excess to the battery.

More sophisticated would be to calculate the likely excess, based on the max output of the inverter, the capacity of the PV and the solar forecast, and use that to set the max SOC during the grid charge.

**Comment by springfall2008** [comment]
If you set your inverter_limit correctly (this is the max AC limit) then this is all taken into account. Predbat optimises for cost so if it's cheaper to charge the battery less for the above reasons then this will be accounted for automatically. Do you see cases where this is not happening?

**Comment by springfall2008** [comment]
The sim isn’t to avoid clipping totally but to end up with the lowest cost outcomes taking into account the risk of bad weather as well.

the PV generation predictions come from Solcast

**Comment by psimonkey** [comment]
Probably worth mentioning that a headroom feature is probably only really useful with the Flux tariff.  Leaving headroom in the battery is quite safe with Flux - 1 kWh less charging in the morning saves 20p of import, and means you miss out on 20p of export around midday.  If the weather's bad then a bit of extra import at 30p during the day or lost export at 30p in the evening isn't much difference.  With other tariffs where the difference between cheap import and normal export is larger, it's probably not worth the risk.  You've already got the best_soc_min setting (which potentially increases cost), so would a best_soc_max be reasonable?

**Comment by springfall2008** [comment]
Sure, I could add the feature for the next release if you think it’s useful

**Comment by springfall2008** [comment]
Please see the latest release:

https://github.com/springfall2008/batpred/releases/tag/v6.8

**Comment by psimonkey** [comment]
Great - cheers.  I'll give it a go and feed back.
