### ISSUE TITLE
Check Fox ESS Configuration?

### ISSUE THREAD

**Issue by letsstartbeinganon** [springfall2008/batpred#1401]
Just thought I'd post this here as I think I've managed to get Batpred working on my Fox ESS inverter, connected via an Elfin EW11 modbus and using Nathan's Fox ESS Modbus tool.

I know many people have requested this type of config file so thought I'd share mine.  It would be great if other people could cast their eyes over this to make sure it is set up optimally?

https://pastebin.com/WtgC3Xt6

**Comment by springfall2008** [comment]
Thanks, I'll push it to the templates area

**Comment by letsstartbeinganon** [comment]
> Thanks, I'll push it to the templates area

Thanks Trefor, I've just noticed that in line 258 on your template my account number is available as I wrote it in full rather than using the auto-sensor that is used elsewhere. Any chance you could remove that?

**Comment by springfall2008** [comment]
Sorry now done
