### ISSUE TITLE
Inverter using grid rather than battery during peak period

### ISSUE THREAD

**Issue by johnleeshore** [springfall2008/batpred#1414]
**Describe the bug**
I'm on Octopus Flux: Inverter is using grid to top up solar during peak hours of 4 to 7pm

**Expected behavior**
Expecting inverter to use battery rather than grid for topping up solar for house load during peak hours

**Predbat version**
8.4.1

**Environment details**
- GIV-HY3.6
- 9.5kWh Battery
- Standard HAOS installer
- Predbat 1.1.23

**Screenshots**
This is what the plan was:
<img width="842" alt="Screenshot 2024-08-31 at 13 00 28" src="https://github.com/user-attachments/assets/d9965374-c37f-4073-a92e-139cde4e73d3">
This is what happened:
<img width="342" alt="Screenshot 2024-08-31 at 19 14 42" src="https://github.com/user-attachments/assets/7ef6114f-3e58-4cb9-9f59-15dc51d5706b">
These are my settings:
[Predbat Web Interface.pdf](https://github.com/user-attachments/files/16825641/Predbat.Web.Interface.pdf)
**Log file**
[predbat.log](https://github.com/user-attachments/files/16825676/predbat.log)

**Comment by springfall2008** [comment]
Sorry what do you mean "Grid to top up solar"?

**Comment by johnleeshore** [comment]
Sorry I meant the inverter is using the grid for extra house load during the peak time rather than using the battery which I would have expected so that it wasn't using peak electricity from the grid.

**Comment by springfall2008** [comment]
Where do you see it using grid, the plan only shows battery in Eco and exporting battery?

**Comment by johnleeshore** [comment]
Yes the plan shows Eco and exporting battery but what happened (see graph below) was that the battery wasn't used and the inverter imported from the grid only. I would have expected any excess load to have come from the battery but the battery charge was maintained.
<img width="388" alt="Screenshot 2024-09-01 at 17 39 20" src="https://github.com/user-attachments/assets/4a512248-e7ec-44d4-910f-3ad5e43c714c">

**Comment by johnleeshore** [comment]
<img width="1453" alt="Screenshot 2024-09-01 at 17 48 46" src="https://github.com/user-attachments/assets/9dbc2f07-2ca7-4123-aec8-969d9183ded7">

**Comment by johnleeshore** [comment]
Although today it does seem to have worked as I thought it would:
<img width="291" alt="Screenshot 2024-09-01 at 17 59 35" src="https://github.com/user-attachments/assets/a93258b4-623b-4f42-8b1d-470b2282f2bf">
I did uncomment
  export_limit:
    - 3600
in apps.yaml this morning. But I can't see this making a difference

**Comment by johnleeshore** [comment]
I was just checking apps.yaml on web ui and not that the scheduled discharge enable entity points to a predbat sensor which is different to the other entities. Is this relevant?
<img width="1472" alt="Screenshot 2024-09-02 at 12 31 14" src="https://github.com/user-attachments/assets/05fff6a5-7053-4593-a67d-2cf71e8c8422">

**Comment by johnleeshore** [comment]
Found out the issue. The Discharge 1 Setting in the Remote Control area was somehow set at 100% despite the slot times being 00.00. Changed it to 4% which has sorted the issue today.
