### ISSUE TITLE
PredBat plan shows erroneous character when displaying using ingress

### ISSUE THREAD

**Issue by charlie-chester** [springfall2008/batpred#1423]
**Describe the bug**
When looking at the HTML plan via the Ingress method, the column displaying the cost has an erroneous extra character before the "£" sign. This is only a problem when viewing on Firefox.

**Expected behaviour**
To display the cost cleanly without extra characters. 

**Predbat version**
Add-on V 1.2
PB V 8.4.4

**Environment details**

- GivEnergy
- Standard HAOS instal
- Viewing HA through Firefox on macOS. 

**Screenshots**
<img width="1738" alt="predbat_–_Home_Assistant_and_predbat_–_Home_Assistant" src="https://github.com/user-attachments/assets/bfc8a281-2e11-47aa-8c10-93358b862fff">

**Comment by springfall2008** [comment]
Fix has been pushed to main for the next release
