### ISSUE TITLE
Chart inconsistencies with WebUI in v8.4.8

### ISSUE THREAD

**Issue by SwiftRR** [springfall2008/batpred#1459]
**Describe the bug**
Chart display on web portal doesn't fit vertically (on Safari iMAC):
<img width="1795" alt="image" src="https://github.com/user-attachments/assets/3df01b56-09de-44be-88e1-c8e84f5d7605">

Charts works fine on tablet and phone (IoS)

New PV7 chart
This is headed as 'Solar Forecast' but is displays the last historical 7 days which is not useful (for me). The vertical cut off screen is more obvious here:
<img width="1821" alt="image" src="https://github.com/user-attachments/assets/5122c7a1-86d3-4a96-b9e4-f68992dceb68">

**Expected behavior**
Charts fit screen!

**Predbat version**
v8.4.8

**Environment details**
GE AC3.0 AC coupled
Standard HAOS install on pi

**Screenshots**
See above

**Comment by springfall2008** [comment]
Fix on 'main' for testing

**Comment by SwiftRR** [comment]
I have tested the 'main' webUI charts and they all look good now. y axis fits and everything scales nicely.

Do we need the 'double inner scroll bar' that I see on computer (iMac)? The top little scroll bar just moves the title box up and down by a tiny amount. In the title box, could the bat be moved up a little and the vertical space reduced. It takes up a fair bit of space.

A nice correction of the y axis scale. Thanks

Rob

**Comment by springfall2008** [comment]
I should probably get rid of the little top scroll bar, not sure how to....
