### ISSUE TITLE
Suboptimal IOG plan

### ISSUE THREAD

**Issue by nickgee31** [springfall2008/batpred#1489]
**Describe the bug**
My GivEnergy inverter is today freeze discharging and discharging mid-afternoon, leaving no battery available for the evening.

**Expected behavior**
All discharges should happen as late as possible in the day.

**Predbat version**

V8.4.9

**Environment details**

- GivEnergy Gen 2 5KW + 9.5 battery
- Standard HAOS installer

**Screenshots**
<img width="491" alt="Screenshot 2024-09-28 at 12 41 07" src="https://github.com/user-attachments/assets/a7234741-3508-4779-8bd6-f0c752dbbc62">
<img width="490" alt="Screenshot 2024-09-28 at 12 41 16" src="https://github.com/user-attachments/assets/4afa5e33-ae81-4d04-bd1e-ad0733b141c6">

**Log file**
[predbat.log](https://github.com/user-attachments/files/17174236/predbat.log)

**Comment by gcoan** [comment]
I'd suggest that whilst the plan may be discharging earlier than you'd like, it's a perfectly reasonable plan that retains enough battery charge to last you through to the IOG cheap rate charge period with no grid imports 

What I would question though is your load sensor, it's predicting very very low house load every half hour slot, so low that any load scaling is in the margins of error. I think you need to check the sensor is giving an accurate load history as it seems too low. 

If it is correct then arguably the plan is fine as is. If you want to keep more charge for later then increasing best soc keep might do what you want. 

There are other issues on the recent freeze discharge changes. 

See also #1462

**Comment by nickgee31** [comment]
Hey,

I am generally not here on weekends so it is quite reasonable that my load is that low on a weekend. I guess what I am getting at is that on the off chance that load is increased then it should leave enough before the cheap period at 23:30 - not potentially leave with nothing left.

**Comment by gcoan** [comment]
It would be worth you trying to configure a higher level for best_soc_keep to advise Predbat of a soc level to keep.  This is not a hard soc level that will always be kept (that's best_soc_min) but advises Predbat of a soc level that you wish to keep for 'just in case's'

I do agree with your sentiment though, delaying forced discharge as long as possible is a good strategy in case house load is higher than expected

**Comment by gcoan** [comment]
Best_soc_keep definitely makes a positive impact in how much soc is retained in case of unexpected load. 

My plan tomorrow with best_soc_keep set to my default 0.5, most of the day the battery is in freeze discharge mode and whilst Soc drops the battery never empties (assuming the load forecast is correct):

![image](https://github.com/user-attachments/assets/29c82f0e-8231-4cd0-9020-acc454d67c50)
![image](https://github.com/user-attachments/assets/791298ad-6c2b-4c7a-b324-b23c9eed9c75)
![image](https://github.com/user-attachments/assets/ac9a95f8-dd12-42ae-b8ff-de45703148e4)

I increased best_soc_keep to 1.5 (kWh) and there's less freeze discharging through the day and the Soc is about 10% higher:

![image](https://github.com/user-attachments/assets/91f4b25f-62b7-483f-8748-ddf063a07f40)
![image](https://github.com/user-attachments/assets/855e4fc9-ebc9-4e76-80fc-03ea87fbd95d)
![image](https://github.com/user-attachments/assets/029ddc0b-a548-4c8b-9e97-a9575d48f8a7)

**Comment by nickgee31** [comment]
Thank you. The issue with changing the best_soc_keep is that it now leaves the battery with 20% at the end of the day rather than down to 5% like I would like. It used to be better when you could have best_soc_keep at 2.0 and best_soc_min at 0.5 - that used to work rather well but that functionality was removed.

**Comment by gcoan** [comment]
> It used to be better when you could have best_soc_keep at 2.0 and best_soc_min at 0.5 - that used to work rather well but that functionality was removed

That's pretty much what I have set, bsk is now 1.5 and bsm 0.5. Not sure what you mean by the functionality was removed. I'm not on iog so can't test exactly but give it a go and see what it does for your Soc. 

If this retains too much Soc you could dynamically change the bsk with an automation to different levels in the evening to further reduce the retained soc if you wanted to

**Comment by nickgee31** [comment]
What I mean is that setting best_soc_min to 0.5 would actually mean it would discharge down to that level, whereas it doesn't do that anymore.

To be honest I don't want to introduce automations to change levels, it should just be a set and forget kind of thing like it used to be.

**Comment by phiebs** [comment]
I have been tweaking various settings to try and achieve the same result. The way I’ve done this is to set the `rates_export_override` to prevent discharging in the peak evening slot and also to encourage discharging just before the cheap rate kicks in. I do this with `rate_increment` and set it to -10 for peak period and +10 from 22:00-23:30. You may need to tweak the times and increment rates for your particular setup but it works well now for me.

**Comment by phiebs** [comment]
Just to follow up after giving this some more thought, it would be super cool to have a switch that did a “export all battery just before lower rate starts” or similar. We know the battery kWh value and the max rate of discharge so should be easy to calculate when to start this. E.g. 9kWh in battery with 6kW discharge rate, would equal 1.5 hours of discharge to end exactly at the start of the lower rate window. This would change all the time but once the capacity remaining is greater than time until cheap rate x max export power we can safely trigger an export without fear of running out.

**Comment by nickgee31** [comment]
I think that's kind of what we need @phiebs, the tweaking of export rates is okay but just thinking if there was some early IOG slots then the battery wouldn't discharge before them if the export rate was too low.

**Comment by phiebs** [comment]
Yep, that’s why I think the toggle to discharge before next cheap slot would solve the issue. Could probably write an automation to do just this but would be way more convenient within predbat. P.s. as we come into winter the increment adjustment on export rates helps with avoiding any use during peak hours to maximise gains with DFS sessions

**Comment by nickgee31** [comment]
@springfall2008 Is this something you think may be possible at all? To delay discharges until the next cheap slot to prevent running out of battery before the end of day.

**Comment by gcoan** [comment]
> as we come into winter the increment adjustment on export rates helps with avoiding any use during peak hours to maximise gains with DFS sessions

Yet to see what shape DFS takes this winter but this is exactly what I did last year to discourage predbat from peak rate discharging

**Comment by springfall2008** [comment]
The original post issue was zero load prediction, fixing that would have solved the problem.

The secondly issue is that discharge freeze (exporting solar directly) causes less losses than charging the battery and exporting it later. If that feature were disabled (currently its hard wired on) then you would probably get what you wanted.

You might also try including load_scaling10 to make your worst case load predictions a bit higher

**Comment by nickgee31** [comment]
The load prediction was just really low for a weekend, I will adjust the load_scaling10 to compensate for that.

Can I edit something in the code locally to disable the feature to see how it behaves?

**Comment by nickgee31** [comment]
Managed to find it, in config.py on line 1031. Changing support_discharge_freeze to False has resulted in a much better plan being created and not discharging until last thing in the day.
