### ISSUE TITLE
Predbat with agile and Ohme

### ISSUE THREAD

**Issue by retr083** [springfall2008/batpred#1511]
**Describe the bug**
Every time EV is plugged in and Ohme schedules a charge the agile rates change to the lowest half hourly rate for the entire time the car is scheduled to charge (see image, 5.29p being the lowest price at 22:30-23:00 but duplicating across the entire ev charge schedule). I am not using predbat to schedule charges.

**Expected behavior**
Agile rates should not change but predbat should know what times the car is going to charge.
**Predbat version**

8.4.11

**Environment details**

- Givenergy 5KW hybrid & 9.5kwh battery
- Appdaemon install
- Octopus addon
- Ohme addon

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.

![Screenshot 2024-10-05 190726](https://github.com/user-attachments/assets/f323001b-3044-4f9e-8a52-18ee64081a3d)

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)

[2024-10-05 192042.835978 WARNING Ap.txt](https://github.com/user-attachments/files/17267099/2024-10-05.192042.835978.WARNING.Ap.txt)

**Comment by springfall2008** [comment]
Hmm, its probably as its designed for intelligent GO, I didn't know Ohme could schedule without GO. I think I can make that an option for you...

**Comment by retr083** [comment]
that would be great, this is the entity in the ohme integration that gives the list of charge slots, sensor.ohme_charge_slots

**Comment by springfall2008** [comment]
Please try updating to 'main' and setting

octopus_slot_low_rate: False

In apps.yaml - this will tell Predbat to not change the rates based on the charge slots

**Comment by retr083** [comment]
Working perfectly, thanks so much
