### ISSUE TITLE
Manual forced discharge freeze (override option) is prevented by state of the "set discharge freeze switch" being off from v8.4.11 onwards

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#1551]
**Describe the bug**
A few of us have noticed that the battery continued to charge when Predbat was in Freeze Discharge mode.  Digging into this further I can see that on my system Predbat is not changing the battery charge rate to zero, nor is it enabling the PauseCharge mode on the inverter.  If I roll back to versions 8.4.10 or earlier, this function works as expected.

This was the version where a toggle was added to switch off freeze discharge, so code change seems related

Additionally it seems to set a different status message of hold discharging, rather than freeze discharging in the later version where it is not working.

Can be replicated by selecting a manual force discharge freeze

Freeze charge seems to work as expected, however I don't see it change the battery discharge rate to zero, but it does raise the reserve. I see this on all versions, so assume it is expected behaviour

**UPDATE** When it does the undesirable behaviour, Predbat status is hold discharge rather than freeze discharge

**UPDATE 2** It is related to if the set discharge freeze switch is on or off - see my final comment

**Expected behavior**
For the battery charge to be paused by setting the battery charge rate to zero and the inverter pause mode to PauseCharge

**Predbat version**

behaviour seen 8.4.11 onwards

**Environment details**

- AC3 2x 5.2kWh latest inverter firmware with pause Mode
- Standard HAOS installer 

**Screenshots**

<img width="303" alt="image" src="https://github.com/user-attachments/assets/40b84739-6cb9-40cf-af50-df10151e99d6">

**Log file**
Log file attached, however it covers testing across multiple versions to identify where the break happens.
[predbat.log](https://github.com/user-attachments/files/17436023/predbat.log)

**Comment by mpartington** [comment]
![Screenshot_2024-08-22-06-28-15-691_com facebook katana](https://github.com/user-attachments/assets/d181bd2e-2814-411c-ad34-30c51e0dee7b)

**Comment by gcoan** [comment]
Predbat 8.5.1

I'm seeing freeze discharging working fine, both battery pause is set and charge rate is set to zero correctly

![image](https://github.com/user-attachments/assets/29e2237b-beaf-4b90-a5f6-ab1d1136cf9f)
![image](https://github.com/user-attachments/assets/546209b0-a59f-4d2b-92c9-2e2b56bd1fc5)

**Comment by mpartington** [comment]
You know what, it is for me now! I tried all sorts of downgrades, upgrades,
restarts and it was repeatable. Only thing new for me is a HA core update.

Will do some more testing later and probably close this off

**Comment by gcoan** [comment]
🤷‍♂️

**Comment by mpartington** [comment]
Ok, seems to have repeated it. I accidentally turned on discharge instead of freeze discharge. I cancelled that and tried freeze discharge and it's gone back to not setting pause or charge rate. The big vlusle.seems to be the status changes to hold discharging, rather than freeze discharging.

There must be a trigger sequence that upsets predbat.

![Screenshot_2024-10-19-15-11-09-758_io homeassistant companion android](https://github.com/user-attachments/assets/1d371ccb-4098-480e-a9ef-b418f0cfd3bc)

Will.grab logs when home

**Comment by mpartington** [comment]
[write_log_inv_1.log](https://github.com/user-attachments/files/17445765/write_log_inv_1.log)
[predbat.log](https://github.com/user-attachments/files/17445767/predbat.log)

**Comment by mpartington** [comment]
**SOLVED**
And it is related to the introduction of the 'switch.predbat_set_discharge_freeze' entity.

If this is turned OFF, and you select manual force discharge freeze, then it sets Hold Discharging (but doesn't set pause or change charge rate to zero)

If it is turned ON and you select manual force discharge freeze, then it sets Hold Discharging and it **DOES** set pause and change charge rate to zero

Now as a user I would intuitively assume that if I select an override, then that will override any other setting (which it doesn't), so I would say this is still a bug. However it is something I could live with either way now I understand it.

Trefor, please close (or add to improvement queue) depending on your view

**Comment by gcoan** [comment]
I have to admit I think I've seen freeze charge not working as it should do when I set a manual session but never looked into it.

Can you please check if there is a similar pattern with freeze charge @springfall2008 ?

**Comment by springfall2008** [comment]
Well tracked down and pushed a fix on 'main' for testing.

I've started to add unit testing for the execute plan part of the code and introduce this fix along with some other fixes/simplifications. Now set_charge_freeze/set_discharge_freeze has no impact on the plan execution it will only change if the plan will include these actions.

**Comment by mpartington** [comment]
And the plans:
![Screenshot_2024-10-22-09-19-10-441_com facebook katana](https://github.com/user-attachments/assets/7dcf14bc-e21b-4ab9-862e-72b5c78922b0)
![Screenshot_2024-10-22-09-19-06-925_com facebook katana](https://github.com/user-attachments/assets/64af14db-5e06-40f3-9848-04938fb701e8)

**Comment by nbullus** [comment]
I'm on 15p export and was definitely getting Freeze Discharges prior to testing the 'main' version. Worth Trefor taking another look to see why it's stopped Freeze Discharging at the 15p export rate.

**Comment by mpartington** [comment]
Still.not seeing any Automatic freeze discharge on my plans, but the subject of this ticket is fixed.
