### ISSUE TITLE
Improve the accuracy of the nord data agile prediction

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#1562]
**Is your feature request related to a problem? Please describe.**
I've noticed that whilst the nord data next day market prices give a broad indication of the shape of the agile prices, there's always a variation.

I was thinking that it was due to regional pricing, my agile rates are always 0.7p more than @swiftrr in Yorkshire and the nord data feed and predbat calculator doesn't reflect that, so thinking that what is needed is a regional adder option.

But looking at the prices on a number of days, it's not as simple as that.

October 12th predicted 
![image](https://github.com/user-attachments/assets/e39386e4-8a05-44cc-aa13-b42fc2d628a7) 

12th actual 
![image](https://github.com/user-attachments/assets/f565c121-009e-4b51-a09c-27d9396e08b0)

13th predicted 
![image](https://github.com/user-attachments/assets/97c7f538-5561-427d-86b5-abd0c3cf616c)

13th actual 
![image](https://github.com/user-attachments/assets/5e0491e8-317d-4c15-b365-a2e649e05756)

20th predicted
![image](https://github.com/user-attachments/assets/81ce2122-b335-4429-b450-479d9a2bca00)

20th actual 
![image](https://github.com/user-attachments/assets/faa71c85-5bb6-4537-95c3-4d6966f79281)

21st predicted 
![image](https://github.com/user-attachments/assets/72186756-3441-4306-88a2-8e1bc861b89b)

21st actual 
![image](https://github.com/user-attachments/assets/58c145f1-a68e-4fb1-b858-51abdd48a676)

**Describe the solution you'd like**
Reviewing the predictions against actuals I believe:

- there is a regional adder that isn't currently included that if there was, could improve prediction accuracy 
- negative price predictions are overstated. Eg -12.98p predicted for  3:30 Monday 21st, actually was -0.92p. I think there's some damping that Octopus apply 
- it probably needs an indepth comparison of actual to prediction to work out the adjustment factors 

Maybe the agile prices prediction API could help improve the prediction accuracy https://prices.fly.dev

**Comment by SwiftRR** [comment]
To add to comment from @gcoan, I live in Yorkshire region and I believe that @gcoan is in Eastern England region.

The table below compares Agile rates for these 2 regions between 19:00 and 22:30 today (23-10-2024).
<img width="678" alt="image" src="https://github.com/user-attachments/assets/58c13c6b-2b0e-4047-ab15-3aea328ed374">
Source: https://files.energy-stats.uk/csv_output (showing historical Agile rate 2018-2024)

You can see the differences between the rates across regions are greater when the Agile rates are higher.

I would presume that the Nordpool prediction is for the whole GB.

For rates close to the fixed export rate of 15p, this may result in Predbat making a different prediction dependent of the region.

Rob

**Comment by gcoan** [comment]
Thanks Rob

Another example of why improving the accuracy of the nord data prediction is important:

Tonight's norddata prediction is for rates to drop overnight tonight and it to be cheaper to charge the battery up than to export the solar generation today.  So Predbat is scheduling my battery to be on freeze discharge for most of the day, only letting it half fill up.

![image](https://github.com/user-attachments/assets/ff5efe45-255a-4d7f-b536-e59791d7f240)
![image](https://github.com/user-attachments/assets/fdb44c82-763e-4f1a-a1b8-4bdc817c8600)

But if that forecast is a penny or two out, the time at which the cheaper rates come in is slightly different, then it would have been better to keep some of the generated solar rather than exporting it all.

So for me today I will put some force idle's in to give a bit more buffer space and retain a bit more solar. Less efficient but a bit safer

**Comment by SwiftRR** [comment]
For comparison, this is my plan from 11:50 am

<img width="968" alt="image" src="https://github.com/user-attachments/assets/e62bac50-e0bc-4ee1-bb65-9cba5b745d27">

I will be interesting to see how the Nordpool predictions stand up after 4 pm when the Octopus rates come through ........ and to see Predbat's predictions then.

Rob

**Comment by SwiftRR** [comment]
And a direct comparison. We have different Nordpool predictions with different Predbat predictions. So are the Nordpools Regional?

<img width="682" alt="image" src="https://github.com/user-attachments/assets/224470a4-aa7d-4b50-b179-5fa7feb8f4ea">

Rob

**Comment by gcoan** [comment]
> We have different Nordpool predictions with different Predbat predictions. So are the Nordpools Regional?
> 

Ah I think I remember that the nordpool data is used to create a series of delta's on the 'roll forward' prices which of course do incorporate regional variation.  So the way predbat works already may give some of the regional pricing variation I thought was needed, but I think there is still opportunity for accuracy improvement in the predictions.

**Comment by SwiftRR** [comment]
And here's the end of my analysis. Nordpool predictions against Octopus actuals:

<img width="674" alt="image" src="https://github.com/user-attachments/assets/fe1b2783-9ce0-4911-a974-b568c7190191">

Although the two sets of data are in the same ballpark, I am surprised at some of the differences. Not quite 'all over the place', but look at 23:00, 00:30 and 02:30.

Still better though than just carrying forwards rates from previous 24 hours.

Rob

**Comment by gcoan** [comment]
I think I've posted enough before and after screenshots already, but for completeness here is my actual Octopus rates for tonight

![image](https://github.com/user-attachments/assets/1e2d0bde-68f7-440d-aec4-6ff3c43197e6)

Comparing the same 3 times Rob did:

23:00 predicted 14.11, actual 18.08
00:30 predicted 15.46, actual 11.47
02:30 predicted 13.33, actual 9.48

A lot of variation, both up and down

**Comment by SwiftRR** [comment]
Going right back to the first post of @gcoan for this issue:
> **Is your feature request related to a problem? Please describe.**
> I've noticed that whilst the nord data next day market prices give a broad indication of the shape of the agile prices, there's always a variation.

From our analysis, it seems that Nordpool predictions indicate the direction of travel of future rates. However, the error range is such that some actual rates are higher and some lower than the Nordpool predictions. These differences can be significant.
The Nordpool predictions do seem to take into account regional variations in rates (Ofgem).

Can Predbat take these rather random variations into account, or is Predbat doing as much as it can by considering the direction and extent of travel of the rates?

Rob

**Comment by gcoan** [comment]
Agreed Rob,

> Can Predbat take these rather random variations into account, or is Predbat doing as much as it can by considering the direction and extent of travel of the rates?

But I'd go a step further and ask an alternative question:

Should Predbat be basing its charge and discharge activity for today (e.g. freeze discharge and export all solar, force discharge the battery) based on the expectation that the norddata derived rates are 100% correct when we now clearly see that they are not.

Would it be better for Predbat to apply some form of 'uncertainty factor' to the norddata future rates to recognise the inherent deviations in projected to actual rates that are being seen and the plan be more conservative as a result?
Maybe this won't be the optimum plan all the time but better to let the battery charge unnecessarily and then have to force discharge it than let the solar be exported and have to be imported later on at a higher rate than norddata predicted,  or hold onto the charge and not export it, maybe need to export it later on when the future agile rates are known?

**Comment by SwiftRR** [comment]
With both Nordpool and Octopus values, we have bracketed values based on losses.
For me, the bracketed cost is typically about 1 p higher.
From our analysis today (and experience from recent days), the Nordpool values can be significantly 'out' (±4p today).

There could be a case for showing the bracketed Nordpool cost as a ± value
But this would likely confuse many users and I could just imagine a deluge of queries. 

More questions than answers!

Rob

**Comment by gcoan** [comment]
Hi @springfall2008 I see you have introduced improvements with the nord data handling in 8.5.2 #1567

Looking at the change history it looks like some of the documentation changes you made for this new feature got lost in energy-rates.md:

![image](https://github.com/user-attachments/assets/9932b45c-6881-4f71-8ff4-13574f5d4995)

**Comment by springfall2008** [comment]
I think this has been fixed with today's release, please check?

**Comment by gcoan** [comment]
> I think this has been fixed with today's release, please check?

Thanks Trefor for the enhancements, I am away from tomorrow for a few weeks so I won't have the chance to upgrade until I get back

**Comment by springfall2008** [comment]
Please open a new ticket in case of issues

**Comment by gcoan** [comment]
> Please open a new ticket in case of issues

I have installed 8.5.3 and checked the nord data and actual Agile prices for today and they seem to be a lot closer than they were before. Quite a few prices were predicted to within a decimal place of the actual price, and where there were variations they were at most a couple of pence.  The pre-4pm charge plan and the post-4pm charge plan were quite similar.

Will need to separately look at negative agile prices as none coming through at the moment, but this looks a big improvement, thanks
