### ISSUE TITLE
No Export available after upgrading to Outgoing octopus 12M fixed tariff

### ISSUE THREAD

**Issue by Dipstikk** [springfall2008/batpred#1574]
Predbat cannot set up an export time.

**Expected behaviour**
I would expect an export session to be available in the plan

**Predbat version**

8.5.3

**Environment details**

- Inverter and battery setup
- AC3.0 2x8.2 batteries
- Standard HAOS installer or Docker
- Standard
- Anything else?
**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.
![IMG_7679](https://github.com/user-attachments/assets/3e20c6ba-bcf9-4652-8372-f7a109641ec5)

**Log file**Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please 
[Copy of Predbat Log File.docx](https://github.com/user-attachments/files/17569558/Copy.of.Predbat.Log.File.docx)
enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)

**Comment by Dipstikk** [comment]
Hi Mike, I do not have a template line in my apps.yaml file, it’s one of the first things i removed when I first set it up, note, Predbat has been working absolutely perfectly for over 12 months.

Please check attached yaml to see if you can find the template line, i also notice that the predbat log file I collected last night is dated 02/09/2024, not current, is this correct?
# ------------------------------------------------------------------
# This is an example configuration, please modify it
# ------------------------------------------------------------------
---
pred_bat:
  module: predbat
  class: PredBat

  # Sets the prefix for all created entities in HA - only change if you want to run more than once instance
  prefix: predbat

  # Timezone to work in
  timezone: Europe/London


  # Set to auto-match with a GivEnergy serial number, but you can override the serial or the sensor names
  # if it doesn't work or if you have more than one inverter you will need to list both
  geserial: 're:sensor.givtcp_(.+)_soc_kwh'
  #geserial2: 're:sensor.givtcp2_(.+)_soc_kwh'
  
  # ha_url: 'http://192.168.0.65:8123'

  #
  # Sensors, more than one can be specified and they will be summed up automatically
  #
  # For two inverters the load today would normally be the master load sensor only (to cover the entire house)
  # If you have three phase and one inverter per phase then you would need three load sensors
  #
  # For pv_today if you have multiple solar inverter inputs then you should include one entry for each inverter
  #
  load_today:
    - sensor.givtcp_{geserial}_load_energy_today_kwh
  import_today:
    - sensor.givtcp_{geserial}_import_energy_today_kwh
  export_today:
    - sensor.givtcp_{geserial}_export_energy_today_kwh
  pv_today:
    - sensor.givtcp_{geserial}_pv_energy_today_kwh

  # Load forecast can be used to add to the historical load data (heat-pump)
  # To link to Predheat
  # Data must be in the format of 'last_updated' timestamp and 'energy' for incrementing kWh
  #load_forecast:
  #  - predheat.heat_energy$external
  #
  # If you enable ge_cloud_data then the load/import and export data will be fetches from the GE cloud instead of from GivTCP sensors
  # this is usually less efficient and of course prone to internet downtime, but could be useful if you lost your GivTCP data
  # Set the serial to the inverter serial to pull the data from and the key to your API key
  # When this is set load_today, import_today and export_today are not used
  #
  # ge_cloud_data: False
  # ge_cloud_serial: '{geserial}'
  # ge_cloud_key: 'xxxx'
  #
  # Controls/status - must by 1 per inverter
  #
  num_inverters: 1
  #
  # Run balance inverters every N seconds (0=disabled) - only for multi-inverter
  # balance_inverters_seconds: 60
  #
  # When set use the REST API rather than HA entity for control, should be more reliable/faster to control
  # Set one per inverter
  # If using Docker then change homeassistant.local to the Docker IP address
  givtcp_rest:
   - 'http://192.168.0.65:6345'
   - 'http://homeassistant.local:6346'

  
  # Inverter max AC limit (one per inverter). E.g for a 3.6kw inverter set to 3600
  # If you have a second inverter for PV only please add the two values together
  inverter_limit:
   - 3000

  # Export limit is a software limit set on your inverter that prevents exporting above a given level
  # When enabled Predbat will model this limit
  # export_limit:
  # - 2800

  # Some inverters don't turn off when the rate is set to 0, still charge or discharge at around 200w
  # The value can be set here in watts to model this (doesn't change operation)
  inverter_battery_rate_min:
    - 200

  # Workaround to limit the maximum reserve setting, some inverters won't allow 100% to be set
  # inverter_reserve_max : 99

  # Some batteries tail off their charge rate at high soc%
  # enter the charging curve here as a % of the max charge rate for each soc percentage.
  # the default is 1.0 (full power)
  # The example below is from GE 9.5kwh battery with latest firmware and gen1 inverter
  battery_charge_power_curve:
    91 : 0.91
    92 : 0.81
    93 : 0.71
    94 : 0.62
    95 : 0.52
    96 : 0.43
    97 : 0.33
    98 : 0.24
    99 : 0.24
    100 : 0.24

  # Inverter clock skew in minutes, e.g. 1 means it's 1 minute fast and -1 is 1 minute slow
  # Separate start and end options are applied to the start and end time windows, mostly as you want to start late (not early) and finish early (not late)
  # Separate discharge skew for discharge windows only
  inverter_clock_skew_start: 0
  inverter_clock_skew_end: 0
  inverter_clock_skew_discharge_start: 0
  inverter_clock_skew_discharge_end: 0

  # Clock skew adjusts the Appdaemon time
  # This is the time that Predbat takes actions like starting discharge/charging
  # Only use this for workarounds if your inverter time is correct but Predbat is somehow wrong (AppDaemon issue)
  # 1 means add 1 minute to AppDaemon time, -1 takes it away
  clock_skew: 0

  # Solcast
  solcast_host: 'https://api.solcast.com.au/'
  solcast_api_key: '75KgGYKZabTwEtpIcRDV8UMVuiFKSPd2'
  solcast_poll_hours: 8
  # Set these to match solcast sensor names
  # The regular expression (re:) makes the solcast bit optional
  # If these don't match find your own names in Home Assistant
  pv_forecast_today: re:(sensor.(solcast_|)(pv_forecast_|)forecast_today)
  pv_forecast_tomorrow: re:(sensor.(solcast_|)(pv_forecast_|)forecast_tomorrow)
  pv_forecast_d3: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_3|d3))
  pv_forecast_d4: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_4|d4))

  # car_charging_energy defines an incrementing sensor which measures the charge added to your car
  # is used for car_charging_hold feature to filter out car charging from the previous load data
  # Automatically set to detect Wallbox and Zappi, if it doesn't match manually enter your sensor name
  # Also adjust car_charging_energy_scale if it's not in kwH to fix the units
  # car_charging_energy: 're:(sensor.myenergi_zappi_[0-9a-z]+_charge_added_session|sensor.wallbox_portal_added_energy)'

  # Defines the number of cars modelled by the system, set to 0 for no car
  #num_cars: 1

  # car_charging_planned is set to a sensor which when positive indicates the car will charged in the upcoming low rate slots
  # This should not be needed if you use Intelligent Octopus slots which will take priority if enabled
  # The list of possible values is in car_charging_planned_response
  # Auto matches Zappi and Wallbox, or change it for your own
  # One entry per car
  # car_charging_planned:
  # 're:(sensor.wallbox_portal_status_description|sensor.myenergi_zappi_[0-9a-z]+_plug_status)'
  # car_charging_planned_response:
  #  -'yes'
  #  -'on'
  #- 'true'
  #  -'connected'
  #  -'ev connected'
  #  -'charging'
  #  -'paused'
  #  -'waiting for car demand'
  #  -'waiting for ev'
  #  -'scheduled'
  #  -'enabled'
  #  -'latched'
  #  -'locked'
  #  -'plugged in'

  # In some cases car planning is difficult (e.g. Ohme with Intelligent doesn't report slots)
  # The car charging now can be set to a sensor to indicate the car is charging and to plan
  # for it to charge during this 30 minute slot
  # car_charging_now:
  #  - off

  # Positive responses for car_charging_now
  # car_charging_now_response:
  # - 'yes'
  # - 'on'
  # - 'true'

  # To make planned car charging more accurate, either using car_charging_planned or the Octopus Energy plugin,
  # specify your battery size in kwh, charge limit % and current car battery soc % sensors/values.
  # If you have Intelligent Octopus the battery size and limit will be extracted from the Octopus Energy plugin directly.
  # Set the car SOC% if you have it to give an accurate forecast of the cars battery levels.
  # One entry per car if you have multiple cars.
  #car_charging_battery_size:
  #  - 75
  #car_charging_limit:
  #  - 're:number.tsunami_charge_limit'
  #car_charging_soc:
  #  - 're:sensor.tsunami_battery'

  # If you have Octopus intelligent, enable the intelligent slot information to add to pricing
  # Will automatically disable if not found, or comment out to disable fully
  # When enabled it overrides the 'car_charging_planned' feature and predict the car charging based on the intelligent plan (unless octopus intelligent charging is False)
  # This matches either the intelligent slot from the Octopus Plugin or from the Intelligent plugin
  
  octopus_intelligent_slot: 're:(binary_sensor.octopus_energy([0-9a-z_]+|)_intelligent_dispatching)'
  octopus_ready_time: 're:(time.octopus_energy([0-9a-z_]+|)_intelligent_ready_time)'
  octopus_charge_limit: 're:(number.octopus_energy([0-9a-z_]+|)_intelligent_charge_limit)'
  
  # IOG OHME set up
  # octopus_intelligent_slot: 'binary_sensor.ohme_slot_active'
  # octopus_ready_time: 'time.ohme_target_time'
  # octopus_charge_limit: 'number.ohme_target_percent'
  
  # Flux settings
  # calculate_best_charge - True            	# You want the tool to calculate charging
  # set_charge_window - True                		# You want to have Predbat control the charge window
  # calculate_best_discharge - True         # Enable discharge calculation
  # set_discharge_window - True             # Allow the tool to control the discharge slots
  # best_soc_keep - 0.0                     		# Setting this to 0 is best cost wise
  
  # Octopus saving session points to the saving session Sensor in the Octopus plugin, when enabled saving sessions will be at the assumed
  # rate configured with input_number.predbat_metric_octopus_saving_rate in-side HA
  octopus_saving_session: 're:(binary_sensor.octopus_energy([0-9a-z_]+|)_saving_session(s|))'
 
  # To improve on saving sessions to avaoid discharging the full amount
  rates_export_override:
  -   start: '18:30:00'
      end: '19:00:00'
      rate_increment: -10

  # Energy rates
  # Please set one of these three, if multiple are set then Octopus is used first, second rates_import/rates_export and latest basic metric

  # Set import and export entity to point to the Octopus Energy plugin import and export sensors
  # automatically matches your meter number assuming you have only one (no need to edit the below)
  # Will be ignored if you don't have the sensor but will error if you do have one and it's incorrect
  # NOTE: To get detailed energy rates you need to go in and manually enable the following events in HA
  #       event.octopus_energy_electricity_xxxxxxxx_previous_day_rates
  #       event.octopus_energy_electricity_xxxxxxxx_current_day_rates
  #       event.octopus_energy_electricity_xxxxxxxx_next_day_rates
  # and if you have export enable:
  #       event.octopus_energy_electricity_xxxxxxxx_export_previous_day_rates
  #       event.octopus_energy_electricity_xxxxxxxx_export_current_day_rates
  #       event.octopus_energy_electricity_xxxxxxxx_export_next_day_rates
  # Predbat will automatically find the event. entities from the link below to the sensors
  metric_octopus_import: 're:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_rate)'
  metric_octopus_export: 're:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_export_current_rate)'
  # metric_octopus_gas:  're:(sensor.octopus_energy_gas_current_rate)'
  # 0.1p_metric_octopus_export:  're: (no export)'

  # Standing charge in pounds, can be set to a sensor or manually entered (e.g. 0.50 is 50p)
  # The default below will pick up the standing charge from the Octopus Plugin
  # The standing charge only impacts the cost graphs and doesn't change the way Predbat plans
  # If you don't want to show the standing charge then just delete this line or set to zero
  metric_standing_charge: 're:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_standing_charge)'
  
  # Or set your actual rates across time for import and export
  # If start/end is missing it's assumed to be a fixed rate
  # Gaps are filled with zero rate
  #rates_import:
  #  -  start: "00:30:00"
  #     end: "04:30:00"
  #     rate: 7.5
  #  -  start: "04:30:00"
  #     end: "00:30:00"
  #     rate: 40.0
  #
  #rates_export:
  #  -  rate: 4.2

  # Can be used instead of the plugin to get import rates directly online
  # Overrides metric_octopus_import and rates_import
  # rates_import_octopus_url : "https://api.octopus.energy/v1/products/FLUX-IMPORT-23-02-14/electricity-tariffs/E-1R-FLUX-IMPORT-23-02-14-A/standard-unit-rates"
  # rates_import_octopus_url : "https://api.octopus.energy/v1/products/AGILE-FLEX-BB-23-02-08/electricity-tariffs/E-1R-AGILE-FLEX-BB-23-02-08-A/standard-unit-rates"

  # Overrides metric_octopus_export and rates_export
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/FLUX-EXPORT-BB-23-02-14/electricity-tariffs/E-1R-FLUX-EXPORT-BB-23-02-14-A/standard-unit-rates"
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/AGILE-OUTGOING-BB-23-02-28/electricity-tariffs/E-1R-AGILE-OUTGOING-BB-23-02-28-A/standard-unit-rates/"
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/OUTGOING-FIX-12M-BB-23-02-09/electricity-tariffs/E-1R-OUTGOING-FIX-12M-BB-23-02-09-A/standard-unit-rates/"

  # Import rates can be overridden with rate_import_override
  # Export rates can be overridden with rate_export_override
  # Use the same format as above, but a date can be included if it just applies for a set day (e.g. Octopus power ups)
  # This will override even the Octopus plugin rates if enabled
  #
  #rates_import_override:
  # -  date: '2023-09-10'
  #    start: '14:00:00'
  #    end: '14:30:00'
  #    rate: 5

  # For pv estimate, leave blank for central estimate, or add 10 for 10% curve (worst case) or 90 or 90% curve (best case)
  # If you use 10 then disable pv_metric10_weight below
  # pv_estimate: 10

  # Days previous is the number of days back to find historical load data
  # Recommended is 7 to capture day of the week but 1 can also be used
  # if you have more history you could use 7 and 14 (in a list) but the standard data in HA only lasts 10 days
  days_previous:
  - 7

  # Days previous weight can be used to control the weighting of the previous load points, the values are multiplied by their
  # weights and then divided through by the total weight. E.g. if you used 1 and 0.5 then the first value would have 2/3rd of the weight and the second 1/3rd
  # Include one value for each days_previous value, each weighting on a separate line.
  # If any days_previous's that are not given a weighting they will assume a default weighting of 1.
  days_previous_weight:
  - 1

  # Number of hours forward to forecast, best left as-is unless you have specific reason
  forecast_hours: 36

  # Specify the devices that notifies are sent to, the default is 'notify' which goes to all
  #notify_devices:
  #  - mobile_app_treforsiphone12_2

  # Battery scaling makes the battery smaller (e.g. 0.9) or bigger than its reported
  # If you have an 80% DoD battery that falsely reports it's kwh then set it to 0.8 to report the real figures
  battery_scaling: 1.0

  # Can be used to scale import and export data, used for workarounds
  # import_export_scaling: 1.0

  # Export triggers:
  # For each trigger give a name, the minutes of export needed and the energy required in that time
  # Multiple triggers can be set at once so in total you could use too much energy if all run
  # Creates an entity called 'binary_sensor.predbat_export_trigger_<name>' which will be turned On when the condition is valid
  # connect this to your automation to start whatever you want to trigger
  export_triggers:
    - name: 'large'
      minutes: 60
      energy: 1.0
    - name: 'small'
      minutes: 15
      energy: 0.25

  # If you have a sensor that gives the energy consumed by your solar diverter then add it here
  # this will make the predictions more accurate. It should be an incrementing sensor, it can reset at midnight or not
  # It's assumed to be in Kwh but scaling can be applied if need be
  #iboost_energy_today: 'sensor.xxxxx'
  #iboost_energy_scaling: 1.0

  # Nordpool market energy rates
  #futurerate_url: 'https://www.nordpoolgroup.com/api/marketdata/page/325?currency=GBP'
  #futurerate_adjust_import: False
  #futurerate_adjust_export: True
  #futurerate_peak_start: "16:00:00"
  #futurerate_peak_end: "19:00:00"
  #futurerate_peak_premium_import: 14
  #futurerate_peak_premium_export: 6.5
  
  # Carbon Intensity date from National Grid
  carbon_intensity: 're:(sensor.carbon_intensity_uk)'

**Comment by mpartington** [comment]
Just realised the log you shared is 2024-08-28, so you need to upload a more recent version. Have you changed from the app Daemon to add on version as the location changed
![Uploading Screenshot_2024-10-30-16-58-02-107_com.cxinventor.file.explorer.jpg…]()

**Comment by Dipstikk** [comment]
Hi Mike,
I haven't moved to the add on version so its as I built it up, I have just powered off my Pi and am waiting for it to restart to see if that clears things a bit, I thought I might restore a backup that was prior to the Octopus change.
Update, just got into the Pi, HA and Predbat and the log file is exactly the same so I am going to do a restore and see what happens, I have had grief with GivTCP 3.x.x. throwing predbat figures and graphs all over the place.

**Comment by mpartington** [comment]
It might be worth trying the add on. One less point of failure. Think there are some instructions in the documentation. You'd just need to copy the apps.yaml to the new location and stop App Daemon

**Comment by Dipstikk** [comment]
Oh well resetting back to a month ago hasn’t helped, I remember now when the add on came out I gave it a go but it failed, a few days later a new version was released as there was an issue with the original files and I have never got around to installing it, I’ll give it a go later on.
I’ll let you know how it goes.

**Comment by SwiftRR** [comment]
I think you need to go back to square one.

Follow the instructions in the instructions step-by-step:
https://springfall2008.github.io/batpred/install/#

I recommend going too the Predbat standalone add-on, leaving appdeamon well behind (as @mpartington has suggested):
https://springfall2008.github.io/batpred/install/#predbat-add-on-install

 Hope that helps

Rob

**Comment by mpartington** [comment]
>  I remember now when the add on came out I gave it a go but it failed

You might be grabbing the logs from the 'add on' location then, which would explain why they are so old. They are stored in a different folder location for appdaemon (I couldn't tell you everywhere, but I think it's down a level).  This would include the location of your apps.yaml file.

**Comment by Dipstikk** [comment]
That is exactly correct. Just to be clear i can just copy and paste my exiting apps.yaml file into the new directory, i’m questioning this as i have had a read of the newer apps.yaml and there is quite a bit more in it.

**Comment by Dipstikk** [comment]
Ok, update, I have installed the predbat add on and it’s working, I have found that I had a couple of cross overs in Solcast, which I have sorted and a couple of error messages regarding the comments on Octopus ready time and octopus charge limit, I have commented both out for the time being to get rid of the errors, however I still do not have export in the plan, I have noticed this comment in a box at the bottom of the apps.yaml file viewed through predbat, see attached screen grab.
![IMG_2888](https://github.com/user-attachments/assets/1fdb2732-de73-4116-9643-dee72bde3a3a)

Any suggestions on how it can be enabled? Or do I need to contact GE?

**Comment by mpartington** [comment]
What you have shared looks good. I'm not sure if some of the octopus sensors had a name change recently, which may be the cause of the errors. However the important ones seem to be picked up correctly.  

Scheduled discharge enable is just turned on by Predbat as needed, so off is ok. However on mine,.I don't have the subsequent 'on's . Is something wrong with apps.yaml here I wonder?

Feels like you are getting closer. Does the plan show enough battery left to export?

![Screenshot_2024-11-01-16-47-54-457_io homeassistant companion android](https://github.com/user-attachments/assets/50e50cbe-bddb-44a8-839c-3f6aaf610307)

**Comment by SwiftRR** [comment]
This is better and looks like you are getting there.

As with @mpartington, I also do not have the three 'on' lines. This is mine:
<img width="870" alt="image" src="https://github.com/user-attachments/assets/5c3beeed-8396-49b1-97aa-78edac6f41d3">

Please upload the complete apps.yaml file and we can then see exactly what you have.
Within file editor, download the file and then attach the file to your reply.

Rob

**Comment by gcoan** [comment]
> What you have shared looks good. I'm not sure if some of the octopus sensors had a name change recently, which may be the cause of the errors

There were a couple of the Octopus Intelligent Go sensors renamed in the latest Octopus integration (v13.0.0).  The new sensor names are in the documentation and the latest apps.yaml template

**Comment by Dipstikk** [comment]
Ok, another possibly rookie error, it has been suggested I download and send the apps.yaml file, when I select download on the file, well the 3 dots, I get the error message, 401 not authorised, what the heck, surely I am admin of my own Pi?
In the mean time I’ll check the file names in the Octopus app although I am seeing the cheap rate night time figures.
Again thanks for all you comments and help.

**Comment by mpartington** [comment]
I often get that as well and don't really understand why. I've installed the samba add on, which means I can browse the files on a laptop on the same network. Makes it easy to just copy them across to GitHub.

Upload a new log file and screenshot of your plan as well (,showing up to the next charge period). We may be able to spot something.

![Screenshot_2024-11-02-10-07-18-678_io homeassistant companion android](https://github.com/user-attachments/assets/29ff88e9-9541-4170-b64b-59d9a7f79998)

**Comment by SwiftRR** [comment]
On your 401 error, I don't know! I am still graduating from my HA rabbit level but there are others more knowledgable than me who may be able to help here.

This is what I see when I select the vertical 3 dots:
<img width="332" alt="image" src="https://github.com/user-attachments/assets/0513bde9-d994-4dd2-9f94-ef4b33e635bd">

If this fails, you can post the whole apps.yaml, as you did before in your first post.

Make sure that you add 3 back ticks above and below : ```
Otherwise you may get some lines in bold text.

Or you could try selecting all your apps.yaml code, copying into a text editor, saving that and uploading the file here.

Do check out the suggestion above from @gcoan.

Rob

**Comment by SwiftRR** [comment]
I have looked right back to the start and one question from @mpartington:

> Its strange its doing anything at all as there are no calculations in the logs, you don't have 2 instances running at the same time do you (the add on and AppDaemon)?

You have copied a screen from the webUI so you must have the standalone Predbat installed. 
But do you still have the Appdaemon version installed?
**I am wondering whether you are accessing the Appdaemon apps.yaml file in File Editor.**
The original Word doc that you uploaded references to standalone Predbat.

Check the documentation again:
https://springfall2008.github.io/batpred/install/#editing-configuration-files-in-home-assistant

When you open File Editor, you will see the screen below. Select <- Home Assistant:
<img width="331" alt="image" src="https://github.com/user-attachments/assets/0971f0dc-6c0c-4d23-9c32-2276f9495906">

Now Select addon_configs
<img width="336" alt="image" src="https://github.com/user-attachments/assets/c849b83c-775d-4b73-a370-d6ef4643b5e8">

If you are Standalone, you should see this:
<img width="337" alt="image" src="https://github.com/user-attachments/assets/7f5c5616-6cd3-467d-b555-ac7e369f9cd0">

And then:
<img width="331" alt="image" src="https://github.com/user-attachments/assets/cc6d59b5-14aa-4c89-826b-a845ac3049e5">
This is the apps.yaml file that Predbat standalone will be using.

If you are on appdaemon, you reach the Appdaemon-Predbat apps.yaml file via another route.
https://springfall2008.github.io/batpred/install/#predbat-add-on-install

Once you are on standalone Predbat, you can uninstall the Appdaemon version. When I did this, I noticed that the config files were still there (from File Editor). I then deleted the Appdaemon-Predbat files.

Before deleting things, I would take a backup!

Hope there is something here to help. Sorry if I have meme,ised things that you have already done but we need to get to the root of the problem.

Rob

**Comment by Dipstikk** [comment]
Hi Rob, yes I get add-on_configs then 6adb4f0d_predbat, which I am accessing the apps.yamel file from, but under the addon_configs I get a0d7b954_appdaemon, I take it I can delete this file set?

**Comment by SwiftRR** [comment]
Yes, you can delete this do please backup first. I would hate to have given you false advice that can't be undone!
First uninstall your old Appdaemon-Predbat add-on which will have been in here:
<img width="619" alt="image" src="https://github.com/user-attachments/assets/93768155-adcb-470c-858d-ff0b776a4891">

I have also uninstalled Appdaemon but you may be using this for other applications.

Then at least you will have a clean slate.

Then get a copy of your current apps-yaml file to us somehow!

Rob

**Comment by gcoan** [comment]
> Hi Rob, yes I get add-on_configs then 6adb4f0d_predbat, which I am accessing the apps.yamel file from, but under the addon_configs I get a0d7b954_appdaemon, I take it I can delete this file set?

As long as the appdaemon add-on is not started, there is no issue with leaving all the appdaemon files there.  I would suggest leaving them in place so (a) you can refer to them if you need to and (b) it gives an easy way to revert back from the predbat addon.  Once you are absolutely settled with the predbat addon running fine, delete the files and delete the appdaemon addon

On the 401 error you got, it may be a permissions thing with how you were trying to download it.  HA partitions addons so that you can't by default access other addon folders in /addon_configs

If you use either file editor, studio server or SSH then you should be OK as it sets the global permissions needed

**Comment by SwiftRR** [comment]
Follow advice from @gcoan.
He has been my mentor since I embarked on Predbat. 

Rob

**Comment by Dipstikk** [comment]
[Predbat log.txt](https://github.com/user-attachments/files/17607513/Predbat.log.txt)
[Apps yaml.txt.txt](https://github.com/user-attachments/files/17607514/Apps.yaml.txt.txt)

Here you go, if yo can find an error please let me know

**Comment by springfall2008** [comment]
You might want to edit the apps.yaml to remove your solcast API key

**Comment by Dipstikk** [comment]
Thanks Trefor.

**Comment by Dipstikk** [comment]
[Predbat log.txt](https://github.com/user-attachments/files/17607947/Predbat.log.txt)
[Apps yaml.txt.txt](https://github.com/user-attachments/files/17607948/Apps.yaml.txt.txt)

Here you are, if you can find an issue with them please let me know.
Thank you, Dave.

**Comment by Dipstikk** [comment]
Just to let you all know my export through Predbat has burst into life, thank you all.

**Comment by SwiftRR** [comment]
Well done.

Do you know what the issue was?

Rob

**Comment by Dipstikk** [comment]
Hi Rob,
The only thing I could put it down to was I hadn’t upgraded predbat to the new add on, since doing that viewing the apps yaml file showed me sections that were highlighted in red meaning they were either wrong or were not needed so I commented out the two lines Octopus_ready_time and Octopus_charge_limit and set a few things in the Config that were showing red to base settings then left it, a couple of hours later I received a txt saying Predbat status was set to idle and from that point forward the battery graph showed sets of discharge oh and a couple of lines have appeared in the apps.yaml as per the attached screen dump.
![IMG_2889](https://github.com/user-attachments/assets/9ad1a49c-1ecd-4517-8865-d6da1955635b)

#gotthereintheend

Now to watch Trefor’s video on tweeking for performance.
