### ISSUE TITLE
In v8.5.5, futurerate debug output is still generated

### ISSUE THREAD

**Issue by SwiftRR** [springfall2008/batpred#1584]
**Describe the bug**
The 'What's changed' section for v8.5.5 includes this line:

• Add p/kWh to cost today, remove debug output in futurerate by @springfall2008 in https://github.com/springfall2008/batpred/pull/1580

The p/kWh info is included in the WebUI rates chart (after restarting Predbat)

But the debug line showing Nordpool calibrating is still being generated every 5 min  in the Predbat add-on log: _(I am assuming that the calibration line is Debug output_).

<img width="872" alt="image" src="https://github.com/user-attachments/assets/81e73257-bfec-4ed6-8277-6e6ae3fc6494">

**Expected behaviour**
**No debug output.**

**Predbat version**
v8.5.5

**Environment details**
- Inverter and battery setup GE AC3.0 and two GE 8.2 kWh batteries
- Standard HAOS install: Raspberry pi 4 with HAOS 13.1 and HA core 2024.10.2

**Screenshots** and **Log file**
See screenshot above.

Rob

**Comment by springfall2008** [comment]
Fixed in v8.5.6
