### ISSUE TITLE
Not all sensors honor the apps.yaml setting for valuta

### ISSUE THREAD

**Issue by Doorshifter** [springfall2008/batpred#1588]
Not all valuta related sensors honor the apps.yaml setting:

I use the settings below
  # Currency, symbol for main currency second symbol for 1/100s e.g. $ c or £ p or e c
  currency_symbols:
    - '€'
    - 'c'
however when checking them in the dashboard I see that some are hardcoded.
<img width="505" alt="Screenshot 2024-11-03 at 14 14 23" src="https://github.com/user-attachments/assets/e284d0fb-b329-4765-b392-8b695bbd5d3b">
<img width="510" alt="Screenshot 2024-11-03 at 14 14 57" src="https://github.com/user-attachments/assets/5d11a2c4-e286-4bab-9038-2c29655a19fe">
I would expect that this would be in line with the apps.yaml setting.
Also some of the amounts are getting quite large, it might be better to show them in $, €, £, ... iso c, p, ...
**Predbat version**

8.5.6

**Environment details**

- SE Inverter and battery setup: [https://github.com/hif2k1/battery_sim](url)
- I use the Add-on

**Comment by gcoan** [comment]
The currency symbol in apps.yaml is currently only used on the html plan, the sensors don't use the values.

Its on my to-do list to address this as its inconsistent

**Comment by Doorshifter** [comment]
Looks good now, doesn't it 😄
