### ISSUE TITLE
Unexpected p/kWh spikes

### ISSUE THREAD

**Issue by Doorshifter** [springfall2008/batpred#1596]
Unexplainable spikes in rates graph. 
![Screenshot 2024-11-04 at 22 19 00](https://github.com/user-attachments/assets/a063d9c2-22ce-44f0-b5a1-1aa8066625aa)

**Predbat version**

8.5.9

**Environment details**

- SEbInverter and battery bat_sim
- Standard HAOS installer 
- Anything else? Nope

**Comment by springfall2008** [comment]
The reason is this broken is the calculation does quite make sense

What it was doing is (total cost) / (import energy - export energy)

But if you have close to 0 energy used (e.g. a battery) you get close to infinity.

I've changed it to use house Load now, this is on 'main' for testing

**Comment by Doorshifter** [comment]
I’ve got the latest HA and pred_bat installed. But unfortunately I got this today. 
![IMG_0124](https://github.com/user-attachments/assets/26de0ca0-602e-49c5-8b60-3a2ee3a17ed4)

**Comment by Doorshifter** [comment]
Also , the p/kWh feels like hard coded p’s iso my c’s in the apps.yaml see other solved issue
