### ISSUE TITLE
In "Charging Paused" status with set limit , error message "'int' object has no attribute 'split'" occurs in the log

### ISSUE THREAD

**Issue by maxgrosse1** [springfall2008/batpred#1602]
**Describe the bug**
In "Charging Paused/Hold charging" status with set limit , error message "'int' object has no attribute 'split'" occurs in the log

**Expected behaviour**
No error should occur.

**Predbat version**

v8.5.9

**Environment details**

- Inverter: Solax G4 X3
- Add-on to HomeAssistant

**Screenshots**
![grafik](https://github.com/user-attachments/assets/177520e5-b683-43b0-b52d-ba3ddf97b2bc)
![grafik](https://github.com/user-attachments/assets/799115e0-5ab2-4245-8da3-fe564d7e8b6d)

**Comment by springfall2008** [comment]
Can you share your configuration? I'm guessing you typed in a number into apps.yaml when it should be an Home Assistant entity name?

**Comment by maxgrosse1** [comment]
Sure, my config file is 
[apps.txt](https://github.com/user-attachments/files/17692812/apps.txt)

**Comment by springfall2008** [comment]
So I suspect the issue is you have:

>has_reserve_soc True

But reserve is set to 10, it should be set to a control that can be changed or commented out.

e.g. 'number.solax_feedin_discharge_min_soc'

**Comment by maxgrosse1** [comment]
Thank you very much Trefor. After setting 'reserve' to a control, the error message has gone.
