### ISSUE TITLE
sensors for today and tomorrow predicted items (kwh and cost)

### ISSUE THREAD

**Issue by eddysteurs** [springfall2008/batpred#1635]
**Is your feature request related to a problem? Please describe.**
with current sensors not possible to build a dashboard with today & tomorrow figures, only actual follow actual day hours

**Describe the solution you'd like**
would it be possible to have output sensors with the predicted kwh and cost items for today and tomorrow but on actual day (0 - 24h) (now it are moving hours depending on forecast span , for me 48 hrs)

**Describe alternatives you've considered**

**Additional context**

**Comment by springfall2008** [comment]
How is the chart you want different from this one?

![image](https://github.com/user-attachments/assets/022a9828-461b-41fe-a1d2-6e0272daad90)

**Comment by gcoan** [comment]
@eddysteurs 

Have a look at the attributes of predbat.best_metric which is Predbat's future cost predictions

The attribute 'results' gives the future cost predictions from now to the end of the predicted plan so if you wanted to get tomorrow's predicted cost you could create a template sensor that calculates results['today+2'00:00] - predbat.best_metric

the today+2 is to get the value of the predicted cost at midnight tomorrow night

Bit of fiddling with date manipulation but all the data is there for you to extract and use as you wish

**Comment by eddysteurs** [comment]
I will have a try at this tomorrow, thanks for the tip
Sent from my iPhone
Eddy Steurs


On 17 Nov 2024, at 22:37, Geoffrey Coan ***@***.***> wrote:

﻿

@eddysteurs<https://github.com/eddysteurs>

Have a look at the attributes of predbat.best_metric which is Predbat's future cost predictions

The attribute 'results' gives the future cost predictions from now to the end of the predicted plan so if you wanted to get tomorrow's predicted cost you could create a template sensor that calculates results['today+2'00:00] - predbat.best_metric

the today+2 is to get the value of the predicted cost at midnight tomorrow night

Bit of fiddling with date manipulation but all the data is there for you to extract and use as you wish

**Comment by eddysteurs** [comment]
Gcoin

thanks a lot , got it working, 1 example on import from grid for tomorrow
        predbat_import_fcst_tomorrow:
          friendly_name: "predbat import forecast tomorrow"
          unit_of_measurement: 'kWh'
          value_template: >
                {% set data = state_attr('predbat.import_energy', 'results') %}
                {% set target_time = (now() + timedelta(days=2)).date() ~ 'T00:00:00+0100' %}
                {% set target_today = (now() + timedelta(days=1)).date() ~ 'T00:00:00+0100' %}
                {% set value =( data[target_time] - data[target_today] ) | round(2) %}
                 {{value}}

once you have 1 the rest is peace of cake 👍

**Comment by gcoan** [comment]
Neat job @eddysteurs I'll add it to the documentation as an example for others

If you add a state_class of total then you'll collect long term statistics on this template so can  produce history graphs etc

**Comment by eddysteurs** [comment]
some change as it seems 00:00 is not always present, so search for next
        predbat_import_fcst_today:
          friendly_name: "predbat import forecast today"
          unit_of_measurement: 'kWh'
          value_template: >
                {% set data = state_attr('predbat.import_energy', 'results') %}
                {% set target_today = (now() + timedelta(days=1)).date() ~ 'T00:05:00+0100' %}
                  {% set keys = data.keys() | list | sort %}
                  {% set next_item = keys | select('>', target_today) | list | first %}
                  {% set value = data[next_item] if next_item else '9999' %}
                  {{value}}

        predbat_import_fcst_tomorrow:
          friendly_name: "predbat import forecast tomorrow"
          unit_of_measurement: 'kWh'
          value_template: >
                {% set data = state_attr('predbat.import_energy', 'results') %}
                {% set target_time = (now() + timedelta(days=2)).date() ~ 'T00:00:00+0100' %}
                  {% set keys = data.keys() | list | sort %}
                  {% set next_item = keys | select('>', target_time) | list | first %}
                  {% set valuetom = data[next_item] if next_item else '9999' %}
                {% set value =( valuetom|float(0) - states('sensor.predbat_import_fcst_today')|float(0) ) | round(2) %}
                {{value}}
