### ISSUE TITLE
Export rates not getting to 

### ISSUE THREAD

**Issue by howlintj1** [springfall2008/batpred#1645]
Just changed tariffs from octopus intelligent flux for export to fixed export 15p.

Export data in predbat plan still show octopus flux 23/30p rather than 15p.

octopus intergration is active an updating I tested.

**Predbat version**

8.7
**Environment details**

- giv energy inverter and batter 
- Standard HAOS installer 
- Anything else?

**Screenshots*
![IMG_0892](https://github.com/user-attachments/assets/1a77d891-65aa-4efd-99fc-901a115810b5)
![IMG_0891](https://github.com/user-attachments/assets/a7376da3-d17b-46fe-8b14-98437877dbc5)

**Comment by gcoan** [comment]
What is your export sensor from the octopus integration saying ?

sensor.octopus_energy_electricity_XXXX_export_current_rate

This is almost certainly not a Predbat bug, nor an Octopus Integration bug,  I'm willing to bet that your Octopus account has only changed the import rate and Octopus have forgotten to change the export rate.

Same thing happened to me when I moved from Flux to Agile.  And then about 6 months later Octopus spotted the error and rebilled me for the entire 6 months

**Comment by howlintj1** [comment]
You are correct!

It’s at the old rates. I’ll contact octopus to sort out.

**Comment by SwiftRR** [comment]
If you contact Octopus using DM on X, you may find that the tariff is changed really quickly.

Rob

**Comment by howlintj1** [comment]
Thanks Contacted them on x. I've just set up a manual export rate for now
and it looks to be working perfectly.

Thanks for everyones help. I'm not sure I'd of done it otherwise!

**Comment by gcoan** [comment]
> You are correct!
> 
> It’s at the old rates. I’ll contact octopus to sort out.

I thought it would be the case.  When you change import tariff they don't seem to remember the linked export rate

Until Octopus fix your account you can put a rates_export_override in apps.yaml with the correct export rate
