### ISSUE TITLE
Manual_api appears to have rate always defined as "0"

### ISSUE THREAD

**Issue by Ashpork** [springfall2008/batpred#1646]
**Describe the bug**
I'm on Tomato Intensity as a tarrif, which means when the CO2 levels nationally are less than 115, they apply a 15% discount to the tarrif in that time slot.

I've written a short template to evaluate and generate the manual_api command to adjust the rate for that timeslot by 15%. My output looks like the below

rates_import_override?date=2024-11-24&start=00:00:00&end=00:30:00&rate=20.924
rates_import_override?date=2024-11-24&start=01:00:00&end=01:30:00&rate=4.501
rates_import_override?date=2024-11-24&start=02:00:00&end=02:30:00&rate=4.501
rates_import_override?date=2024-11-24&start=03:00:00&end=03:30:00&rate=4.501
rates_import_override?date=2024-11-24&start=04:00:00&end=04:30:00&rate=4.501
rates_import_override?date=2024-11-24&start=05:00:00&end=05:30:00&rate=4.501
rates_import_override?date=2024-11-24&start=06:00:00&end=06:30:00&rate=20.924
rates_import_override?date=2024-11-24&start=07:00:00&end=07:30:00&rate=20.924
rates_import_override?date=2024-11-24&start=08:00:00&end=08:30:00&rate=20.924
rates_import_override?date=2024-11-24&start=09:00:00&end=09:30:00&rate=20.924
rates_import_override?date=2024-11-24&start=10:00:00&end=10:30:00&rate=12.631
rates_import_override?date=2024-11-24&start=11:00:00&end=11:30:00&rate=12.631

I'm firing each one of these at the select.predbat_manual_api entity in an attempt to override the price for those slots. However, I'm finding that each slot I'm adjusting, just changes the rate to '0' regardless of the value I provide.

**Expected behaviour**
I was hoping for the manual_api, to enable me to adjust the import rate for a given time slot, outside of '0'

**Predbat version**
v8.7.0

**Environment details**

**Screenshots**

![image](https://github.com/user-attachments/assets/8650a4c2-033d-4251-89a4-85bfc4a32df1)

**Log file**

app.yaml has the below defined:

  
  rates_import:
    - start: "22:30:00"
      end: "01:00:00"
      rate: 24.617
    - start: "01:00:00"
      end: "06:00:00"
      rate: 5.2952
    - start: "06:00:00"
      end: "09:30:00"
      rate: 24.617
    - start: "09:30:00"
      end: "11:30:00"
      rate: 14.86
    - start: "11:30:00"
      end: "20:30:00"
      rate: 24.617
    - start: "20:30:00"
      end: "22:30:00"
      rate: 14.86

**Comment by gcoan** [comment]
I've only ever used the manual API with rate=0 for Octopus power up and Free electricity events.  You're probably the first person to test a non-zero rate!

**Comment by springfall2008** [comment]
Odd it worked for me:

rates_export_override?start=17:00:00&end=18:00:00&rate=5

![image](https://github.com/user-attachments/assets/f6304835-3f84-4209-90a0-20ae71c34a49)

**Comment by springfall2008** [comment]
Right that would make sense now,debugging....

**Comment by springfall2008** [comment]
Fix on 'main' for testing

**Comment by springfall2008** [comment]
Without the logfile of the error its hard to know how I would catch it.
