### ISSUE TITLE
IOG - Use full 30min slot at off peak rate if car is charging and then is unplugged part way through a slot

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#1648]
**Describe the bug**
Not sure if this is a bug or feature request.  My understanding of IOG is if the car partially charges in a 30 min slot, then the whole of that 30 mins is billed off peak.

What I am finding is, soon as I unplug the car, Predbat reverts the slot reverts back to peak rate and therefore doesn't take advantage of this.  What seems to be happening is the octopus dispatch sensor switches off and Predbat reacts immediately to change the rate.

**Expected behaviour**
Assuming my understanding is correct... Predbat should lock in the remainder of the 30 min slot at the off peak rate and continue running off grid, charge batteries etc

v8.7.1

Example below shows 

**Screenshots**

![Screenshot_2024-11-23-13-39-34-268_io homeassistant companion android](https://github.com/user-attachments/assets/d84ac368-7ddb-4370-8c7b-cbd9c96d08e1)

![Screenshot_2024-11-23-13-53-18-641_io homeassistant companion android](https://github.com/user-attachments/assets/c6808140-4a7a-46e5-9f35-a382b114f775)

<img width="523" alt="image" src="https://github.com/user-attachments/assets/2260d65a-23c3-472d-aecc-657437eafa69">

**Log file**

[predbat.log](https://github.com/user-attachments/files/17880314/predbat.log)

**Comment by springfall2008** [comment]
Have you tried turning off 'octopus_intelligent_ignore_unplugged'?

**Comment by mpartington** [comment]
Double checked and that's never been switched on

**Comment by springfall2008** [comment]
Actually that switch doesn't control the peak/off peak rate anyhow. More the question is what the Octopus Integration does, if it removes the slots from the dispatch sensor then it will go away in Predbat too.

**Comment by mpartington** [comment]
It does appear to remove the slots from the dispatch sensor. I can't see one for that time.

I'm sure its been said you do get the whole slot, maybe others can confirm. I'll see if I can find an example, as I've one of these billed already.

If so, maybe more one for bottlecap dave?

**Comment by mpartington** [comment]
Here is an example from my first ever slot that seems to confirm I won't be getting an unwelcome bill : -)

<img width="573" alt="image" src="https://github.com/user-attachments/assets/5fba877b-0d05-4fdb-9705-645618e62c67">

<img width="562" alt="image" src="https://github.com/user-attachments/assets/e7bd1259-eff4-4641-9b7d-17d29796a905">

**Comment by springfall2008** [comment]
The real question is how Predbat would know, if Bottlecap Dave removes the slot from the sensor as Octopus removes it? Keeping the slots as sticky won't work as the plan can change at Octopus end too.
