### ISSUE TITLE
Sudden loss of data and control with GivEnergy hybrid gen 3

### ISSUE THREAD

**Issue by steve-daedilus** [springfall2008/batpred#1654]
**Describe the bug**
As of early hours of this morning, Predbat is no longer seeing data from, nor able to control, my GivEnergy system. Data values are missing, and errors throughout the stack in Home assistant. No configurations made, though the HA VM was migrated earlier that evening to new storage location. Additionally, the battery charging controls on the inverter were set to charge, and even manual override failed to do more than trickle charge from solar panels.

Attempted downgrade of minor HA core patch that had auto rolled out a few days ago. No change.

Multiple restarts of all aspects of the stack collectively did nothing.

Restarting inverter did not help. Did a full inverter and battery power down and startup. Then reset defaults for settings and then was able to manually force a charge on the inverter.

Still seeing no data for Predbat in HA.

**Expected behaviour**
Data populating HA and Predbat managing as has been previously.

**Predbat version**

8.7.2

**Environment details**

- GE Hybrid 5kW gen 3, 2x 5.2kw in series. Ethernet connected.
- Standard HAOS installer
- HA deployed in proxmox VM.
- HA all adds ins and services for control set to auto update.

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.

**Log file**
Logfile (Warnings) - All Warnings Errors
14334	2024-11-24 11:45:07.472754: Error: 'NoneType' object has no attribute 'get'
14333	2024-11-24 11:45:07.472376: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
14331	AttributeError: 'NoneType' object has no attribute 'get'
14322	2024-11-24 11:45:07.458440: Error: Traceback (most recent call last):
14321	2024-11-24 11:45:07.458329: Error: Exception raised 'NoneType' object has no attribute 'get'
14319	2024-11-24 11:45:07.458166: Warn: Inverter control auto restart trigger: REST read failure
14317	2024-11-24 11:45:07.442836: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
14310	2024-11-24 11:45:01.294081: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.77 kWh to make new average 26.23 kWh (percent 98%)
14309	2024-11-24 11:45:01.293486: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.1 kWh to make new average 26.28 kWh (percent 99%)
14276	2024-11-24 11:40:07.076632: Error: 'NoneType' object has no attribute 'get'
14275	2024-11-24 11:40:07.076446: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
14273	AttributeError: 'NoneType' object has no attribute 'get'
14264	2024-11-24 11:40:07.064335: Error: Traceback (most recent call last):
14263	2024-11-24 11:40:07.064011: Error: Exception raised 'NoneType' object has no attribute 'get'
14261	2024-11-24 11:40:07.063780: Warn: Inverter control auto restart trigger: REST read failure
14259	2024-11-24 11:40:07.050951: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
14252	2024-11-24 11:40:00.896744: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.74 kWh to make new average 26.19 kWh (percent 98%)
14251	2024-11-24 11:40:00.895575: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.15 kWh to make new average 26.33 kWh (percent 99%)
14218	2024-11-24 11:35:07.673440: Error: 'NoneType' object has no attribute 'get'
14217	2024-11-24 11:35:07.673125: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
14215	AttributeError: 'NoneType' object has no attribute 'get'
14206	2024-11-24 11:35:07.660391: Error: Traceback (most recent call last):
14205	2024-11-24 11:35:07.660161: Error: Exception raised 'NoneType' object has no attribute 'get'
14203	2024-11-24 11:35:07.659801: Warn: Inverter control auto restart trigger: REST read failure
14201	2024-11-24 11:35:07.647189: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
14194	2024-11-24 11:35:01.498765: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.75 kWh to make new average 26.2 kWh (percent 98%)
14193	2024-11-24 11:35:01.497625: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.2 kWh to make new average 26.39 kWh (percent 99%)
14160	2024-11-24 11:30:07.292070: Error: 'NoneType' object has no attribute 'get'
14159	2024-11-24 11:30:07.291715: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
14157	AttributeError: 'NoneType' object has no attribute 'get'
14148	2024-11-24 11:30:07.279264: Error: Traceback (most recent call last):
14147	2024-11-24 11:30:07.279002: Error: Exception raised 'NoneType' object has no attribute 'get'
14145	2024-11-24 11:30:07.278607: Warn: Inverter control auto restart trigger: REST read failure
14143	2024-11-24 11:30:07.265703: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
14136	2024-11-24 11:30:01.115958: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.73 kWh to make new average 26.19 kWh (percent 98%)
14135	2024-11-24 11:30:01.115335: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.19 kWh to make new average 26.37 kWh (percent 99%)
14102	2024-11-24 11:25:07.872743: Error: 'NoneType' object has no attribute 'get'
14101	2024-11-24 11:25:07.872693: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
14099	AttributeError: 'NoneType' object has no attribute 'get'
14090	2024-11-24 11:25:07.857658: Error: Traceback (most recent call last):
14089	2024-11-24 11:25:07.857393: Error: Exception raised 'NoneType' object has no attribute 'get'
14087	2024-11-24 11:25:07.857017: Warn: Inverter control auto restart trigger: REST read failure
14085	2024-11-24 11:25:07.844185: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
14078	2024-11-24 11:25:01.688845: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.81 kWh to make new average 26.27 kWh (percent 98%)
14077	2024-11-24 11:25:01.688094: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.2 kWh to make new average 26.38 kWh (percent 99%)
14044	2024-11-24 11:20:07.448684: Error: 'NoneType' object has no attribute 'get'
14043	2024-11-24 11:20:07.448414: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
14041	AttributeError: 'NoneType' object has no attribute 'get'
14032	2024-11-24 11:20:07.435068: Error: Traceback (most recent call last):
14031	2024-11-24 11:20:07.434613: Error: Exception raised 'NoneType' object has no attribute 'get'
14029	2024-11-24 11:20:07.434225: Warn: Inverter control auto restart trigger: REST read failure
14027	2024-11-24 11:20:07.421187: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
14020	2024-11-24 11:20:01.271767: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.83 kWh to make new average 26.28 kWh (percent 98%)
14019	2024-11-24 11:20:01.270613: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.33 kWh to make new average 26.51 kWh (percent 99%)
13986	2024-11-24 11:15:08.056403: Error: 'NoneType' object has no attribute 'get'
13985	2024-11-24 11:15:08.055840: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13983	AttributeError: 'NoneType' object has no attribute 'get'
13974	2024-11-24 11:15:08.042235: Error: Traceback (most recent call last):
13973	2024-11-24 11:15:08.041943: Error: Exception raised 'NoneType' object has no attribute 'get'
13971	2024-11-24 11:15:08.041436: Warn: Inverter control auto restart trigger: REST read failure
13969	2024-11-24 11:15:08.026492: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13962	2024-11-24 11:15:01.868763: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.67 kWh to make new average 26.13 kWh (percent 98%)
13961	2024-11-24 11:15:01.868199: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.38 kWh to make new average 26.56 kWh (percent 99%)
13929	2024-11-24 11:10:07.409946: Error: 'NoneType' object has no attribute 'get'
13928	2024-11-24 11:10:07.409533: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13926	AttributeError: 'NoneType' object has no attribute 'get'
13917	2024-11-24 11:10:07.394568: Error: Traceback (most recent call last):
13916	2024-11-24 11:10:07.394116: Error: Exception raised 'NoneType' object has no attribute 'get'
13914	2024-11-24 11:10:07.393675: Warn: Inverter control auto restart trigger: REST read failure
13912	2024-11-24 11:10:07.378755: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13905	2024-11-24 11:10:01.223942: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.47 kWh to make new average 25.92 kWh (percent 98%)
13904	2024-11-24 11:10:01.223355: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.43 kWh to make new average 26.61 kWh (percent 99%)
13871	2024-11-24 11:05:08.011990: Error: 'NoneType' object has no attribute 'get'
13870	2024-11-24 11:05:08.011671: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13868	AttributeError: 'NoneType' object has no attribute 'get'
13859	2024-11-24 11:05:07.997202: Error: Traceback (most recent call last):
13858	2024-11-24 11:05:07.996999: Error: Exception raised 'NoneType' object has no attribute 'get'
13856	2024-11-24 11:05:07.996633: Warn: Inverter control auto restart trigger: REST read failure
13854	2024-11-24 11:05:07.982932: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13847	2024-11-24 11:05:01.833055: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 25.13 kWh to make new average 25.58 kWh (percent 98%)
13846	2024-11-24 11:05:01.832069: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.5 kWh to make new average 26.69 kWh (percent 99%)
13813	2024-11-24 11:00:07.523902: Error: 'NoneType' object has no attribute 'get'
13812	2024-11-24 11:00:07.523587: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13810	AttributeError: 'NoneType' object has no attribute 'get'
13801	2024-11-24 11:00:07.510939: Error: Traceback (most recent call last):
13800	2024-11-24 11:00:07.510678: Error: Exception raised 'NoneType' object has no attribute 'get'
13798	2024-11-24 11:00:07.510318: Warn: Inverter control auto restart trigger: REST read failure
13796	2024-11-24 11:00:07.496896: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13789	2024-11-24 11:00:01.345456: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 24.79 kWh to make new average 25.23 kWh (percent 98%)
13788	2024-11-24 11:00:01.344509: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.55 kWh to make new average 26.73 kWh (percent 99%)
13755	2024-11-24 10:55:07.112321: Error: 'NoneType' object has no attribute 'get'
13754	2024-11-24 10:55:07.111784: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13752	AttributeError: 'NoneType' object has no attribute 'get'
13743	2024-11-24 10:55:07.098664: Error: Traceback (most recent call last):
13742	2024-11-24 10:55:07.098569: Error: Exception raised 'NoneType' object has no attribute 'get'
13740	2024-11-24 10:55:07.098528: Warn: Inverter control auto restart trigger: REST read failure
13738	2024-11-24 10:55:07.084691: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13731	2024-11-24 10:55:00.925172: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 24.54 kWh to make new average 24.98 kWh (percent 98%)
13730	2024-11-24 10:55:00.924038: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.66 kWh to make new average 26.84 kWh (percent 99%)
13697	2024-11-24 10:50:07.705457: Error: 'NoneType' object has no attribute 'get'
13696	2024-11-24 10:50:07.705140: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13694	AttributeError: 'NoneType' object has no attribute 'get'
13685	2024-11-24 10:50:07.692997: Error: Traceback (most recent call last):
13684	2024-11-24 10:50:07.692752: Error: Exception raised 'NoneType' object has no attribute 'get'
13682	2024-11-24 10:50:07.692347: Warn: Inverter control auto restart trigger: REST read failure
13680	2024-11-24 10:50:07.676236: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13673	2024-11-24 10:50:01.824407: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 24.2 kWh to make new average 24.63 kWh (percent 98%)
13672	2024-11-24 10:50:01.823298: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 26.81 kWh to make new average 26.99 kWh (percent 99%)
13639	2024-11-24 10:45:06.596725: Error: 'NoneType' object has no attribute 'get'
13638	2024-11-24 10:45:06.596374: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13636	AttributeError: 'NoneType' object has no attribute 'get'
13627	2024-11-24 10:45:06.584236: Error: Traceback (most recent call last):
13626	2024-11-24 10:45:06.583991: Error: Exception raised 'NoneType' object has no attribute 'get'
13624	2024-11-24 10:45:06.583661: Warn: Inverter control auto restart trigger: REST read failure
13622	2024-11-24 10:45:06.570437: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13615	2024-11-24 10:45:01.625188: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 24.03 kWh to make new average 24.45 kWh (percent 98%)
13614	2024-11-24 10:45:01.624038: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 27.0 kWh to make new average 27.19 kWh (percent 99%)
13581	2024-11-24 10:40:07.396721: Error: 'NoneType' object has no attribute 'get'
13580	2024-11-24 10:40:07.396336: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13578	AttributeError: 'NoneType' object has no attribute 'get'
13569	2024-11-24 10:40:07.384128: Error: Traceback (most recent call last):
13568	2024-11-24 10:40:07.383851: Error: Exception raised 'NoneType' object has no attribute 'get'
13566	2024-11-24 10:40:07.383475: Warn: Inverter control auto restart trigger: REST read failure
13564	2024-11-24 10:40:07.370240: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13557	2024-11-24 10:40:01.216555: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 23.77 kWh to make new average 24.2 kWh (percent 98%)
13556	2024-11-24 10:40:01.215962: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 27.19 kWh to make new average 27.38 kWh (percent 99%)
13523	2024-11-24 10:35:07.983654: Error: 'NoneType' object has no attribute 'get'
13522	2024-11-24 10:35:07.983347: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13520	AttributeError: 'NoneType' object has no attribute 'get'
13511	2024-11-24 10:35:07.970378: Error: Traceback (most recent call last):
13510	2024-11-24 10:35:07.970123: Error: Exception raised 'NoneType' object has no attribute 'get'
13508	2024-11-24 10:35:07.969814: Warn: Inverter control auto restart trigger: REST read failure
13506	2024-11-24 10:35:07.956482: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13499	2024-11-24 10:35:01.798817: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 23.49 kWh to make new average 23.9 kWh (percent 98%)
13498	2024-11-24 10:35:01.797697: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 27.37 kWh to make new average 27.56 kWh (percent 99%)
13465	2024-11-24 10:33:44.844920: Error: 'NoneType' object has no attribute 'get'
13464	2024-11-24 10:33:44.844608: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13462	AttributeError: 'NoneType' object has no attribute 'get'
13453	2024-11-24 10:33:44.831874: Error: Traceback (most recent call last):
13452	2024-11-24 10:33:44.831636: Error: Exception raised 'NoneType' object has no attribute 'get'
13450	2024-11-24 10:33:44.831269: Warn: Inverter control auto restart trigger: REST read failure
13448	2024-11-24 10:33:44.815745: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13441	2024-11-24 10:33:39.065834: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 23.15 kWh to make new average 23.56 kWh (percent 98%)
13440	2024-11-24 10:33:39.064696: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 27.65 kWh to make new average 27.84 kWh (percent 99%)
13403	2024-11-24 10:33:27.803329: Warn: Web Socket closed, will try to reconnect in 5 seconds
13401	aiohttp.client_exceptions.W SServerHandshakeError: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13400	raise WSServerHandshake Error(
13394	2024-11-24 10:33:27.803155: Error: Traceback (most recent call last):
13393	2024-11-24 10:33:27.802840: Error: Web Socket exception in startup: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13391	2024-11-24 10:33:22.789811: Warn: Web Socket closed, will try to reconnect in 5 seconds
13389	aiohttp.client_exceptions.W SServerHandshakeError: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13388	raise WSServerHandshake Error(
13382	2024-11-24 10:33:22.788970: Error: Traceback (most recent call last):
13381	2024-11-24 10:33:22.788551: Error: Web Socket exception in startup: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13379	2024-11-24 10:33:17.775350: Warn: Web Socket closed, will try to reconnect in 5 seconds
13377	aiohttp.client_exceptions.W SServerHandshakeError: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13376	raise WSServerHandshake Error(
13370	2024-11-24 10:33:17.775230: Error: Traceback (most recent call last):
13369	2024-11-24 10:33:17.775037: Error: Web Socket exception in startup: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13367	2024-11-24 10:33:12.763307: Warn: Web Socket closed, will try to reconnect in 5 seconds
13365	aiohttp.client_exceptions.W SServerHandshakeError: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13364	raise WSServerHandshake Error(
13358	2024-11-24 10:33:12.762822: Error: Traceback (most recent call last):
13357	2024-11-24 10:33:12.762304: Error: Web Socket exception in startup: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13355	2024-11-24 10:33:07.754114: Warn: Web Socket closed, will try to reconnect in 5 seconds
13353	aiohttp.client_exceptions.W SServerHandshakeError: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13352	raise WSServerHandshake Error(
13346	2024-11-24 10:33:07.753250: Error: Traceback (most recent call last):
13345	2024-11-24 10:33:07.752785: Error: Web Socket exception in startup: 502, message='Invalid response status', url=URL('http://supervisor/core/api/websocket')
13343	2024-11-24 10:33:02.741267: Warn: Web Socket closed, will try to reconnect in 5 seconds
13342	2024-11-24 10:30:07.597979: Error: 'NoneType' object has no attribute 'get'
13341	2024-11-24 10:30:07.597663: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13339	AttributeError: 'NoneType' object has no attribute 'get'
13330	2024-11-24 10:30:07.585528: Error: Traceback (most recent call last):
13329	2024-11-24 10:30:07.584978: Error: Exception raised 'NoneType' object has no attribute 'get'
13327	2024-11-24 10:30:07.584934: Warn: Inverter control auto restart trigger: REST read failure
13325	2024-11-24 10:30:07.572664: Warn: Inverter 0 unable to read REST data from http://homeassistant.local:6345/runAll - REST will be disabled
13318	2024-11-24 10:30:01.426732: Warn: Historical day 5 has 25 minutes of gap in the data, filled from 23.15 kWh to make new average 23.56 kWh (percent 98%)
13317	2024-11-24 10:30:01.425750: Warn: Historical day 2 has 10 minutes of gap in the data, filled from 27.65 kWh to make new average 27.84 kWh (percent 99%)
13284	2024-11-24 10:25:24.230128: Error: 'NoneType' object has no attribute 'get'
13283	2024-11-24 10:25:24.229799: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'get'
13281	AttributeError: 'NoneType' object has no attribute 'get'
13272	2024-11-24 10:25:24.217038: Error: Traceback (most recent call last):
13271	2024-11-24 10:25:24.216772

**Comment by springfall2008** [comment]
Can you check settings, system, logs, predbat and find the actual stack dump?

**Comment by gcoan** [comment]
Looking at the GivTCP log it looks like its a GivTCP or inverter issue, not Predbat

https://github.com/britkat1980/ha-addons/issues/33

**Comment by steve-daedilus** [comment]
Thanks both so far. I'll collate what I can if it helps.

**Comment by steve-daedilus** [comment]
Version information:

Core 2024.11.2
Supervisor 2024.11.4
Operating System 13.2
Frontend 20241106.2

Logs from Supervisor around when we started seeing issues:

2024-11-24 00:39:54.503 INFO (SyncWorker_2) [supervisor.docker.manager] Stopping addon_a6a2857d_givtcp application
2024-11-24 00:39:55.102 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_a6a2857d_givtcp application
2024-11-24 00:39:55.348 WARNING (MainThread) [supervisor.docker.addon] Can not set nested option PALM_BATT_UTILISATION as Docker env
2024-11-24 00:39:56.599 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on britkat/giv_tcp-ma with version 2.4.9
2024-11-24 00:39:57.509 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a6a2857d_givtcp
2024-11-24 00:39:59.492 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping addon_core_mosquitto application
2024-11-24 00:40:05.464 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_core_mosquitto application
2024-11-24 00:40:07.293 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.4.1
2024-11-24 00:40:10.008 ERROR (MainThread) [supervisor.services.modules.mqtt] There is already a MQTT service in use from core_mosquitto
2024-11-24 00:40:52.178 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping addon_6adb4f0d_predbat application
2024-11-24 00:40:52.315 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 257
2024-11-24 00:40:52.315 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for 6adb4f0d_predbat closed
2024-11-24 00:40:56.498 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_6adb4f0d_predbat application

These general reports of "PALM_BATT_UTILISATION as Docker env" and "There is already a MQTT service in use from core_mosquitto" then appear periodically.

I've done some reboot / restarts this afternoon in last half hour or so, and there's a lot of aiohttp.server errors, at which point another kick has happened.

Once back up, I've then conducted a ha configuration check (come back ok).  I'll go and retrieve detailed logs

**Comment by steve-daedilus** [comment]
As per suggestion elsewhere, I have restored to previous backup state, and after a short while of this (and re-configuring MQTT user settings), this has started working now (GivTCP info and Predbat info populating again).

I'm going to monitor this for the time being, however this has confirmed it is not a predbat issue.

Thanks for the help!
