### ISSUE TITLE
Multiple warnings: "Warn: Out of range index 1 within item"

### ISSUE THREAD

**Issue by discodancerstu** [springfall2008/batpred#1666]
Predbat displaying multiple warnings.

System is 2 x Hybrid Inverters, 2 x batteries and GivTCP 3.

Also running PredAI

Predbat log and apps.yaml as requested attached.
[predbat.log](https://github.com/user-attachments/files/17934114/predbat.log)
[appsyaml.txt](https://github.com/user-attachments/files/17934127/appsyaml.txt)

**Comment by springfall2008** [comment]
**battery_scaling** and **inverter_time** should be set in apps.yaml one per inverter.

You should also comment back in the other settings below this comment which is actually now incorrect as some are used for charge curve calculation:

```yaml
  # If not using REST then instead set the Control here (one for each inverter)
  # - you can delete this section if using REST
  ...
```

The warning reducing idle time and device_id can be ignore I think that's a bug on my side

**Comment by discodancerstu** [comment]
Thanks Trefor, I can't see how to set *battery_scaling* and *inverter_time*
for each inverter, please can you advise?

Also to confirm I should have this section as per below?

[image: image.png]

**Comment by discodancerstu** [comment]
![Screenshot_20241130_204126_Home Assistant](https://github.com/user-attachments/assets/2dc5b848-3f7e-49d9-82e4-40969bec0072)

**Comment by discodancerstu** [comment]
Since doing this, the following warnings and errors are now showing. 
![Screenshot_20241130_204227_Home Assistant](https://github.com/user-attachments/assets/c394252d-cd14-4160-86e6-0fca971a8f1a)

**Comment by gcoan** [comment]
You've got badly formatted YAML

If you look at your apps.yaml, each entry should be indented by two spaces

soc_max and reserve are both indented correctly and then everything after that is missing a space

see https://springfall2008.github.io/batpred/apps-yaml/#warning-appsyaml-file-format
