### ISSUE TITLE
Potential optimisations around planned export to minimise writes

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#1681]
Firstly thank you for all the work you have done already in this area following the STTG video.  I've noticed that the major contributor to writes is now the forced export at the end of my plan .prior to charging up on the cheap rate.  It feels like this is an opportunity for further improvement and I wanted to share my thoughts based on observations.

Last night it required 23 write requests to discharge what remained in my battery, which seemed excessive. Ironically this did include my automation halting a spurious calibration at 23:10 (said to be triggered by too many writes 🥴)

<img width="740" alt="image" src="https://github.com/user-attachments/assets/03675516-8ddf-47be-ae5b-38238315107f">

I noticed the following contributors:
- Despite having calculate secondary order off, the discharge slots were not planned concurrently (Obviously this means Predbat needs to switch between modes)
- The finish time was pushed back every 30 mins, rather than just specifying the end slot of the total discharge period
- The reserve was frequently changed, rather than setting the final value
- GivTCP seems to be recording multiple writes for the same command, is Predbat making too many requests?

My thoughts for improvements 

- Ensure discharge slots do not split, are as late as possible and are always concurrent when calculate secondary order is off (possible bug as I thought this was the intention)
- Auto combine 30 min slots.(As you have done with charge), at the moment the end time is changed every 30 mins - just use final time.
- Could a discharge period covering the whole day (e.g. 00.00.01 to 00.00.00) be set and then only the 'enable discharge schedule' toggle be turned on / off as needed
- Maybe feature to finish within a +/- X minute time window would allow it to schedule with more flexibility, without needing to frequently stop/start to hit an exact finish time (similar to the change on low power mode to finish early). 
   - You wouldn't want this on Agile, but on IOG, I don't care so much if discharge continues into the cheap slot (so long as no car charge is scheduled). I can schedule high drain appliances accordingly avoiding the first 30 mins.
    - Now I realise this could also be due to having an incorrect discharge rate modelled, but my calibration chart looks ok
 - Set the reserve as the final target value, rather than changing potentially every run 
 - We've had a previous conversation, where it was confirmed it is necessary to enable reserve to support some of the Pause/Hold functions, has this/could this be decoupled? The new Pause function doesn't need it

Not saying any of this is necessarily possible, but wanted to spark discussion

Logs from the period 
[write_log_inv_1.log](https://github.com/user-attachments/files/17975259/write_log_inv_1.log)

[predbat1.log](https://github.com/user-attachments/files/17975260/predbat1.log)

**Comment by mpartington** [comment]
Slot scheduling with Secondary order off (it did enact this)
![image](https://github.com/user-attachments/assets/98ed5fe1-a45d-42bf-aa2b-e144229f4dd3)

**Comment by mpartington** [comment]
Example of the slot times being changed and the reserve values
<img width="405" alt="image" src="https://github.com/user-attachments/assets/0b56a96c-0987-4822-9e16-b7d463c344b1">

**Comment by springfall2008** [comment]
Interesting I made a fix on 'main' for just these cases this morning, can you give it a try?

**Comment by mpartington** [comment]
> Interesting I made a fix on 'main' for just these cases this morning, can you give it a try?

Will do.  I've noticed it still wants to split my discharge slots with secondary order either on or off (makes no difference).

However if I change SOC Keep from 0.5 to 0.4, it combines them. Any idea what's going on there?

<img width="284" alt="image" src="https://github.com/user-attachments/assets/b429e8d8-9d79-4670-b333-b4b497671ab1">

<img width="286" alt="image" src="https://github.com/user-attachments/assets/8b902e77-6451-40d9-a001-8e2fc5e71d51">

**Comment by mpartington** [comment]
Feedback on main (version 03-Dec)

Firstly despite fiddling with SOC keep, I ended up with split discharge times rather than on continuous block.  I ended up adding a manual forced export from 23:30 until 01.00 (to give soc time to settle at empty)

I don't really understand why the GivTCP logs are different (do they ignore REST?), but I saw some unnecessary discharge slot setting, especially around 4am, whilst the battery should have been charging

<img width="718" alt="image" src="https://github.com/user-attachments/assets/e3d4cec2-f6a4-4b3f-bdc0-ddd44d23dc60">


<img width="416" alt="image" src="https://github.com/user-attachments/assets/3a81dc20-14ee-4f4c-843a-0967a2c157b7">

<img width="210" alt="image" src="https://github.com/user-attachments/assets/104f6f97-c36d-4242-a1ee-42c693fb9266">
<img width="189" alt="image" src="https://github.com/user-attachments/assets/5904d5a9-c657-4f12-8169-6b0f7f7aa08a">

**Comment by springfall2008** [comment]
Discharge fix on 'main' for testing

**Comment by mpartington** [comment]
> Discharge fix on 'main' for testing

Thanks, just loaded. What's the best setting to push the discharge slots together and as late as possible?

This is calculate secondary order slots off
<img width="283" alt="image" src="https://github.com/user-attachments/assets/95998ae2-37c2-4aa6-9f6f-c73ee135c6d3">

and on

<img width="302" alt="image" src="https://github.com/user-attachments/assets/9eb3095e-daa0-4cc3-aa2d-e011fb70520c">

**Comment by mpartington** [comment]
Hi @springfall2008 , I've uploaded the logs for last night as it's probably easier for you to see the writes.

It seems better, but 2 observations

1. As on the chart, the discharge is frequently started and stopped. Not sure what I can be here, I've set my discharge battery curve to 1.05 to try and get Predbat to understand predict the discharge, but that didn't seem to work.
2. Unsure why it is changing pause modes here, seems unnecessary
![Screenshot_2024-12-05-09-49-48-344_io homeassistant companion android~2](https://github.com/user-attachments/assets/59c8973c-e493-422e-acaf-5af46863f69e)

[predbat (1).log](https://github.com/user-attachments/files/18021140/predbat.1.log)
[predbat.1 (1).log](https://github.com/user-attachments/files/18021155/predbat.1.1.log)

**Comment by springfall2008** [comment]
I'm not sure that will do anything, 4: 1.05 means that you will discharge 5% faster than normal when your battery reaches 4%?

Can you change metric_battery_scaling_discharge to adjust the predicted discharge speed up/down

**Comment by mpartington** [comment]
Ah, I did wonder if it was just at 4%.

I don't think that metric exists does it?
![Screenshot_2024-12-05-19-47-05-433_io homeassistant companion android](https://github.com/user-attachments/assets/c1e3b5ed-bee8-4aae-98cb-c93268a05e27)

**Comment by springfall2008** [comment]
![image](https://github.com/user-attachments/assets/082edc0b-a5d4-42fd-9a2d-2e7dbf375f3d)

**Comment by mpartington** [comment]
I think the final bug has just been fixed in 8.8.3 (Split / too early discharge slots), so good to close
