### ISSUE TITLE
0% Error

### ISSUE THREAD

**Issue by thewhale21** [springfall2008/batpred#17]
When batteries are over voltage and go from 100% to 0% SoC due to a bug in GE's reporting. BatPred misscalculates SoC targets as it thinks there is less battery capacity. 

Saw this today on a 2 * 5.2 setup, where first one battery "faulted" and only 4.2kws was used for calcs, then when my second one over voltaged it went up to 5.1 for some reason. 

I Know GE were meant to fix this at some point in the future. But not sure what update its in.

**Comment by springfall2008** [comment]
I'm not sure exactly what the issue is or how to workaround it, maybe if you provide more details? Are you using REST mode as there is a battery capacity workaround in there that might work.

**Comment by thewhale21** [comment]
Im not entirely sure which metric it was that was miss reporting. But when one of my 2 batteries went offline due to it being overcharged. the below was showing Actual as 5.1Kwh.
![image](https://github.com/springfall2008/batpred/assets/25723228/370b5835-cb20-446e-9027-bc7abc22f551)

Now that i've discharged the battery down to normal voltage limits the Actual is showing correctly again.

I assume when the battery goes into this state BatPred is unable to pull something from GivTCP so it just uses the value for the single battery. 

As i said its a bug with GE's reporting on SoC when battery is to full, :) Probably not worth the time to look into as they are meant to be fixing soon.

**Comment by treforsouthwell-sifive** [comment]
The data comes from GivTCP, it's not something Predbat calculates itself. 

I take you are using battery scaling to 0.8?

**Comment by thewhale21** [comment]
Yup, Ah okay. Thought that might be the case :)

in theorey it should never be a problem as batteries should discharge them selves down to a safe level anyway and batpred was just recalculate. Just makes an ugly squiggle in my chart!

But thanks for checking :)

**Comment by springfall2008** [comment]
The data comes from GivTCP, it's not something Predbat calculates itself. 

I take you are using battery scaling to 0.8?
