### ISSUE TITLE
Custom inverter start/end times set after service call

### ISSUE THREAD

**Issue by chris-y** [springfall2008/batpred#1700]
I'm not sure if this is the same issue or different to #1690

My plan looks like this, so it is supposed to be charging: 

![Screenshot_20241206-235103-319.png](https://github.com/user-attachments/assets/64f32c0a-25dd-47d7-b2d8-2590929d69a5)

However it has set the start and ends times to midnight (ie. don't charge):

![Screenshot_20241206-235641-422.png](https://github.com/user-attachments/assets/bfa14895-f974-4751-b901-aefef7b3f813)

You can see the start and ends times are 00:00 for a bit around the time when this service was called: 

![Screenshot_20241206-235020-563.png](https://github.com/user-attachments/assets/cda568b4-d0aa-493a-9fda-f35c300ce2f0)

The relevant part of the log is here. It looks like it maybe called the service before setting the times?

![Screenshot_20241207-001816-706.png](https://github.com/user-attachments/assets/300280b2-d696-407c-9873-661bdf8b51c0)

This zoomed in section of the end time seems to confirm this is the case: 
![Screenshot_20241207-002603-061.png](https://github.com/user-attachments/assets/1663a61e-d556-47c4-a074-d930d4045504)

The time that was set was after the service was called.

**Comment by springfall2008** [comment]
How is your service getting the start and end times as they are not passed in the service call?

**Comment by chris-y** [comment]
It's picking them up from sensor.predbat_mine_0_charge_start_time and sensor.predbat_mine_0_charge_end_time, which Predbat sets

**Comment by springfall2008** [comment]
I put a fix for this on 'main' for testing

**Comment by chris-y** [comment]
That has fixed this issue, thanks!
I've put a note on the other issue #1690 about the current setting having a similar problem.
