### ISSUE TITLE
Charge slots incorrect since upgrade to 7.8.2

### ISSUE THREAD

**Issue by AGLAISTER** [springfall2008/batpred#173]
SInce upgrade to 7.8.2 charging at higher price times and not occurring at times where the battery is lower and the price is much lower than the actual set charge times.
It is also not charging the battery anywhere near as high as pre 7.8.1 leaving me at risk of running out of battery during peak rate times.
[appdaemon.log.1.txt](https://github.com/springfall2008/batpred/files/12886967/appdaemon.log.1.txt)
[appdaemon.log.2.txt](https://github.com/springfall2008/batpred/files/12886969/appdaemon.log.2.txt)
[appdaemon.log.3.txt](https://github.com/springfall2008/batpred/files/12886970/appdaemon.log.3.txt)
![Predbat Image 1](https://github.com/springfall2008/batpred/assets/141528175/5a2f1ebf-5690-4a8f-8d19-8f8d20143fd9)
![Predbat Image 2](https://github.com/springfall2008/batpred/assets/141528175/963efa58-53c5-4257-831d-1f36d008d642)
![Predbat Image 3](https://github.com/springfall2008/batpred/assets/141528175/805f8a20-3a9d-4390-86b5-aec5a5a6bd57)

**Comment by springfall2008** [comment]
It maybe worth putting metric_max_windows back to 96 and see if you get similar results to before 

Also check calculate_discharge_incharge and make sure it’s on

**Comment by AGLAISTER** [comment]
where is metric_max_windows???? I can't find it either trying to add it to a card or in the apps.yaml

also despite restarting home assistant and appdaemon I cannot turn calculate_discharg_incharge on, I click it on but the switch turns off on its own.

**Comment by springfall2008** [comment]
Sorry I had the name wrong: input_number.predbat_calculate_max_windows

Sometimes when you change a toggle you have to wait a few minutes, it might toggle back in the meantime before updating again.

**Comment by springfall2008** [comment]
Did this help?

**Comment by AGLAISTER** [comment]
Hi since I've dropped the windows back to 32 things seem to be working ok
again

**Comment by springfall2008** [comment]
Closing this for now, I think things have moved on.
