### ISSUE TITLE
Predbat will not discharge to min soc

### ISSUE THREAD

**Issue by Eeebygum23** [springfall2008/batpred#1766]
[predbat_debug_08_00_00.txt](https://github.com/user-attachments/files/18217912/predbat_debug_08_00_00.txt)
**Describe the bug**
Predbat used to discharge the battery every night to 4% (0.5kwh). Now it seems to be happy to discharge to about 26%.

**Expected behaviour**
I am hoping that PB will discharge the battery down to minimum keep.

**Predbat version**

8.8.10

**Environment details**

Givenergy 135kw AIO
- installed directly onto Home assistant Yellow
- 

**Predbat debug yaml file**
Enable debug mode and let Predbat run for one cycle. Look in the 'debug' directory under the Predbat add-on and take the .yaml file for the time period in question.
Rename the predbat_debug_XX_XX_XX.yaml to predbat_debug_XX_XX_XX.yaml.txt and upload it to Github. This will allow your plan to be reproduced and also stores all your settings for review.
[PREDBAT CHANGE LOG.txt](https://github.com/user-attachments/files/18217741/PREDBAT.CHANGE.LOG.txt)

**Comment by springfall2008** [comment]
setting 'calculate_export_low_import' to True seems to fix this, I think I should put the default back

**Comment by springfall2008** [comment]
Fix on main to change this default

**Comment by gcoan** [comment]
> Fix on main to change this default

Could the documentation be updated to match this change please @springfall2008 ?

Thanks

**Comment by mpartington** [comment]
Bit confused on this, was the switch working the opposite way around or does enabling stop it being sorted by time order?

**Comment by Eeebygum23** [comment]
I have no idea how to update these files. Are there replacement .py files anywhere that i can copy and paste?

**Comment by springfall2008** [comment]
> > Fix on main to change this default
> 
> Could the documentation be updated to match this change please @springfall2008 ?
> 
> Thanks

Pretty sure I have done, docs only get published on release however (which I just did)

**Comment by springfall2008** [comment]
Oh wait I didn't.... will update the docs

**Comment by gcoan** [comment]
> > > Fix on main to change this default
> 
> > Could the documentation be updated to match this change please @springfall2008 ?
> 
> > Thanks
> 
> 
> 
> Pretty sure I have done, docs only get published on release however (which I just did)

I looked at the commits referenced in the above change and didn't see any changes to the documentation files.  But if done, great

**Comment by springfall2008** [comment]
Docs update now done
