### ISSUE TITLE
Error: Exception raised Inverter.press_and_poll_button() missing 1 required positional argument: 'entity_id'

### ISSUE THREAD

**Issue by philicibine** [springfall2008/batpred#1778]
Seeing the above error. Battery is not charging / discharging as scheduled.

**Predbat version**
8.8.12 have also tried rolling back to previous version

**Environment details**
Solis hybrid inverter using Solax Modbus integration.

**Log file**
[predbat.log](https://github.com/user-attachments/files/18221640/predbat.log)
**Predbat debug yaml file**
[predbat_debug.yaml.txt](https://github.com/user-attachments/files/18221729/predbat_debug.yaml.txt)

**Comment by springfall2008** [comment]
Fixed in release v8.8.13

**Comment by philicibine** [comment]
Thanks.  Can confirm it is working now!
