### ISSUE TITLE
8.8.15 causing errors on load

### ISSUE THREAD

**Issue by andyrew66** [springfall2008/batpred#1794]
**Describe the bug**
The following error appears upon updating 
Status
Status	Error: Exception raised str.format() got multiple values for keyword argument 'charge_start_time

Reverting to 8.8.13 resolves the issue

**Predbat version**

8.8.15

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.

**Predbat debug yaml file**
Enable debug mode and let Predbat run for one cycle. Look in the 'debug' directory under the Predbat add-on and take the .yaml file for the time period in question.
Rename the predbat_debug_XX_XX_XX.yaml to predbat_debug_XX_XX_XX.yaml.txt and upload it to Github. This will allow your plan to be reproduced and also stores all your settings for review.
![predbat_debug-1.yaml.txt](https://github.com/user-attachments/files/18259012/predbat_debug-1.yaml.txt)

![predbat.log.txt](https://github.com/user-attachments/files/18259025/predbat.log.txt)

**Comment by gcoan** [comment]
what inverter type and can you share a debug file or apps.yaml please.

I'm on 8.8.15 and not seen this error so it must be inverter-specific

**Comment by andyrew66** [comment]
My log files are at the end of my comment

It's a lux inverter, as mentioned, it doesn't have an issue on previous versions.

**Comment by springfall2008** [comment]
Fix on 'main', will be released soon

**Comment by springfall2008** [comment]
Fix released
