### ISSUE TITLE
Suggestion: Recode 'set reserve enable' to toggle eco mode on/off to accommodate new inverter firmware

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#180]
Unfortunately the new faster firmware that is being/will be rolled out means that the previous method of setting the battery reserve to the soc target no longer results in zero charge / discharge. In fact rather odd things are happening.

The new firmware still has a small charge even when paused, which appears to be driving fluctuations. The only way I have identified to truly pause the battery is by turning off eco mode. Therefore if possible, could this method be used instead? It should be compatible with all inverter types.

Example of the issue (set reserve enable is on). Soc target is 70%

![Screenshot_2023-10-10-06-04-01-287_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/84180ea4-aa49-425c-ad89-f95546e23a61)

![Screenshot_2023-10-10-06-05-00-914_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/20063bc1-0581-442b-93d7-05b563f50cf1)

Understand if not possible and this should really be fixed in firmware, which I will continue to push for

**Comment by mpartington** [comment]
This is an example from this morning, where set reserve enable was switched off. The fluctuations were still present, but less frequent
![Screenshot_2023-10-14-06-47-24-033_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/0a73b612-2a74-4861-92db-b9b59740693c)
![Screenshot_2023-10-14-06-54-27-733_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/33e505a1-0ad9-4fb6-ae67-7ea737e6febe)

**Comment by springfall2008** [comment]
Are you suggesting to use Eco (Paused) mode?

<img width="473" alt="image" src="https://github.com/springfall2008/batpred/assets/48591903/5cda66bc-d840-46d4-bb78-099367762427">

**Comment by mpartington** [comment]
I normally select from the portal,.which completely turns off charge /discharge and sets the mode to Eco (Paused). Bizarrely, doing it the other way around (selecting in GivTCP, doesn't seem to have the same effect. There is still a 200W charge.

I'll check Willy's balancing scripts, as sure he uses this method
![Screenshot_2023-10-14-15-26-05-199_com android chrome~2](https://github.com/springfall2008/batpred/assets/106986397/cb705690-bf2a-4c1a-8165-6412632a9163)

**Comment by gcoan** [comment]
Before I started using predbat, if I wanted to hold the battery level in my own HA scripts I just set discharge or charge rate to zero.  I never used target soc.
Would this work?

**Comment by mpartington** [comment]
If you're on the 1st gen original.firmware, that works perfectly. On the new faster firmware, it doesn't fully shut off (for reasons still unexplained by Giv).  We then got around this by setting the reserve to the soc target.

However the firmware has evolved again breaking that work around, and now they have added a battery pause register, which ironically still doesn't fully pause the battery.

I'm on the AC3 beta firmware,.which is.meant to be the final version. I keep asking for a true pause to be coded in firmware, but not happened yet :-(. Turning off eco is.about the only way to do 8t, but it looks like the portal does it differently to GivTCP

**Comment by mpartington** [comment]
Got it, it's 
switch.givtcp_xxxx_battery_power_mode
Turn it off and battery power drops to zero

**Comment by gcoan** [comment]
Thanks for the explanation. Crazy that setting the battery still charges and discharges when the rate is set to zero.  Definitely sounds like a GivEnergy bug/feature.

Yes I’m on 1st gen original firmware so it works for me.

**Comment by springfall2008** [comment]
Matt that's odd, as reading the code setting battery power mode to 0 is forced export mode - maybe it's 0 outside the window and force export inside?

**Comment by mpartington** [comment]
Not sure, but this is what it currently does. I've added the toggle to my dashboard, so you can see the mode changes 

![Screenshot_2023-10-14-16-27-52-643_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/791ef30d-48d7-47f7-af02-f901b08fed7e)
![Screenshot_2023-10-14-16-25-16-862_io homeassistant companion android~2](https://github.com/springfall2008/batpred/assets/106986397/c4c4e0c5-8485-4cb4-9570-03cfb5d4ac67)
![Screenshot_2023-10-14-16-25-33-563_io homeassistant companion android~2](https://github.com/springfall2008/batpred/assets/106986397/924aa7c0-0351-49df-9e0a-ae14850c24bf)

**Comment by reidjr** [comment]
> Matt that's odd, as reading the code setting battery power mode to 0 is forced export mode - maybe it's 0 outside the window and force export inside?

Its not quite that:
You need to look at the pair.
Battery mode 0/1 ECO off or On outside the window
Enable discharge 0/1 Discharge fully in window.



So you have 4 options:
Battery Power Mode, Enable Discharge
1,0 ECO
1,1 Timed Discharge
0,1 Timed Export
0,0 Idle ( no specific mode in the Apps )

Trouble is Gen1 and gen2, or at least firmware to firmware behaviour to those settings differ.

**Comment by mpartington** [comment]
Richards given some good insight into the logic (with an assumption GivTCP switches 2 registers- as suggested above).

It might be easier for me to knock up a.local.automation, but I'm not sure if predbat would see the mode changes and change them back.  I'll give it a go tonight

![Screenshot_2023-10-15-10-35-26-167_com facebook katana](https://github.com/springfall2008/batpred/assets/106986397/a43b9676-ab2a-4b13-9545-81976a965c20)

![Screenshot_2023-10-15-10-23-26-935_com facebook katana](https://github.com/springfall2008/batpred/assets/106986397/09457f52-2f35-4bbe-8ac6-8530b88317f0)

**Comment by mpartington** [comment]
This will differ system to system, but this is the residual charge amounts for the different methods (AC3 new firmware)

Pause charge: 28W
Active power set to zero : 86W
Battery charge rate set to zero: 316W
Pause during charging (firmware logic) : approx 90W
Eco mode off: zero

**Comment by mpartington** [comment]
Possibly a semi success. I ran a simple automation the turned off battery mode when soc= soc target and back on whenever soc target changed in the charge period. That bit worked perfectly, however the battery still had a residual charge, unlike my earlier experiment.

I need to understand this, so will disable predbat tonight and set a soc target manually, to rule.in or out predbat changing something back, or if it just works differently in a charge window. The charts do have a few very small areas of zero charge. Will also see if anything in the logs.

![Screenshot_2023-10-16-06-28-28-016_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/430eeba2-ed0c-47a5-b02d-e312b47c2a9b)

![Screenshot_2023-10-16-06-29-45-259_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/450e6caf-487a-4986-b745-4eb9dd9576a7)
