### ISSUE TITLE
Sub-optimal import/export plan since 8.8.17

### ISSUE THREAD

**Issue by sammort** [springfall2008/batpred#1821]
### Describe the bug
Since v8.8.17 of Predbat I'm getting a sub-optimal charge/discharge plan for my AIO. As I'm on IOG it is usual for predbat to plan a charge > discharge > charge during the off-peak period overnight. However, v8.8.17 and above show the same sort of pattern but with an extremely low limit (charging/discharging from 4% limit > 5% limit > 4% limit).

Versions before v8.8.17 behave as expected, charging and discharging as much as possible before ending with a full battery by the time peak period begins at 5:30am

### Expected behaviour
Predbat continues to optimise the plan to minimize costs

### Predbat version
v8.8.17 and above

### Environment details

- AIO
- Docker install
- IOG tariff

#### 8.8.17 plan
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/5a66dd7d-c02c-4341-a208-42bd067ec217" />

#### 8.8.16 plan
<img width="1096" alt="image" src="https://github.com/user-attachments/assets/6a1feb2a-e139-4331-a684-37d5bb8ae16e" />

### Predbat debug yaml file
[predbat_debug.yaml.txt](https://github.com/user-attachments/files/18277859/predbat_debug.yaml.txt)

**Comment by springfall2008** [comment]
That's bonkers I agree, will look

**Comment by springfall2008** [comment]
So I can see your plan but when I re-run it I get the more sensible plan instead. Could you please re-create the debug YAML with 'debug_enable' turned on so I get the intermediate load data information? It maybe worth updating to the latest release also in case I've already fixed it.

**Comment by springfall2008** [comment]
Okay I managed to reproduce this now, it seems to relate to the car charging - I'll debug it further

**Comment by springfall2008** [comment]
A new release v8.8.20 has been made to fix this issue

**Comment by sammort** [comment]
Thanks for taking a look at this and getting a fix in place so quickly @springfall2008.

Hope you have a Happy New Year.
