### ISSUE TITLE
Testing wrong key when reading `metric_octopus_export`

### ISSUE THREAD

**Issue by Tim-Mawson-i2** [springfall2008/batpred#2]
Line 512 should be testing for the existence of `metric_octopus_export`, not `metric_octopus_import`:

`if 'metric_octopus_export' in self.args:`

instead of

`if 'metric_octopus_import' in self.args:`

**Comment by springfall2008** [comment]
Thanks Tim, as chance had it I also fixed this issue yesterday:)
