### ISSUE TITLE
Octopus Energy update (V8)

### ISSUE THREAD

**Issue by Speshman** [springfall2008/batpred#23]
Since the Octopus energy was updated https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy it seems that batpred can no longer read the rates from it.
![image](https://github.com/springfall2008/batpred/assets/70112814/4e602439-5fc7-47ca-847d-0a777ab77520)

![image](https://github.com/springfall2008/batpred/assets/70112814/1d27954c-af0e-47cf-aeed-53fb9a0f1235)

![image](https://github.com/springfall2008/batpred/assets/70112814/40c9ba7d-0675-49ba-82e1-3ad0bd8fd233)

sensor.octopus_energy_electricity_22l4330885_2199998082940_current_rate is what my rate sensor is called, just in case your auto discovery is looking for something different

**Comment by springfall2008** [comment]
I've submitted a fix to master, will release it once someone else has tested it

**Comment by adamwylde** [comment]
I was seeing the same problem with Octopus 8.0.0… I’ve overwritten predbat.py with the one from master and my rates have returned and it looks like its correctly calculated my upcoming flex discharge window correctly, and tomorrows charge window, so I think the fix is good.

**Comment by dbrb2** [comment]
I can confirm this seems to have fixed the problem - I have only been running it for a few minutes, but the missing rates have reappeared. Thanks!

**Comment by springfall2008** [comment]
Thanks, I've made a release of this code now
