### ISSUE TITLE
Settings for Octopus agile import and fixed export

### ISSUE THREAD

**Issue by stefan-west1** [springfall2008/batpred#233]
### Discussed in https://github.com/springfall2008/batpred/discussions/232

<div type='discussions-op-text'>

<sup>Originally posted by **stefan-west1** October 31, 2023</sup>
Hi all. I'm completely new to this, so struggling a little with all the different settings. I have both solar and battery, and I'm currently with octopus agile for my import, and octopus fixed for the export. What I want to set up is basically for the system to charge from the mains when the price is the cheapest overnight, and not worry too much about export. My export rate is fixed at 15p per kwh, so if I can charge at less than that, to me it makes sense to fill the battery from the mains, and just allow all solar to export. However, I'm struggling to work out which things should be on, which should be off etc.

Essentially I want it to fully charge my battery each night if it can do it for under 15p per kwh, if the average price is going to be over that then I need it to fill the battery only up to where the solar can fill the rest the following day if that makes sense? </div>

**Comment by springfall2008** [comment]
This should work fairly well.

Based the default settings, adjust your rate low threshold to 0 (automatic) and your rate high threshold to 0 (automatic). 

What are you seeing?
