### ISSUE TITLE
BatPred dumping battery just before peak times!

### ISSUE THREAD

**Issue by stefan-west1** [springfall2008/batpred#237]
Hi all,

Still really new to all of this so I've bound to have set something up wrong. But for some reason, my battery is being fully exported right before 4pm, just in time for peak pricing to kick in!

Looking at the "Plan" card, for some reason from 4pm for a few hours, my predicted load is 0? It seems to be working for the rest of the day, just not for those critical few hours!

![Screenshot 2023-11-01 163727](https://github.com/springfall2008/batpred/assets/65961309/bd279cf0-20c9-44fb-834f-14508638fdf9)

**Comment by arti273** [comment]
Have you got enough days of load data? Also, what days previous settings do you have in apps.yml? Days previous:1 does not work very well.

**Comment by stefan-west1** [comment]
days_previous is set to 7. I've just checked my givenergy cloud however, and I'm now beginning to think the issue might lay there. For no apparent reason my battery just dropped from 36% to 4% instantly. I've only had the system fitted for a few weeks, so I don't really fully understand it all yet.

![Screenshot 2023-11-01 165404](https://github.com/springfall2008/batpred/assets/65961309/352d0837-ee45-4ce3-a5e2-ed0f504e0f85)

**Comment by stefan-west1** [comment]
As a temporary fix I’ve set best_soc_min to 2.0 to at least keep some battery for the peak times. Hopefully it’ll fix itself in a few days. As for the huge random battery drop, no idea what’s caused that. Hopefully just a glitch

**Comment by springfall2008** [comment]
It’s best to use best_soc_keep as min will set the minimum for all charges

**Comment by stefan-west1** [comment]
So it’s been a few days, but still from around 4pm onwards each day my predicted load is 0. I’ve also noticed that in the battery prediction card, from 4pm onwards it thinks the historic load was also 0. Not sure if this is an issue with batpred, givtcp, or GivEnergy themselves. 

As for battery dropping suddenly to 0. This apparently is a known issue with GivEnergy systems incorrectly stating the SOC and should be fixed in an upcoming firmware update. 

Any ideas on what's going on with the load issue?

![IMG_2798](https://github.com/springfall2008/batpred/assets/65961309/4dd8014b-faa6-4620-b564-5901bb0ebc53)
![IMG_2799](https://github.com/springfall2008/batpred/assets/65961309/f5f42ab7-ca37-4509-9fc8-11d8d6cd9614)

**Comment by springfall2008** [comment]
Have you checked your load data in GivTCP to see if it’s really zero in the previous days you configured?

do you have car charging hold turned on and if so what threshold?

**Comment by stefan-west1** [comment]
So below is my load data from GivTCP, While it does drop to 0 occasionally, it's never for any significant amount of time

<img width="800" alt="Screenshot 2023-11-03 212907" src="https://github.com/springfall2008/batpred/assets/65961309/003361e9-3df8-4865-9d97-ad2de56132b6">


As for the car charging hold, I just checked, and this is on with the threshold set to 6. I'll be completely honest, I'm trying to get used to this, but it's a steep learning curve for me, so there's a good chance I've screwed something up. If it makes any difference, I don't have an electric car

**Comment by springfall2008** [comment]
There's a couple of gaps in this data which will translate into periods of zero load. Do you have some sort of network issue perhaps where it's dropping offline?

The easiest way to around this is to average two or more days data e.g.

days_previous:
  - 2
  - 3
  - 4
 
If you keep enough history you can use 7 and 14 but the default in HA is only 10 days so you would need to increase that to maybe 15 days or more first.

**Comment by stefan-west1** [comment]
Thank you, that seems to have sorted it. Turns out I had some weird software glitch on the AIO which was causing the battery to drop off, stopping me from charging and discharging, and kept throwing up "Garbage data" errors in GivTCP which I imagine was where the missing data is. Since GivEnergy fixed it, it seems a bit more stable. But either way, I'll be keeping the average. Thanks again
