### ISSUE TITLE
Some weird interplay between battery charging and EV charging

### ISSUE THREAD

**Issue by adamwylde** [springfall2008/batpred#247]
Hi @springfall2008 

I'm seeing some odd behavior where predbat seems to be not making best use of the overnight cheap window. As you'll see from the below, when it hit 23:30 last night it charged up the battery although not fully despite the dreadful weather, then let it discharge to the house overnight. A few minutes ago the graph suggested it was then going to charge for half an hour at 06:00-06:30 because I have an extra intelligent charging slot then - but now thats plan has disappeared and its not charging up. You can see in the predicition we will run out of battery today.

[a0d7b954_appdaemon_2023-11-04T05-55-14.484Z.log](https://github.com/springfall2008/batpred/files/13255915/a0d7b954_appdaemon_2023-11-04T05-55-14.484Z.log)

![image](https://github.com/springfall2008/batpred/assets/39195357/20021a0a-5b2a-4248-b778-396ba253fd3c)

![image](https://github.com/springfall2008/batpred/assets/39195357/c645c4a4-f5c5-42fb-ae7c-2314a9e211e0)

Any ideas please?

Thanks

**Comment by adamwylde** [comment]
(I've just set best_soc_min to 9.5 to force it to charge temporarily)

**Comment by adamwylde** [comment]
A couple of other observations:

I've looked through the log and it looks like I've upload one that doesnt match the images - as I mentioned at some points the plan did show charging during the intelligent slot - the log does show that, the images were slightly later where it had reverted to not charging. Of course, either way, the point is it didnt charge fully, or the whole night like usual, regardless of this bonus slot.

FYI Now that I've set best_soc_min to 9.5, the prediction is showing the 'charge_limit_base' for tomorrow matching todays extra Intelligent slot (6-6:30) which is odd:
![image](https://github.com/springfall2008/batpred/assets/39195357/8d091ebc-b69f-49c5-8c4b-c3f8e8501bd5)

**Comment by springfall2008** [comment]
Somehow your plan period seems too short.
What do you have it set to in apps.yaml ?

**Comment by adamwylde** [comment]
Set to defaults:

  forecast_hours: 48
  forecast_plan_hours: 24

**Comment by adamwylde** [comment]
Seems to have been fine overnight, maintaining the full battery as expected right through some extra slots this morning. I didnt change anything!

![image](https://github.com/springfall2008/batpred/assets/39195357/a4c65457-ffb4-4ccd-8a11-b9e4b88f94f6)

**Comment by springfall2008** [comment]
I think you need forecast_plan_hours to be 48 in this case, it's confused because the extra slots are assumed to be repeated tomorrow (which they aren't).

That said I normally have the allow car to charge from battery turned off and that has the same effect overall.

What are you other settings, do you have combine charge turned on?

**Comment by adamwylde** [comment]
Allow car to charge from battery is off. (I'm not overly bothered it showed up tomorrows slots in the plan as by the time they are relevant they disappear anyway).
Combine charge slots is on.

I'm largely following your Intelligent settings guide.

Full options below:

![image](https://github.com/springfall2008/batpred/assets/39195357/4f82d72b-3a37-41ae-bb3a-5dbcd343ee3f)

Thank you

**Comment by adamzest** [comment]
Having had the car fail to charge overnight I got an extra Intelligent slot this morning which I'm currently in the middle of, and the rest of the plan is now not right, although I'm sure it will fix its-self once this slot has finished! (Best SOC Min is 9.5, so the overnight period this evening should be to the max). You mentioned that the plan needed increasing to prevent the repeating IO slot which I haven't changed, but the overnight charge is well within the next 24 hours and as I say, its min 9.5kwh anyway).

![image](https://github.com/springfall2008/batpred/assets/105922338/9ba06a92-b92c-4476-8c32-15cc0d42a2a3)

Having updated the plan hours to 48 fixes the overnight charge, but also continues to show todays bonus charge on tomorrows plan?

![image](https://github.com/springfall2008/batpred/assets/105922338/9030809c-8899-48a1-9bfb-76becded62be)

**Comment by springfall2008** [comment]
Isn’t the bonus charge the one in green as base, not the one Predbat has picked in yellow?

**Comment by adamwylde** [comment]
Yes your quite right 🤦‍♂️

I guess it’s working correctly then with 48 hour plan! Thanks
________________________________
