### ISSUE TITLE
Not forecasting battery discharge since 7.11.12

### ISSUE THREAD

**Issue by arti273** [springfall2008/batpred#255]
Hi Trefor, 
As discussed on Facebook, here is the latest AD log.
[appdaemon.log](https://github.com/springfall2008/batpred/files/13257089/appdaemon.log)
Many thanks 
Robin

**Comment by springfall2008** [comment]
Battery discharge is disabled "discharge rate 0.0 kw"

Either turn it back on manually or enable 'set_charge_freeze' which will also do it.
