### ISSUE TITLE
Latest update, entities missing

### ISSUE THREAD

**Issue by Redding43** [springfall2008/batpred#26]
Trefor, just installed the latest update and get a number of entities not working

update: looks like my Solcast has maxed out. Thanks Trefor, I’ll fix that

this follows updating the the latest version of core yesterday and solcast today[
![IMG_2810](https://github.com/springfall2008/batpred/assets/122637671/983514f0-f6b8-4cde-9fec-6fdaef2d032d)
](url)

**Comment by springfall2008** [comment]
![image](https://github.com/springfall2008/batpred/assets/48591903/f70281a8-8d5c-4bbb-be1f-38bdc207da70)

**Comment by springfall2008** [comment]
For reference the issue was Solcast not connected properly.
