### ISSUE TITLE
Repeated discharge slot alerts

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#264]
I've turned off most of the notifications from predbat now, only set discharge notify is on.

But some of the alerts don't make sense as to why I'm getting them generated. 

From 18:20 to 18:55 I got an alert every 5 minutes (x2 inverters) telling me that the discharge time slot was being set.
I got repeated alerts that the slot was being set to 1850-1900 before from 1850 when I was then told that the slot is being set to 1845-1900

Why so many alerts that are all the same slot setting?
Personally I'd like the notifications simplified, I think I only really want to know when the batteries start and end force charging and force discharging. The slot changes are not really very useful /interesting 

![image](https://github.com/springfall2008/batpred/assets/142018870/fe5daaba-478d-401d-b50e-df2817dfd8c3)
![image](https://github.com/springfall2008/batpred/assets/142018870/ac731094-c9c8-4800-b482-ad667673174b)
![image](https://github.com/springfall2008/batpred/assets/142018870/a2845d39-6be9-48ec-b7cd-c5f01f5467db)
![image](https://github.com/springfall2008/batpred/assets/142018870/8b0b5f35-4cf2-4add-8311-2c2fc838ffe4)

**Comment by gcoan** [comment]
Here's the logfile for this period
[appdaemon (4).log](https://github.com/springfall2008/batpred/files/13260577/appdaemon.4.log)

**Comment by springfall2008** [comment]
I'm hoping this is fixed by this release: https://github.com/springfall2008/batpred/releases/tag/v7.11.7

**Comment by gcoan** [comment]
That was quick!

I'll install it and let you know.  Thanks

**Comment by gcoan** [comment]
The release note and the change you made to the sample dashboard are for the switch called set_state_notify but the actual new switch is set_status_notify 

Which is correct?

Cheers

**Comment by springfall2008** [comment]
Ah crap it’s status, will fix the readme soon

**Comment by gcoan** [comment]
Thanks for the  confirmation, I'll change my dashboard

**Comment by gcoan** [comment]
I just noticed a series of rest errors in the predbat status so maybe that's why I kept on getting messages about the discharge slot being set every 5 minutes?
![image](https://github.com/springfall2008/batpred/assets/142018870/38488976-1139-40d0-a6bb-fb08e66541e0)

**Comment by springfall2008** [comment]
I'm pretty sure this was fixed in the latest release, but your message still shows the old issue which is likely before the update?

**Comment by gcoan** [comment]
I was on the prior release 11.6 when I noticed it and logged this issue.

Soon afterwards I saw the new release which I’ve installed.  Just going to see how it runs tonight at peak discharge time to confirm it’s fixed

Thanks

**Comment by gcoan** [comment]
This is on 7.11.7.  I'll install 7.11.8 now 

Not got repeated discharge time slot alerts but am seeing multiple discharge rate alerts. Are these duplication detected as well?

![image](https://github.com/springfall2008/batpred/assets/142018870/1fc08ab9-cb2b-4230-bb7c-1b887bea8558)

**Comment by springfall2008** [comment]
Believed to be fixed
