### ISSUE TITLE
Midnight issue

### ISSUE THREAD

**Issue by slopemad** [springfall2008/batpred#268]
I see an issue every day when Predbat does it's midnight run, in that the entire plan for the immediate future is removed.

<img width="541" alt="Screenshot 2023-11-06 at 00 02 07" src="https://github.com/springfall2008/batpred/assets/118896510/3d55d839-30c1-4b1d-aa7d-f6c56377877f">

The 00:00 run log is here: https://pastebin.com/E4ETAvBZ

And the plan returns in the 00:05 run.  I see this consistently every day.

<img width="387" alt="Screenshot 2023-11-06 at 00 06 32" src="https://github.com/springfall2008/batpred/assets/118896510/de063b3b-6945-4dba-a884-a48e98514a50">

The 00:05 run log is here: https://pastebin.com/Kfhvxkqr

Could it be related to this in apps.yaml?

  days_previous: 
    - 1
    - 7
    - 14

  days_previous_weight:
    - 1
    - 0.8
    - 0.6

**Comment by springfall2008** [comment]
Good spot, I pushed a fix and it will be in the next release

**Comment by gcoan** [comment]
I think I saw the same issue myself last night, and I was running 7.11.8 which the midnight fix #270 was included in.

Just after midnight I looked at predbat to see when the cheap period was to put the washing machine on at was, and was astonished to see that there was no charging or discharging planned for the day and the battery would empty out.
I didn't get much chance to look at it then, or take a screen shot, but when I next looked at 00:05 there was a normal pattern of charging and discharging planned for the day.
So not entirely sure this is fixed.

Here's my logfile for around midnight if you can see what the issue might be?

I will take another look tonight if I can see if happens again

[appdaemon.log.5.txt](https://github.com/springfall2008/batpred/files/13278616/appdaemon.log.5.txt)

**Comment by springfall2008** [comment]
Not surprising since I got it the wrong way around!

https://github.com/springfall2008/batpred/releases/tag/v7.11.10

**Comment by gcoan** [comment]
Looks like it's fixed now

Before midnight 
![image](https://github.com/springfall2008/batpred/assets/142018870/50173f9e-1350-4f90-bd72-d27ea780cbf0)

First run after midnight 
![image](https://github.com/springfall2008/batpred/assets/142018870/689b351a-d6fc-44fc-8e5b-0dc5534fc207)

And in the following runs, it didn't change again

**Comment by springfall2008** [comment]
Great, thanks for helping with this.
