### ISSUE TITLE
Different discharge time slots for the two inverters

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#278]
This isn't affecting my discharge but I've noticed it since 7.11.7 that the start time for inverter 1 discharge is being set to 00:00 not the actual time.  Error 8n a variable name or using an uninitialised variable?

![image](https://github.com/springfall2008/batpred/assets/142018870/288f577d-4aaf-4312-95ef-efd62102c10b)
![image](https://github.com/springfall2008/batpred/assets/142018870/12bf4312-510d-4ace-b58a-0fe117d60913)

**Comment by springfall2008** [comment]
I think its maybe as expected, in that the start time isn't changed if it's in the past to avoid constantly updating it.

**Comment by gcoan** [comment]
I’m not sure. I’ve pretty much seen the two inverters always move in sync.

It would make sense to not change the start time if it’s in the past, except of course when it’s setting up a discharge slot for the future

I’ll set inverter 1 discharge time to the same as inverter 0 and see what happens at the next discharge period

**Comment by gcoan** [comment]
There's been a couple of discharges this afternoon and in both occasions the inverters have moved the same together 

![image](https://github.com/springfall2008/batpred/assets/142018870/2a272dff-d473-400a-bbed-5c691c3f369a)
![image](https://github.com/springfall2008/batpred/assets/142018870/0acfaae0-f593-4e72-9630-03e1f460e041)

So can only come conclude that the dissimilar times before were as a result of a manual discharge I'd done 

Will close this as not being an issue
