### ISSUE TITLE
Status Warning

### ISSUE THREAD

**Issue by SheriffOfNotts** [springfall2008/batpred#279]
Hi Trefor, I've been trying, without success to get rid of a status "Warn - Return bad float value unavailable from
car_charging_soc". I'm not sure exactly what this means?

This is the extract from apps.yaml:

 car_charging_soc:
    - sensor.id_3_state_of_charge
    - sensor.volvo_charge_level

Both sensors are numbers - float(0) and round (0)

**Comment by adamwylde** [comment]
Innocent bystander here, but maybe you are missing the quotes? Mine looks like this…

car_charging_soc: 
    - 're:sensor.cupra_born_state_of_charge'

**Comment by springfall2008** [comment]
It's saying the sensor is returning 'unavailable' rather than a value

**Comment by SheriffOfNotts** [comment]
Ah ok, thanks Trefor.

**Comment by springfall2008** [comment]
Did you re-open on purpose or was this a mistake?
