### ISSUE TITLE
Lost helper card

### ISSUE THREAD

**Issue by Speshman** [springfall2008/batpred#28]
More than likely something I've done but I seem to have lost the helper card from my dashboard, is there an easy way to readd the whole card?

**Comment by springfall2008** [comment]
Do you mean this? https://github.com/springfall2008/batpred/blob/main/example_dashboard.yml

**Comment by springfall2008** [comment]
There isn't a default card for Predbat I'm afraid.

**Comment by Speshman** [comment]
Perhaps my terminolgy is off.

When first installing predbat it autopopulates several cards on the main dashboard, one of which is titled helper and has various toggles, offsets etc on it.  This is the card I have 'misplaced' and given that it was autopopulated during install I was hoping to reclaim it

**Comment by springfall2008** [comment]
I think this is when you had your dashboard set to automatic rather than manual, Predbat itself doesn't have such a card but the above link maybe useful for you.

**Comment by springfall2008** [comment]
Resolving this ticket, please re-open if you have any further questions
