### ISSUE TITLE
Gaps in charging on consecutive charge slots

### ISSUE THREAD

**Issue by wilsondw** [springfall2008/batpred#284]
With combine charge slots = false, Predbat calculates separate SOC targets tor each 30 min slot in the 3 hour flux cheap rate period. Towards the end of each slot, the battery charge often matches or exceeds the target and the charging pauses until the next Predbat run completes and the new target is set. When trying to charge from empty to 100% SOC in the three hour cheap rate window, these gaps in charging of a few minutes every half an hour mean that the battery doesn’t reach 100% by the end of the cheap rate. 

Would it be possible to have a mode in between combine slots true and false where Predbat calculates the plan based on charge slots false but then combines consecutive charge slots in the plan sets the end target SOC for the whole block to maximise the chances of successfully charging to that target?

**Comment by springfall2008** [comment]
So I thought I recently made a change to do just that in v7.11.10, what version are you on?

**Comment by wilsondw** [comment]
I’m on 7.11.10. Is there a switch to enable this or should it be automatic when combine charge slots is false?

**Comment by springfall2008** [comment]
Should be automatic

**Comment by wilsondw** [comment]
Don't think it is quite working then :-( The picture shows the grid to battery power flow for last night when it was trying to charge to 100% from empty. It got to 97% - so not far off but would probably have made it another percent or two without the gaps at the end of the half hour slots when SOC reached the target predbat had caclulated for the slot.  Looks like another full charge tonight so will try to grab the logs in the morning. 

<img width="1057" alt="Screenshot 2023-11-08 at 21 16 02" src="https://github.com/springfall2008/batpred/assets/114885151/20070b18-18ad-4df1-9ad6-3eabd7c1515c">

**Comment by wilsondw** [comment]
No log from last night as encountered a different problem (div by zero) which resulted in no overnight charge... Will raise a separate issue on that one

**Comment by wilsondw** [comment]
Logs and power flow for today's cheap rate charge period attached. There were some REST errors again before the charge window but no div by zero problem so charging went ahead as planned, thanks. Separately, I'll increase the log level on GivTCP to see if it gives any hints on why the REST errors are happening.
[appdaemon log.zip](https://github.com/springfall2008/batpred/files/13316908/appdaemon.log.zip)
<img width="808" alt="Screenshot 2023-11-10 at 07 35 16" src="https://github.com/springfall2008/batpred/assets/114885151/01527608-c116-4128-8bf8-6f6ad6f325c4">
