### ISSUE TITLE
 ERROR: Exception raised float division by zero

### ISSUE THREAD

**Issue by wilsondw** [springfall2008/batpred#287]
At 23:30 last night, the predbat log shows there was a problem reading from givTCP over REST API. Then on every subsequent run overnight predbat quits with  ERROR: Exception raised float division by zero. givTCP log does not show any errors and inverter/battery data is available in Home assistant history. Restarting appdaemon this morning solved the problem and the next predbat run completed ok. Predbat log attached.
[float div be zero - 1 appdaemon.log](https://github.com/springfall2008/batpred/files/13304549/float.div.be.zero.-.1.appdaemon.log)

**Comment by springfall2008** [comment]
I think I have found the issue, will push a fix today, but the real issue is why REST has stopped working

**Comment by springfall2008** [comment]
I've released a fix for this now, I hope it won't happen again

**Comment by wilsondw** [comment]
Thanks - have updated
