### ISSUE TITLE
missing item in config file

### ISSUE THREAD

**Issue by marcoaddario** [springfall2008/batpred#305]
There is a new config item missing from the `ginlong_solis.yaml` file and probably from the `other-inverters.md`

When this is not set, it raises and exception.

I assumed it should be set as 

```
  energy_control_switch: 
    - select.solis_energy_storage_control_switch
```

following the same format in the config file

**Comment by fboundy** [comment]
Thanks - that's a recent add that obviously didn't make the PR

________________________________
From: Marco Addario ***@***.***>
Sent: 11 November 2023 10:27
To: springfall2008/batpred ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [springfall2008/batpred] missing item in config file (Issue #305)


There is a new config item missing from the ginlong_solis.yaml file and probably from the other-inverters.md

When this is not set, it raises and exception.

I assumed it should be set as

  energy_control_switch:
    - select.solis_energy_storage_control_switch


following the same format in the config file

**Comment by fboundy** [comment]
Fixed in the `inverter-support` branch
