### ISSUE TITLE
Plan 'state' explanations in documentation

### ISSUE THREAD

**Issue by slopemad** [springfall2008/batpred#362]
Might it be worth adding something to the documentation to explain the various 'states' in the Predbat plan?  Some are more obvious than others, but it might be worth a little explainer as to what 'FreezeChrg', 'Charge/Discharge' and 'FreezeDis' might actually mean from the point of view of what it would change on the inverter?

For example, I'm a little confused about what the plan actually might intend to do during the 'Charge/Discharge' state here...?
<img width="638" alt="Screenshot 2023-11-22 at 21 50 39" src="https://github.com/springfall2008/batpred/assets/118896510/6f2beda2-bed8-4a2d-8b29-8b2086688c27">

**Comment by gcoan** [comment]
+1 from me on this point. I’ve looked and it isn’t covered that I could find

The charge and discharge means within the 30 min slot, some of the 5 minute predbat runs will be charging and some will be discharging

**Comment by slopemad** [comment]
That's what I thought,  but then I also have "Calculate Discharge on charge slots" set to False...  I've since upgraded to 7.13.6, that Charge/Discharge part of the plan has gone away.

**Comment by gcoan** [comment]
I've got calculate discharge on charge slots on

Makes sense to me to have it on for periods like now when export rate is higher than import rate

![image](https://github.com/springfall2008/batpred/assets/142018870/6189bdbc-31b3-4ccb-a1bc-ccf3ffdf1ea8)

Only issue it keeps freeze charging not charging #357

**Comment by slopemad** [comment]
What I have right now is a flat battery and a plan to charge right now even though the current slot is the most expensive for the next few hours (it isn't charging as it's in read only, it doesn't really need to start charging until 1.30am.  Might be an artifact of the recent feature of adding the next 4 hours into the plan?

<img width="552" alt="Screenshot 2023-11-22 at 23 36 05" src="https://github.com/springfall2008/batpred/assets/118896510/bc73e28e-f44d-4498-9280-b3506f036d71">

**Comment by springfall2008** [comment]
This will likely be the result of metric keep being non zero forcing a charge

**Comment by slopemad** [comment]
So here's what I want to try and understand, specifically around FreezeDis and FreezeChrg, and what they are intended to mean.  Here is the current plan:
<img width="566" alt="Screenshot 2023-11-23 at 09 44 21" src="https://github.com/springfall2008/batpred/assets/118896510/b94a585b-22b3-46b0-848d-562306f21206">
A bunch of 'FreezeDis' for the next few hours.  To me, 'FreezeDis' means "No more discharging of the battery", whereas actually it seems to really mean 'No more charging of the battery'.  In 'FreezeDis', the inverter's Battery Charge Rate is changed to zero, which in practice just means 'export excess solar'.

(I added this extra show_limit line into the code at line 5236 to visualise what 'limit' means)
```
                    state += "FreezeDis&rarr;"
                    show_limit = str(int(limit))
```

So, does FreezeDis simply mean 'Eco mode, export excess'?

Meanwhile, FreezeChrg seems to mean 'No Charging, no Discharging either, run the house off mains', i.e. Pause the battery.  The logs suggest that at the last change to Freeze charging, SOC was set to 4, and discharge rate was set to 0. (Which would, of course, mean no mains charge, no discharge at all, excess solar into the battery though).

Is this the intention with these two states?

**Comment by springfall2008** [comment]
So maybe the names are confusing

Charge -> Battery is charging -> Grid charges battery and covers load
Charge Freeze -> Battery is held at the current charge level (charging with soc target == current level) -> Grid covers load, battery can charge from solar only
Discharge -> Battery is force discharging -> Battery covers load and exports to grid
Discharge Freeze -> Battery is held at the current discharge level (discharging with target == current_level) -> Solar is exported, battery will cover the load

**Comment by springfall2008** [comment]
Added some documentation here: https://github.com/springfall2008/batpred/blob/main/docs/what-does-predbat-do.md

**Comment by gcoan** [comment]
Thanks Trevor.

It looks like the freeze discharge ha# got muddled/copy paste partly from an earlier status

Discharge Freeze - A slot where the current battery is held at the current level. The battery covers the load. Any solar generated will be exported.



The battery can’t be held at current level if it’s also supporting house load?

I think there’s some more intro needed.  You hav3 these predbat modes under battery terminology, but they’re not really battery terms, they are describing wha5 predbat does with the battery.  The descriptions talk about slots and the earlier text on the page doesn’t introduce the 30 minute slot and plan concept.
Also Eco mode IS a battery term but predbat corresponding status is idle and the difference isn’t clear

**Comment by springfall2008** [comment]
I've updated the wording again, have a look and see what you think

**Comment by gcoan** [comment]
Found it in the main branch. Reads much better thanks.
