### ISSUE TITLE
Low priority enhancement: populate battery_hours_left when charging

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#366]
I display the battery hours left entity on my dashboard as it's a useful predbat indicator of how long the battery will support house load (-pv generation) but when the battery is being charged it's set to zero which reduces its usefulness.  Is it possible to continue population based on current soc etc?

![image](https://github.com/springfall2008/batpred/assets/142018870/ee73053f-7a3e-4cef-b501-43b04b1f1566)

**Comment by gcoan** [comment]
![image](https://github.com/springfall2008/batpred/assets/142018870/0621f4de-8c4d-4ca8-a37f-6bcf8f26d969)

**Comment by springfall2008** [comment]
I found a recent bug and hopefully fixed this

**Comment by gcoan** [comment]
Its populated now when charging (and soc>4%) but the figures look a bit "generous"

0.37kWh=1.75 hours
![image](https://github.com/springfall2008/batpred/assets/142018870/ee626eb8-e3bd-4587-bef1-9813b74eb3d6)

When discharging earlier, 0.42kwh=2.17 hours
![image](https://github.com/springfall2008/batpred/assets/142018870/aa283fbb-7769-4f73-b590-6ec4fcaac5eb)

current load is 1.33kwh for this slot

**Comment by slopemad** [comment]
31kWh in your Heat Pump though! Mine's used about 14kWh today, and my house has been over 20 degrees all day.  Probably not a Predbat issue ;-)

**Comment by gcoan** [comment]
> 31kWh in your Heat Pump though! Mine's used about 14kWh today, and my house has been over 20 degrees all day. Probably not a Predbat issue ;-)

Yeah the heat pump can use a lot.  Yesterday was only 14kW and the day before 21. Its very weather dependent.  The total house bill is Around £5-7 a day and since I was generating about £5 a day in summer, I'm OK with that.
