### ISSUE TITLE
Charging to 100%

### ISSUE THREAD

**Issue by Philhews** [springfall2008/batpred#389]
When charging to any soc below 100 predbat disables the charge and sets the reserve once it gets there. This seems to work fine, but when charging to full it looks like it fails to set the reserve so the battery then discharges a bit only to be recharged by predbat on its next calculation.

I am unable to manually set the reserve to 100 either via GivTCP (it immediately reverts to the previous value rather than setting it) so I think it's an inverter thing not a predbat thing but I was wondering if there's any way that the method of holding charge can be changed (config or otherwise to use the pause option maybe) or I can limit where predbat will charge to at 99 instead (which works)? 
![Screenshot_2023-11-29-07-44-07-22_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/a2625e6d-58e7-416a-a19b-65fdd9b832f1)
![Screenshot_2023-11-29-07-44-20-93_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/e0c855ec-80f5-483a-921a-5ef63aa0b543)

**Comment by springfall2008** [comment]
Maybe try this in apps.yaml:

  # Workaround to limit the maximum reserve setting, some inverters won't allow 100% to be set
  # inverter_reserve_max : 99

**Comment by Philhews** [comment]
Will give it a go, thanks.

**Comment by springfall2008** [comment]
I've changed the default apps.yaml to be 98% now to avoid these issues
