### ISSUE TITLE
Holding charge overnight

### ISSUE THREAD

**Issue by Denao2** [springfall2008/batpred#390]
Please can you offer any insight as to why predbat would be holding charge at 21% overnight, before starting to recharge in my low rate period in the morning. It has previously been allowing battery to discharge a minimise import - which is intuitively what I would expect? - The saving event appears to have been detected correctly.

<img width="293" alt="image" src="https://github.com/springfall2008/batpred/assets/23340281/0eded4fa-6787-43b7-b87a-c3b6a02be8bf">

**Comment by springfall2008** [comment]
I assume you have best soc keep set to something sound 21%?

**Comment by springfall2008** [comment]
> I dont beleive so. <img alt="image" width="221" src="https://private-user-images.githubusercontent.com/23340281/286626498-9410557e-4a24-48b4-ba6c-ec830cbb1ffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzc1MjIsIm5iZiI6MTcwMTI3NzIyMiwicGF0aCI6Ii8yMzM0MDI4MS8yODY2MjY0OTgtOTQxMDU1N2UtNGEyNC00OGI0LWJhNmMtZWM4MzBjYmIxZmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE3MDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlODYyMzc4Y2FlNGU2MTkxNDYyMGJkMWMwMGY5NTMwN2MyOTcwOGQ2NTZmNDRmYmZjZDVmNzU2MjcxZDQ4N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HK7flyKQpCxtmU1W2Gv6tW5hsfRjJA354QMDDmd_y0I">

Yes, best soc keep is set to 2kwh is which probably around 21%?

**Comment by Denao2** [comment]
Ah. I see. I misinterpreted the units.

Thank you for the prompt support.
