### ISSUE TITLE
Supressing "Predbat status change to: Idle" notifications

### ISSUE THREAD

**Issue by Speshman** [springfall2008/batpred#392]
Is it possible to supress only these notifcations from the phone app?  I seem to get quite a few of them and I'm not sure I need them but want to keep all the others (Android if that makes a difference)

**Comment by springfall2008** [comment]
You can either turn them off with the notify settings in home assistant or you can change the notified devices list in apps.yaml

**Comment by Speshman** [comment]
Hi trefor,  I want the notifications just I seem to get quite alot of idle notifications throughout the day.

**Comment by springfall2008** [comment]
Oh I see, in theory you only get it when it changes to idle from something else e.g. charging->idle, is that not the case?

**Comment by gcoan** [comment]
I see a lot of notifications as well, it's better than it was with the previous notification approach but I get multiple idle notifications and notifications when predbat swaps between charging and hold charging - I can see that happening in the soc chart as well 

I think @Speshman just wants to surpress the Idle notifications, but I see a lot regardless 

![image](https://github.com/springfall2008/batpred/assets/142018870/f42e0c7e-9eb3-4067-a76c-c3963f5ad0f5)
![image](https://github.com/springfall2008/batpred/assets/142018870/dfc9fa0b-71e6-4ec1-a9f6-6d1403bcb4dd)
![image](https://github.com/springfall2008/batpred/assets/142018870/35c2362f-b3d4-4be7-8f23-d756fce6e390)
![image](https://github.com/springfall2008/batpred/assets/142018870/78674979-b224-491d-a5a2-28a215466cc9)

**Comment by Speshman** [comment]
I seem to get idle messages on  repeat even when there hasn't actually been a state change.

**Comment by springfall2008** [comment]
> I seem to get idle messages on repeat even when there hasn't actually been a state change.

Do you have multiple inverters?

**Comment by Speshman** [comment]
Nope just one. Although it seems to no longer be doing it on the latest release

**Comment by Speshman** [comment]
![Screenshot_20231205-222810](https://github.com/springfall2008/batpred/assets/70112814/49e9797c-c9cf-4335-b362-7da258fc6b98)

Randomly happened again, frequency is less.

**Comment by Speshman** [comment]
![Screenshot_20231214-133757](https://github.com/springfall2008/batpred/assets/70112814/1839fd63-a8e5-43d5-89d8-ece6f7578053)

**Comment by springfall2008** [comment]
Are you restarting home assistant or rebooting appdaemon? I wouldn't expect this normally unless something changed.

**Comment by Speshman** [comment]
Finally worked out what's causing it. Losing API connection to Renault and then picking it back up. When it does pick it up the predbat idle status is going to notifications.

![Screenshot_20240511-222912](https://github.com/springfall2008/batpred/assets/70112814/096da0e0-268d-40de-9a1a-4b735498566b)
