### ISSUE TITLE
Respecting SOC Keep

### ISSUE THREAD

**Issue by JonathanLew1s** [springfall2008/batpred#405]
I have SOC Keep at 2.5kWh, expecting that the system will work to maintain SOC at a % above the reserve, yet I do not see the system planning to hold/maintain charge at that level.

2.5 would equate to around 12%, plus reserve at 4%. Shouldn't the system at a minimum hold the charge at 16% in the low rate slot and not plan to get to 4% before holding? Strange it calculates down to 4% and then hold in a medium rate slot.

Tried both 24 and 48 hour windows, tried adjusting SOC keep. 

![image](https://github.com/springfall2008/batpred/assets/34936213/fbdb5c4e-2434-49a2-bcd8-981d4df90249)

**Comment by JonathanLew1s** [comment]
Changed it to 3.5 and no change in plan.

![image](https://github.com/springfall2008/batpred/assets/34936213/b5dd02c7-b0e0-4e05-828a-c777ad7d32f0)


[_appdaemon_logs.txt](https://github.com/springfall2008/batpred/files/13536526/_appdaemon_logs.txt)

**Comment by springfall2008** [comment]
This is because your rate_low_threshold is set to 0.8 and so Predbat can't use any charge slots earlier in the day. Either set it to 0 for automatic or go to something like 0.85 or 0.9
