### ISSUE TITLE
Saving session beta

### ISSUE THREAD

**Issue by kingjpc** [springfall2008/batpred#425]
My systems doesn't seem to have auto joined. Looking at the code you do a replace for sensor but only when looking at joined events?

entity_event = entity_id.replace("binary_sensor.", "event.").replace("_sessions", "_session_events")

**Comment by springfall2008** [comment]
So I think I fixed this in https://github.com/springfall2008/batpred/releases/tag/v7.14.1

Like you said the name was wrong here, but there was also a second issue with the service call I fixed

**Comment by kingjpc** [comment]
I have manually added to this session so I am unable to confirm but happy for you to close this if you think its fixed now.
