### ISSUE TITLE
No dashboard.yaml

### ISSUE THREAD

**Issue by stefan-west1** [springfall2008/batpred#428]
I think I'm missing something really obvious here. I'm running appdaemon and predbat as a docker container. I'm getting the error Exception raised [Errno 2] No such file or directory: '/config/predbat_dashboard.yaml'

I can't see where I would get this file or how to generate it?

**Comment by springfall2008** [comment]
It's trying to generate that file, if it's missing create a soft link from /config to your HA config directory

**Comment by springfall2008** [comment]
Fix in: https://github.com/springfall2008/batpred/commit/e53f8c7e59368aca97547da1ecff9212a3f6aa90
