### ISSUE TITLE
AttributeError: 'PredBat' object has no attribute 'inv_has_target_soc'

### ISSUE THREAD

**Issue by robbstech** [springfall2008/batpred#433]
Just updated to the latest version. And I get the following error:
AttributeError: 'PredBat' object has no attribute 'inv_has_target_soc'

I have to manually update as I run HA in a docker container and run appdaemon as a separate container. Couldn't get it working through HACS. Any help would be appreciated.

Thanks

**Comment by springfall2008** [comment]
Sorry I noticed that and pushed a fix already so just take latest from master again

**Comment by robbstech** [comment]
Yes that worked, thank you so much
