### ISSUE TITLE
predbat plan does not seem to be accounting for solar as well as previously

### ISSUE THREAD

**Issue by AGLAISTER** [springfall2008/batpred#434]
I've noticed a pattern that when there is good solar days the predbat plan is charging more than I'd expect.
This is leading to the situation where my battery reaches 100% and then i'm either dumping to my iboost or to the grid.
iBoost is turned off

I'm on agile import, I don't do dumps to the grid normally as I'm on FIT deemed export so I use all that i generate and import for myself so this is why I want to minimise grid import when there is a good solar day ahead as it is not the most cost effective for me.

In the screen shot below you can see where the plan charges the battery to full by about 4:30 am 
This is even though that the plan then expects the battery to be full by late morning/lunchtime.
You can see from the arrow leading to immersion temp that the PV then fortunately is dumped to my iBoost than being lost.

Before raising the log I did set metric min improvement to 0.1 and discharge improvement to 0.1 but this seems to have made minimal difference.

![image](https://github.com/springfall2008/batpred/assets/141528175/7da1d2c0-81bd-42e0-8f56-1ff7c83f83d1)

i've attached the logs for the last 24 hours
[appdaemon2.log](https://github.com/springfall2008/batpred/files/13583732/appdaemon2.log)
[appdaemon3.log](https://github.com/springfall2008/batpred/files/13583733/appdaemon3.log)
[appdaemon.log](https://github.com/springfall2008/batpred/files/13583734/appdaemon.log)
[appdaemon1.log](https://github.com/springfall2008/batpred/files/13583735/appdaemon1.log)

I also notice a lot of flicking between not charge and idle in my plan and of late a lot of charge holding in a morning about 7am which is not ideal for me as we often have kettles or toasters going for breakfast.

I'm sure this is a case of some settings rather than a bug but this is an easier way to share the data/information to you than via facebook.

**Comment by JonathanLew1s** [comment]
@AGLAISTER Solar actual was higher than Solcast forecast? 
Predbat uses the 10% value rather than the best. In your example 10% 1.7kWh vs a solcast best of 3.4kWh. In the summer the 10% and the best are equal, as we get further into winter they diverge. This avoids that the plan is based on best case and you potentially end up under charging and empty battery in peak. Occasionally the 10% is pessimistic and solar will outperform, this can lead to the situation you experienced with some unexpected discharge.

Looks like you have a single 9.5kWh battery and a daily usage forecast at 9.9kWh, predbat is going to use the full range of your battery to minimise cost. You can change the weight numbers to be a little more optomistic, however you increase chances that you will empty your batteries vs pessimistic that you have occasional discharge. Predbat cannot control the sun.

**Comment by AGLAISTER** [comment]
@JonathanLew1s "@AGLAISTER Solar actual was higher than Solcast forecast?" are you asking me if the actual was higher than the forecast or saying it was I'm not clear
I don't know how to interpret the logs to confirm if its the latter however what I can say for sure is I update my solcast forecast 8 times per day
At the time of raising this issue the updates were at 2am, 4am, 7am, 12pm, 2pm 4pm 8pm and 12am. I've since changed the the early and later ones to 1am, 3am, 6:30am and 11pm

I fully get that the solar forcast is not an exact science and anecdotally I have notice my panels out performing the forecast so I actually altered the PV scaling upwards to get it to be more optimistic on my generation data.

Now this is where it gets interesting. Today is a poor solar day, prices overnight on agile compared to recent are lower
At the time of going to be my plan was charging to 95% overnight, however during the night it then changed to barely 70% this morning. 

![image](https://github.com/springfall2008/batpred/assets/141528175/f4f8ac0e-bb59-4023-8e13-37bdd91a9f33)

To me I am having an issue, not enough grid charge on cloudy days, too much on sunny days and so I've raised this with accompanying logs to try to see what I need to do with my settings to get this working better or if there maybe some competing settings for those using predbat for SEG/SEG2 that don't suit me on Agile/Deemed Export

**Comment by JonathanLew1s** [comment]
Today there are low import rates during the day as well as overnight, your system charged overnight to cover the load until the next low rate window, planning a charge late morning/early afternoon to cover the load until late evening rates.

Mine is similar today, to me this is predbat acting as expected. Covering the forecast usage, based on historic use with a mix of grid charge and PV generation. 

![image](https://github.com/springfall2008/batpred/assets/34936213/fd4f665f-1fe3-4b1e-9a30-e13d42aa7388)

House usage and PV generation are best guess based on the data available, and Trefor has provided a number of options to influence the resulting plan.

Increasing input_number.predbat_pv_metric10_weight will result in a more optimistic PV forecast. 

- Pro. You may avoid export
- Con you may under charge if PV generation doesn't occur.

Decreasing best_soc_keep will result in the plan using the full range of your battery. 

- Pro. Your plan will less frequently plan to a 100% charge, leaving battery capacity for unexpected PV generation.
- Con. If house usage is higher than historic/forecast you could drain your battery and grid import.

Personally, I leave metric10_weight to 0.15 and best_soc_keep at 1.5 with a mindset that i'd rather have an unplanned export that earns a few pennies than an unplanned import that could cost me a lot more. That over the longer term predbat maximises the benefits even in some edge cases it's not perfectly optimised.

**Comment by AGLAISTER** [comment]
@springfall2008 @JonathanLew1s  thanks for your support guys
@springfall2008 I've attached the logs pertaining to the overnight period
[appdaemon2 (2).log](https://github.com/springfall2008/batpred/files/13602573/appdaemon2.2.log)
[appdaemon1 (2).log](https://github.com/springfall2008/batpred/files/13602576/appdaemon1.2.log)

I had changed Metric 10% to 0,15 today and I've tweaked SOC keep down to 1.5 from 2

This is the current dashboard I'm seeing 
![image](https://github.com/springfall2008/batpred/assets/141528175/1231239e-e7db-4647-a230-1c8ed4e0b6e4)
this is showing a tiny amount of generation tomorrow between 10 and 12.

And this is my plan so far for the next 24 hours or so - bit confused by the chart to be honest cos I don't see the point of the hold charge segments where the hold is lower than the predicted SOC

![image](https://github.com/springfall2008/batpred/assets/141528175/46f07d00-3bd4-4ebe-9c51-cc9e936ea62e)

I get there are losses and I probably need to do the maths on things but from my view if I've imported the energy already I'd rather be using it even if I lose a small percentage of it not holding it and importing more.

Is it a case I tweak my inverter, discharge and charge losses?

**Comment by springfall2008** [comment]
I think you might find the old charges are acting on the PV 10% case but not on the 50% case so they will only do something if solar is worse than planned or consumption is higher.

If you try with lower loss settings then you might get more what you expect, but probably at higher real cost.

**Comment by springfall2008** [comment]
Probably fixed now with the cloud model fixes, please re-open if there is a new issue
