### ISSUE TITLE
Predbat still wants to charge at too high a price on Agile

### ISSUE THREAD

**Issue by fboundy** [springfall2008/batpred#442]
Predbat still seems to want to charge at too high a price on Agile. See the plan below where it is starting charging at 7pm at 20p when all the charging needed could be done from midnight onwards at <14p.

![image](https://github.com/springfall2008/batpred/assets/5152701/2206dc9f-9912-440e-8351-2ba7739de23e)

I calculate the optimum plan to be this which I think is about £1 cheaper by 7pm tomorrow

![image](https://github.com/springfall2008/batpred/assets/5152701/d6cb3804-7c5b-48a0-bbe0-ee8763e71030)

I think it's because the Low Threshold is set to 25.8p which seems far too high. But then I don't really understand the need for Thresholds....

**Comment by Redding43** [comment]
Did the view change as you approached as the prices that are 14 have a ‘?’ Meaning that at that point this was the potential price and not guaranteed

**Comment by fboundy** [comment]
Can’t say for certain but I know what algorithm Trefor uses and I know they aren’t going to change very much

**Comment by springfall2008** [comment]
A lot of this is down to losses, if you set charge, discharge, inverter losses and metric battery cycle to 0 then you will just get the cheaper slots. Running at 100% and importing means no losses

**Comment by fboundy** [comment]
Not sure I get that. The same losses are involved to charge the battery at 20p as at 14p so why charge it earlier and then hold the charge at 100%

**Comment by springfall2008** [comment]
In the meantime you would have to supply the home from the battery so those losses are included.

**Comment by fboundy** [comment]
If the battery is empty you are supplying the house from the grid so where are the losses?

**Comment by springfall2008** [comment]
> If the battery is empty you are supplying the house from the grid so where are the losses?
> […](#)
> On 8 Dec 2023 at 22:34 +0000, Trefor Southwell ***@***.***>, wrote: In the meantime you would have to supply the home from the battery so those losses are included. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Yes this is certainly true, but in this case it doesn't apply as plan shown here starts at 82% battery.

One thing Predbat could do better is to disable the battery use (charge freeze) but I don't know if a) it's enabled in this setup and b) many inverters don't actually hold at zero they leak around 200w.

**Comment by springfall2008** [comment]
What version of Predbat?

**Comment by gcoan** [comment]
> One thing Predbat could do better is to disable the battery use (charge freeze) but I don't know if in this setup it leaks or if it really holds at 0 discharge.

I wanted to also highlight #435 where predbat doesn't set the battery reserve so "hold charging" plans/statii actually result in the battery discharging.  This then caused oscillation of charging and discharging, swapping over every 5 minutes in a 30 minute slot

**Comment by fboundy** [comment]
![image](https://github.com/springfall2008/batpred/assets/5152701/1e6618a0-5efe-4532-a212-0b47ecb627d8)

Much the same today. Predbat wants to charge much earlier. You can see what happens in the Calibration chart bottom right. When it gets past the peak it resets the thresholds and all makes sense.

**Comment by springfall2008** [comment]
> Much the same today. Predbat wants to charge much earlier. You can see what happens in the Calibration chart bottom right. When it gets past the peak it resets the thresholds and all makes sense.

I did just make a new release which may or may not help, it would be good if you can try it: https://github.com/springfall2008/batpred/releases/tag/v7.14.6

I wouldn't read much into the threshold, if it's on automatic mode then the threshold value is representing the maximum charge price Predbat has used rather than impacting the end result.

**Comment by fboundy** [comment]
Much better so far with 7.14.6

h12 and h8 are much more stable whereas previously they were flip-flopping. 

Now pretty much identical to my algorithm - I would expect mine to look marginally better on the calibration plot as it is controlling the inverter but the difference is minimal. I'm also just using the Solcast mid with none of the 10% which accounts for the Base difference

![image](https://github.com/springfall2008/batpred/assets/5152701/cc1d072b-12ae-4095-a459-dca33e29b851)

**Comment by springfall2008** [comment]
> Much better so far with 7.14.6
> 
> h12 and h8 are much more stable whereas previously they were flip-flopping.
> 
> Now pretty much identical to my algorithm - I would expect mine to look marginally better on the calibration plot as it is controlling the inverter but the difference is minimal. I'm also just using the Solcast mid with none of the 10% which accounts for the Base difference

Thanks for testing, that's good to know :)

The main thing I'm trying to achieve with Predbat is that the tuning is done to the inverter model rather than with assumed knowledge. It means things like clipping and export limits will be accounted for rather than just unit rates, of course it makes things more complication as a result also.
