### ISSUE TITLE
Battery constant charging/discharging

### ISSUE THREAD

**Issue by slopemad** [springfall2008/batpred#443]
In some circumstances, when the Target SOC is equal to the Battery Power Reserve (in my example here, the Target SOC and Battery Power Reserve were both 88%, and Predbat status was 'Charging'), once the battery reached that SOC, it was constantly charging and discharging (i.e. is reached Target SOC, and so stopped charging, and started discharging a little, then started charging, then started discharging, constantly), per this chart...  

<img width="1190" alt="Screenshot 2023-12-09 at 09 58 17" src="https://github.com/springfall2008/batpred/assets/118896510/aaae2b6c-f53f-4415-aae2-1cfaf093bc98">

I can't imagine this is particularly good for battery cycles.  Might it be better in a charging status, to set the reserve to 100, so that the battery doesn't start doing regular charge/discharge cycles once it reaches the target SOC?

**Comment by springfall2008** [comment]
I think this maybe fixed based on the linked ticket, feel free to open a new issue if it's not.
