### ISSUE TITLE
Hold charges appearing in plan with losses and cycle set to 0

### ISSUE THREAD

**Issue by AGLAISTER** [springfall2008/batpred#454]
I have adjusted my settings to avoid predbat causing a charge hold but I'm still getting charge holds even though as advised I've set 
Battery Loss Charge = 0
Battery Loss Discharge = 0
Inverter Loss = 0
Metric Battery Cycle cost = 0

The example below is not the best but illustrates it is happening - I have mainly been seeing it in a morning at breakfast time

Images and 

![image](https://github.com/springfall2008/batpred/assets/141528175/6ea62e31-f769-453f-ad8b-eb4cbc544fdf)

![image](https://github.com/springfall2008/batpred/assets/141528175/d73d81bc-5ba1-4113-8276-c75c7ca4c97b)

![image](https://github.com/springfall2008/batpred/assets/141528175/e26e6709-e527-43e9-b1da-13a5b5d53c39)

Logs attached

[appdaemon.log](https://github.com/springfall2008/batpred/files/13650690/appdaemon.log)

[appdaemon 1.log](https://github.com/springfall2008/batpred/files/13650692/appdaemon.1.log)

**Comment by springfall2008** [comment]
This is probably due to the Best Soc keep at 1.5 meaning the hold is required to avoid getting below that. Try a keep of 0 or 0.5

**Comment by AGLAISTER** [comment]
1.5/9.5 gives 15% so and when its holding charge the plan is showing 19%
I had best soc at 1.5 to keep enough charge going in for poor solar days as i was seeing it under plan for the next day.
I've reduced to 1 for now and that has removed that SoC keep
I'll monitor things and see what happens - I'll close this for now

Reducing in to 1 did remove the hold charge, I had it at 1.5 to ensure I was getting full charge overnight on poor solar days

**Comment by springfall2008** [comment]
Soc keep is ignored for the next 4 hours which is why the slot disappears at you get closer, it maybe fine to leave it once you know why

**Comment by AGLAISTER** [comment]
I had another occurrence of charge being held this morning even with all parameters set that I understand should be preventing charge hold

[appdaemon.log](https://github.com/springfall2008/batpred/files/13673733/appdaemon.log)
[appdaemon 1.log](https://github.com/springfall2008/batpred/files/13673734/appdaemon.1.log)


![Screenshot_2023-12-14-06-59-18-04_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/21bac54b-b04f-406c-9225-190f9e73b877)
![Screenshot_2023-12-14-06-59-35-54_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/0bfc7aa8-d70e-4e93-8502-74570d9477dd)
![Screenshot_2023-12-14-07-00-13-39_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/6dfaf64b-353d-47af-9990-86c668719032)
![Screenshot_2023-12-14-07-00-23-73_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/891e00f5-4494-4cab-bd9c-c371b2015731)
![Screenshot_2023-12-14-07-00-49-57_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/ff445698-5921-49f7-8324-41619496ac2f)
![Screenshot_2023-12-14-07-12-15-86_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/a2b91edd-1c30-4114-b777-d315402afe01)
![Screenshot_2023-12-14-07-12-32-19_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/22c7a365-7c2e-4d69-b363-eb69f7f410ce)
![Screenshot_2023-12-14-07-12-44-23_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/14d3a24d-684b-471d-ad87-58ad833b066c)
![Screenshot_2023-12-14-07-13-38-00_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/35c5c71b-777b-4f10-9a55-874569f2f80d)
![Screenshot_2023-12-14-07-13-51-64_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/64f5844e-6352-4a9a-b41e-ad715528792e)
![Screenshot_2023-12-14-07-14-02-08_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/141528175/375df431-df22-4b2c-8cea-25fb967725d2)

Note I'm still on v7.13.23 as I haven't had the right time/opportunity to update with the breaking change in v7.14

**Comment by AGLAISTER** [comment]
got another occurrence today of charge holding.

![image](https://github.com/springfall2008/batpred/assets/141528175/6c1d4e7c-9a58-4f6e-850b-c2e76e2a18e3)
![image](https://github.com/springfall2008/batpred/assets/141528175/30e606be-2f14-43b4-947f-a337073d4fa0)

settings are unchanged except that I pushed up load scaling yesterday to ensure I got full charge overnight due to low prices.

**Comment by springfall2008** [comment]
Closing this as the model was re-written since. Please open a new ticket for any new issues
