### ISSUE TITLE
Freeze charging target in alert msg sometimes wrong

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#457]
Splitting this out from #449 as it's a separate issue,

Have seen twice now examples of the Freeze Charge alert notification having a 4% soc target, not the correct target per the plan and the inverter settings:

![image](https://github.com/springfall2008/batpred/assets/142018870/476703f8-5341-4473-a62f-905a5222b5ef)
![image](https://github.com/springfall2008/batpred/assets/142018870/39378f26-18a8-4e2a-a7c7-613121dc37d2)
![image](https://github.com/springfall2008/batpred/assets/142018870/71322cd8-3e3b-4264-996d-ff1f8353fa72)

**Comment by gcoan** [comment]
Yesterday's example of the same issue (moved from #449)

13:30, plan says freeze charging 87% limit and the inverter is setup correctly to do this 
![image](https://github.com/springfall2008/batpred/assets/142018870/ac050e68-e9f6-4534-826b-e8a2bb3706b1)
![image](https://github.com/springfall2008/batpred/assets/142018870/a64e5dec-1676-49a2-b756-a2697f147e1a)
![image](https://github.com/springfall2008/batpred/assets/142018870/8cd566d8-7c69-4bc1-9601-fc24fa50efc5)

But the alert I got was "freeze charging target 4%" - probably just an error in the alert message?
![image](https://github.com/springfall2008/batpred/assets/142018870/aed9c693-9880-40ee-9319-dc2a15384ced)

**Comment by springfall2008** [comment]
Fixed in: https://github.com/springfall2008/batpred/commit/e53f8c7e59368aca97547da1ecff9212a3f6aa90

**Comment by gcoan** [comment]
I downloaded the latest main, its d423cfe though?

**Comment by springfall2008** [comment]
Did the fix work?

**Comment by gcoan** [comment]
> Did the fix work?

I believe so.  I've received lots of freeze charging notifications and looking through them, none of them say 4%, they all say different soc target values; 98, 100, 51, etc

Thanks
