### ISSUE TITLE
Plan explanations

### ISSUE THREAD

**Issue by blastehh** [springfall2008/batpred#473]
Is there any documentation explaining what "Charge", "Discharge", "HoldChrg", "NoCharge" means? The first 2 are obvious, but the last 2 are not.

Maybe a glossary of terms that the app uses would be helpful.

Example of what I'm seeing right now, I don't know the difference between HoldChrg and NoCharge
![image](https://github.com/springfall2008/batpred/assets/8324677/1c77a9c2-d01f-42ed-a860-3398cb254c77)

**Comment by springfall2008** [comment]
It's on this page:https://springfall2008.github.io/batpred/what-does-predbat-do/
