### ISSUE TITLE
Beta version on 'main' for testing

### ISSUE THREAD

**Issue by springfall2008** [springfall2008/batpred#475]
I made too many changes on main so they really need testing.

- When the plan hours < 48 hours now (e.g. 24) the blackout period is calculated based on the next low rate charge slot and not any slots
- Added load_scaling10 to allow the worst case scenario to include higher load - default 1.1
  Here load_scaling10 will skew the house load in the 10% scenario to try to get Predbat to see that you might use more energy than expected as well as have a worse solar day.

* Fix charge freeze to disable the charge window when holding using reserve
* Put some more options into expert mode
* Try to stop charge window from being disabled when it doesn't need to be

**Comment by gcoan** [comment]
I'm installing it now Trefor and will see how it goes.

Don't quite understand how the new load scaling works alongside the existing and why I might or might not want to change it.  Thanks

**Comment by springfall2008** [comment]
> I'm installing it now Trefor and will see how it goes.
> 
> Don't quite understand how the new load scaling works alongside the existing and why I might or might not want to change it. Thanks

So it will scale the load used in the 10% calculation, it kind of makes the best10 into a worst case line

**Comment by gcoan** [comment]
I installed the beta version just after 1pm and for the first part of the afternoon the plan was to charge the battery which occurred fine

Between 1:35 and 3:30 it swapped a couple of times between hold charge and freeze charge

The freeze charge I saw it doing was working fine 
![image](https://github.com/springfall2008/batpred/assets/142018870/f1f21eb9-9ac5-4aff-aecf-5ac0ab838bc8)

The plan at 3:05 showed what appeared to be just normal Eco discharging in the saving session period from 5-6, which looked wrong
![image](https://github.com/springfall2008/batpred/assets/142018870/947683e4-0e7f-4fb8-b56e-e26078bfcc37)

But by 4:30 the plan had changed to be a proper forced discharge (as expected) and as you can see the inverter was just changing to idle in the peak, ahead of the saving session 
![image](https://github.com/springfall2008/batpred/assets/142018870/0a49c783-42e5-4a53-962b-cf9e177a0427)

At 5pm it started the force discharge correctly and held it force discharging to 6pm when it went into idle/Eco mode
![image](https://github.com/springfall2008/batpred/assets/142018870/043405ef-ea38-4286-a7c5-719d9af9a73c)

So other than the plan being wrong initially for the saving session, but it corrected it, it worked fine for me

**Comment by gcoan** [comment]
Are these changes in 7.14.13 or should I keep beta testing main?

**Comment by springfall2008** [comment]
Yeh unfortunately I had an issue with the gap filling and so wanted a new release, so 7.4.13 is the one to try now

**Comment by gcoan** [comment]
Ok I'll upgrade to 7.4.13

**Comment by springfall2008** [comment]
Some of these issue might relate to metric keep, which I think I might have fixed now on main.
