### ISSUE TITLE
Precharge Battery before saver session config

### ISSUE THREAD

**Issue by Bcrutt** [springfall2008/batpred#476]
Hi

I was wondering why my current setup seems not to charge the battery before a saver session, I have added some screenshots below showing my current setup when using Octopus Flux, any comments would be appreciated.

![image](https://github.com/springfall2008/batpred/assets/132393335/70e727d9-a98c-4a18-9bdf-19f5f7c51c56)
d
 
![image](https://github.com/springfall2008/batpred/assets/132393335/78475446-946a-4789-bdfe-fdf7a2b8434d)

![image](https://github.com/springfall2008/batpred/assets/132393335/2db175a4-9874-44b7-97aa-fb793248babd)

![image](https://github.com/springfall2008/batpred/assets/132393335/599fb487-f115-4cc9-a9f0-122f933e32ff)

**Comment by springfall2008** [comment]
Your rate low threshold is hard wired so it can't use the more expensive rate - if you set it to 0 then it's automatic and it can do

**Comment by Bcrutt** [comment]
Changed Low Threshold to 0

![image](https://github.com/springfall2008/batpred/assets/132393335/5fdbf544-70b9-4af7-ace1-41c28f54de4e)

Plan still not showing any sign of charging before saver session

![image](https://github.com/springfall2008/batpred/assets/132393335/dc438c2c-a1ef-4ae8-8705-c1c7b736bbbb)

Also charging on saturday am now looks like this

![image](https://github.com/springfall2008/batpred/assets/132393335/a90b59b7-8340-4928-b3ab-e817392ffd81)

I have attached the appdaemon log
Thanks
[appdaemon.log](https://github.com/springfall2008/batpred/files/13685704/appdaemon.log)

**Comment by Bcrutt** [comment]
After awhile it did start charging and then held the charge at 45%, it then changed again to this
![image](https://github.com/springfall2008/batpred/assets/132393335/a1690a0c-8e01-45fc-94be-ab9c9db9f301)

[appdaemon.log](https://github.com/springfall2008/batpred/files/13686149/appdaemon.log)

**Comment by Bcrutt** [comment]
Then changed to this
![image](https://github.com/springfall2008/batpred/assets/132393335/1f874fc9-a5d4-41e9-b328-07aa95066fb0)

**Comment by Bcrutt** [comment]
V 7.14.12

**Comment by JonathanLew1s** [comment]
The hold charge from 2pm to 4pm looked like a good plan. No point in incurring losses to charge the battery to discharge later, hold the battery at 45% and run the house load from the grid. Going into the saving session with 40% battery.
No sure why the following runs changed from that plan.

Personally, I would set the high threshold rate to 0 and enable charge freeze switch.

**Comment by Bcrutt** [comment]
I thought the plan looked ok, then on the next pass it dropped the hold charge and would have gone into the saver session with just 11% soc. So I decided to set to read only and charged from 15:00 to 16:00 and then set to charge \ discharge and it exported from 17:00 to 18:00.
The plan then showed it was going to charge next from 02:00 saturday am all the way to 16:00 Saturday pm, which I don't understand why it would do that.

![image](https://github.com/springfall2008/batpred/assets/132393335/facee42f-969c-492e-a850-3c838e2eac9a)
![image](https://github.com/springfall2008/batpred/assets/132393335/e8fdb979-3a33-46f8-b28d-da940d7dbbe2)

**Comment by springfall2008** [comment]
Maybe combine charge needs to be turned off?

**Comment by gcoan** [comment]
@Bcrutt as you are on a 3 time of tariff, once you've charged the battery overnight (starting in the cheap period and finishing in the day rate), there's no point in predbat doing anything different with the battery until the evening peak import rate when the battery starts discharging to support your load.

So I think the plan is correct.  If you look at the soc column, once the battery reaches 100% at 5am it then stays there until 4pm discharge.  Maybe from 5am to 4pm it could be labelled 'hold charge' or 'charge freeze', but its the same as charge and maintain 100%

You could look at the config options for your tariff, as Trefor says, turn combine charge off, but it is recommended to be on for Cozy/Flux type of tariffs, and I think the plan is correct anyway
https://springfall2008.github.io/batpred/configuration-guide/

Unless you have a different view what should be planned?
