### ISSUE TITLE
Metric keep doesn't really do what I want

### ISSUE THREAD

**Issue by springfall2008** [springfall2008/batpred#480]
**Describe the bug**

Metric keep is too harsh and forces charging at peak rate just to stay within keep

**Expected behavior**

Somehow try to stay above keep but without doing it just for the sake of it

**Comment by gcoan** [comment]
Agree.  I'd ideally like to keep a kW or so spare in the battery but because of just this problem, min keep causing charging in high rate periods, I ended up setting it to 0.1

**Comment by mpartington** [comment]
Agree, should aim to keep above it when setting the plan, but not at the expense of charging at peak rate if usage increases from initial prediction when letting it run flat would be more cost effective.

**Comment by springfall2008** [comment]
I think I have fixed this on main, please give it a spin when you get time

**Comment by springfall2008** [comment]
Well, I thought i had - but 3 versions later it seems better.... still on main

**Comment by springfall2008** [comment]
https://github.com/springfall2008/batpred/releases/tag/v7.14.14
