### ISSUE TITLE
Terrible plan with v7.14.14

### ISSUE THREAD

**Issue by slopemad** [springfall2008/batpred#488]
Just upgraded from 7.14.11 to 7.14.14 and the new plan is... DREADFUL!

<img width="729" alt="7.14.14" src="https://github.com/springfall2008/batpred/assets/118896510/29451866-c43a-4b86-a3e1-039eb2990d92">

appdaemon.log is here https://pastebin.com/2CuqWapS

Rolled back to 7.14.11 and got a more sensible plan.

<img width="381" alt="7.14.11" src="https://github.com/springfall2008/batpred/assets/118896510/50952ba3-46b3-4867-842a-7335f9f35c98">

The most obvious difference I can see is that under 7.14.14, the Import threshold was 12.9p, whilst with 7.14.11 it is 17.5p.

v7.14.14
2023-12-17 13:50:07.499649 INFO pred_bat: Import threshold used for optimisation was 12.9p

v7.14.11
2023-12-17 13:54:03.057272 INFO pred_bat: Import threshold used for optimisation was 17.5p

**Comment by springfall2008** [comment]
I'm struggling to reproduce what you were seeing on my system configured for Agile, but I think either putting best_soc_keep up a little higher or turning off 'calculate_fast_plan' would fix it.

**Comment by slopemad** [comment]
It's very similar to when I set best_soc_keep to zero - the entire plan disappears.  I wonder if it's related?

**Comment by springfall2008** [comment]
I think best_soc_keep should be 0.5 or above on the latest version, did you try higher numbers?

**Comment by slopemad** [comment]
I only had it set to 0.5 when on 7.4.14, but the effect of the huge drop in low threshold when I upgraded to 7.4.14 was similar to the effect of the drop in low threshold when best_soc_keep is set to zero on 7.4.11.

**Comment by springfall2008** [comment]
Yes I think so, a higher value would probably resolve the issue - it's most as I made the keep threshold less aggressive.

**Comment by slopemad** [comment]
So I had another look at this tonight, and upgraded from 7.14.11 to 7.14.15, and it went back to a substantially worse plan than the one it originally had - the low threshold went from 10.4p to 18p and the best metric (cost) went from about 100p to nearly 200p.  Similar results when I went up to 7.14.16 also, and then to 7.14.13.  And fortunately it reverted back to the lower low threshold of 10.4p and a best metric (cost) of closer to 100p when I went back to 7.14.12.

It feels like one of the changes made between 7.14.12 and 7.14.13 had a big impact on the low threshold calculation and the plan created by Predbat?

I did play around with the best soc keep, but didn't see any notable change between 0.5 (which I have it set to normally) and 1.

**Comment by slopemad** [comment]
This is the current plan with 7.14.12

<img width="655" alt="Screenshot 2023-12-19 at 20 42 47" src="https://github.com/springfall2008/batpred/assets/118896510/da60adfc-6558-4909-95bf-b290d446ba82">
<img width="747" alt="Screenshot 2023-12-19 at 20 42 12" src="https://github.com/springfall2008/batpred/assets/118896510/166808ea-e871-4215-8ba8-b56023ee939d">

And this was the plan with 7.14.15

<img width="555" alt="Screenshot 2023-12-19 at 20 29 24" src="https://github.com/springfall2008/batpred/assets/118896510/dade42a4-9722-4136-8992-a2256dc23c2c">
<img width="668" alt="Screenshot 2023-12-19 at 20 29 40" src="https://github.com/springfall2008/batpred/assets/118896510/93e5b7ea-1557-403f-a69a-cc14c6f45dd5">

**Comment by springfall2008** [comment]
As things have moved on a lot I will close this ticket, feel free to open a new one if you still have issues.
