### ISSUE TITLE
predbat instructing hold  and freeze charging when battery already empty

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#491]
**Describe the bug**
The battery became exhausted at 18:17:
![image](https://github.com/springfall2008/batpred/assets/142018870/e1db2606-2779-4b3a-9b3f-37682853cdc8)

As the rates are staying flat/bumping up and down, no further charging is planned until much later on
![image](https://github.com/springfall2008/batpred/assets/142018870/63b0fb68-576e-4a07-bc32-204c815fb262)

But Predbat keeps on instructing the inverter to hold charge, freeze charge, all of which come through as extra mobile notifications
![image](https://github.com/springfall2008/batpred/assets/142018870/48888df5-77e0-4773-b0e7-679f90cc3f27)

**Expected behavior**
Once the battery is exhausted, no further freeze charge or hold charge or change to idle instructions are made until the soc is greater than min soc.

**Predbat version**
7.14.14

**Environment details**
Gen 1 5kW hybrid, 5.2 battery
HAOS

**Log file**
[appdaemon (5).log](https://github.com/springfall2008/batpred/files/13697498/appdaemon.5.log)

**Comment by gcoan** [comment]
More of the same for the next couple of hours, swapping between Idle, Hold Charging

![image](https://github.com/springfall2008/batpred/assets/142018870/2ae6bf31-4915-447c-a809-6619168291ae)
![image](https://github.com/springfall2008/batpred/assets/142018870/1fa8122e-3508-40b6-98e5-0167f6874360)

I noticed it swaps to Idle on the :00 or :30 minutes and Hold Charging on :06 and :36 minutes so may be related to re-evaluating the plan at the start of every slot and then not a full reval every 5 minutes
[Uploading appdaemon (6).log…]()

**Comment by springfall2008** [comment]
Should be fixed now
