### ISSUE TITLE
Predbat plans to discharge the battery when its already exhausted

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#492]
**Describe the bug**
At 13:20. I can see in the plan that after the evening peak the battery is exhausted on 4%.  The evening slots 19:00-21:30 are planned to leave the house being supplied by the grid as there's no benefit to charging and discharging after losses taken into account 
![image](https://github.com/springfall2008/batpred/assets/142018870/6f6b4afa-b2d8-4922-91f9-fad06ef7444b)

But then from 22:00 predbat's plan is to discharge through to 02:00.  The battery is of course empty so none of these discharges can be executed.
[appdaemon (4).log](https://github.com/springfall2008/batpred/files/13697507/appdaemon.4.log)

Update at 19:15.
The long period of impossible discharge has shortened.  Still trying to discharge for the first hour (22:00 and 22:30) slots, but then charge in the next two before further discharging through to 02:00
![image](https://github.com/springfall2008/batpred/assets/142018870/16e2b048-c6c0-40b0-8b15-adf94abfb4a1)

[appdaemon (5).log](https://github.com/springfall2008/batpred/files/13697508/appdaemon.5.log)

**Expected behavior**
When soc is 4% (or min soc), predbat doesn't plan to discharge the battery as there's no soc to discharge.  Instead remain on idle with the house being grid supplied (as is planned from 19:30 to 21:30 slots)

**Predbat version**
7.14.14

**Environment details**
Gen 1 Hybrid, 5.2kW battery, HAOS

**Comment by gcoan** [comment]
Predbat still doing this unfortunately. Here's an example from today where it's trying to discharge from 20:30-22:00 when the battery is clearly empty and no solar charging.

![image](https://github.com/springfall2008/batpred/assets/142018870/8184a644-f10c-4adb-95bb-342a20ee9f02)

**Comment by springfall2008** [comment]
Fixed now, please re-open if there is a new issue
