### ISSUE TITLE
Batpred plan not optimised for charge when cheap

### ISSUE THREAD

**Issue by onetoomany** [springfall2008/batpred#497]
<img width="416" alt="image" src="https://github.com/springfall2008/batpred/assets/1380470/5187fd2e-d7b0-4213-b191-cf8a1cd60ca6">

There are a few areas of my Batpred plan that confuse me.
1. There is a powerup today at 3pm. However, the plan has the battery charging right up until 2.30pm. I'd have expected that it would either stop charging around 11am or even tactically charge, such that it glides into the powerup nearly empty.
2. At 10.30pm, prices today are 8p. Again, I'm charging from 8pm at 16p such that my battery is already nearly full for this cheap rate.
3. Even ignoring the powerup, prices this morning vary between 15p and 19p. I'm still charging at 19p, thereby sitting on a full battery at 15p - even with battery losses, it would make sense to discharge at 19p rather than charge.

**Comment by gcoan** [comment]
@onetoomany I too have a power up event today, and by comparison my predbat has done what I'd expect it to do.  The battery filled up overnight and has discharged this morning. There's some spurious hold charges #491 but other than that, its not charging the battery until the power up period, at 8:30pm to get over a 9pm spike, and then later tonight in the cheap rate
![image](https://github.com/springfall2008/batpred/assets/142018870/f48e28d8-ea41-44ce-bbcb-9a94a351b506)

My load (ASHP) is much higher than yours, but must be something different in the way our predbat's are configured.
Here's my settings if you can see any key differences:
![image](https://github.com/springfall2008/batpred/assets/142018870/143c99f5-062c-4125-af2c-9eb44fcc6488)
![image](https://github.com/springfall2008/batpred/assets/142018870/e04eb886-1349-476b-b766-7f23bc33973e)
![image](https://github.com/springfall2008/batpred/assets/142018870/1538146f-a3fc-43b0-bfae-05c2d8951f73)

**Comment by gcoan** [comment]
@onetoomany I assume you don't have an export tariff or could export and refill for free

**Comment by springfall2008** [comment]
@onetoomany can you post your log?

**Comment by onetoomany** [comment]
> @onetoomany I assume you don't have an export tariff or could export and refill for free

Correct - no export tariff as mine is a DIY install so I don't have MCS.
My load is probably  slightly lower than I'd expect - I usually use 15kw in a day, so I'd expect an average of 0.25kwh in each period and 1kwh in the three periods at dinner time when I have the oven on.

**Comment by springfall2008** [comment]
Curious, I think turning off combine_charge might help

**Comment by onetoomany** [comment]
we've another powerup tomorrow, so I'll turn it off and see what happens

**Comment by onetoomany** [comment]
The plan is definitely looking better for tomorrow now that I've turned off combine charge.

Only remaining niggle with the plan is a target SOC% (as low as 6%) drops below the "reserve" value set in apps.yaml - in my case 20%; at least, that is what I assume the "reserve" value is for. My inverter's current firmware, for some reason, doesn't allow my battery to go flatter than 20% at the moment.

<img width="407" alt="image" src="https://github.com/springfall2008/batpred/assets/1380470/a06baa6e-17e0-4d3b-bda2-ac256cf4e172">

Its also interesting how the powerups skew the predicted load based on my behaviour.

**Comment by onetoomany** [comment]
<img width="413" alt="image" src="https://github.com/springfall2008/batpred/assets/1380470/7bd75aea-de25-4e4e-9a2a-45aa0fd7ffab">

I've still got Predbat doing some confusing behaviour - charging up now at 16p / 17p only to discharge when its 2p cheaper in an hour. The battery is nearly full, so I don't need a topup.

**Comment by springfall2008** [comment]
How did you set the reserve value, it should be taken into account but maybe a bug in non-GE inverter setup?

**Comment by onetoomany** [comment]
From apps.yaml
```
  battery_power:
    - sensor.sofar_inverter_battery_power
  pv_power:
    - sensor.sofar_solar_power
  load_power:
    - sensor.sofar_house_consumption_power
  soc_kw:
    - sensor.sofar_battery_energy
  soc_max:
    - input_number.sofar_battery_max_charge
  charge_limit:
   - 100
  reserve:
    - 20
  scheduled_charge_enable:
   - off
  scheduled_discharge_enable:
   - off
```

**Comment by onetoomany** [comment]
Perfect! That works.
