### ISSUE TITLE
Optimal Charge Slot Determination

### ISSUE THREAD

**Issue by JonathanLew1s** [springfall2008/batpred#509]
**Describe the bug**

There are 6 negative slots overnight, predbat is chosing to discharge in 3 of them despite battery SOC not being at maximum and to compound there is a choice to recharge later at rate, that is 9p higher than the lowest slot.

**Expected behavior**
In this example, 23:00 could be a discharge slot reducing SOC by 8.5% and freeing enough headroom to use all the negative rate slots to import. Allowing a later discharge to recover costs and bring SOC down to planned demand for tomorrow. That 8.5% charge at 23:00 is simply not needed to cover the demand, maintain SOC or optimise cost.
21:30 I could also argue shouldn't be such a deep charge, to 16%, when only .4kWh/2% is required to bridge the 22:00 to 22:30 slot. SOC keep is 0.1 so only maintaining a 4% reserve.

**Predbat version**

7.14.18

**Environment details**

- 5kWh Hybrid Gen 2, 2 x 9.5kWh batteries
- Docker

**Screenshots**

![image](https://github.com/springfall2008/batpred/assets/34936213/2f0d6759-15a6-498b-b274-7e6e38c918b1)
![image](https://github.com/springfall2008/batpred/assets/34936213/29a682ac-faa8-4311-acc1-3ee42656524f)
![image](https://github.com/springfall2008/batpred/assets/34936213/ae940d43-c1f6-49b2-b209-8fdb39591e3f)
![image](https://github.com/springfall2008/batpred/assets/34936213/4cb18f72-953a-46ba-9643-7f918f77d4de)

**Log file**
[_appdaemon_logs-7.txt](https://github.com/springfall2008/batpred/files/13732534/_appdaemon_logs-7.txt)

**Comment by springfall2008** [comment]
I just pushed a version to main to address this exact issue, would you mind trying it if you get time?

**Comment by JonathanLew1s** [comment]
Looks much better, for the negative slots.

Still challenge that the 21:30 to 18% is way too high and also not possible. 30 minute max charge would be around 8% on a 3.6kWh charge rate. It's aiming for 14%

![image](https://github.com/springfall2008/batpred/assets/34936213/d44c4c56-de58-4fe6-9458-5368e8d4363a)

**Comment by springfall2008** [comment]
I wouldn’t read too much into the target % as it’s clipped with some margin, it says it goes from 5% to 14% which seems okay doesn’t it?

**Comment by JonathanLew1s** [comment]
Agree.

I think 22:30 to 00:00 is still a little janky, 22:30 could be a full charge 23:00 a full discharge. 23:30 is close to 1p cheaper than 00:00.

It's all fine margins, and small gains. I'm happy now that the negative slots are fully leveraged. Plan comes out 4p worse off but with an SOC 14% higher. 

Thanks for the quick reply.

**Comment by gcoan** [comment]
@springfall2008 whats changed in the main release?

TBH my plan for tonight is quite reasonable already.  Yes it's trying to discharge an already empty battery until 2am when it could be charging and discharging, but for the pence gained I'm not bothered and it is more battery cycles.

Charges in 5 of the 6 slots, lets the soc drop in the 5th, then a bit of charging and discharging to generate income.

Fairly ok

![image](https://github.com/springfall2008/batpred/assets/142018870/89903afa-71b7-4bf9-8eba-f5458627a1af)

**Comment by springfall2008** [comment]
The change on main (now https://github.com/springfall2008/batpred/releases/tag/v7.14.19) when selecting export slots all at the same export rate will select from those with the most expensive import rates first. Not sure if it will change your plan to be honest.

**Comment by gcoan** [comment]
OK, I've installed 7.14.19 now.  Will just have to re-apply my pending changes to the code.

The new plan is the same in the negative period, but has introduced a bit more charge/discharge this side of midnight for a few pence extra income
![image](https://github.com/springfall2008/batpred/assets/142018870/3f17fb81-9ff7-4d45-9676-3ed425742db1)
