### ISSUE TITLE
PV shown in plan (presumably calculation too) is wrong

### ISSUE THREAD

**Issue by Philhews** [springfall2008/batpred#511]
**Describe the bug**
The expected PV value is wrong for the time period causing an incorrect expectation. Screenshot show 8.30 this morning with PV forecast even on the 90 value to be less than 0.1 but the plan is showing 0.18. Not a big difference here but proportionally it is. 

**Expected behavior**
PV value in the plan should be what solcast is predicting (or maybe modified based on the 10% weight I don't know exactly what it's supposed to be) 

**Predbat version**

7.14.15

**Environment details**

- Gen 2 3.6 hybrid. 9.5kwh battery
- standard HAOS

**Screenshots**
![Screenshot_2023-12-21-08-15-16-80_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/d6a68c46-5469-4f99-b1da-e03e2f2d31e6)
![Screenshot_2023-12-21-08-14-56-91_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/1ad92db0-636d-4efd-a850-1faf074999d2)

**Comment by springfall2008** [comment]
Do you have the log for that period, or if not the latest log?

**Comment by Philhews** [comment]
Yes, though I was struggling to work out how to lift the file from my phone but at worst I'll copy the section out when I get a second.

**Comment by Philhews** [comment]
[appdaemon.log](https://github.com/springfall2008/batpred/files/13743912/appdaemon.log)

Latest log file, this mornings ones are no longer available

**Comment by Philhews** [comment]
Will include tomorrow morning though which the plan shows 0.02 when all of the estimates for that half hour are essentially 0.00
![Screenshot_2023-12-21-16-32-45-14_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/370aa9a3-a209-4afd-8850-ef96eafda7f8)
![Screenshot_2023-12-21-16-33-18-56_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/a77e29dd-6882-4f69-91aa-642649ff7022)

**Comment by springfall2008** [comment]
Can you double check your input_number.pv_scaling setting in case it's set wrongly?

It's worth noting the values you get from solcast are actually not for the half hour but the power (in watts) so actually they are more like hourly figures - this makes the difference even worse. I did check my system and I don't see this issue.

Are all figures too big or only these low ones?

**Comment by Philhews** [comment]
Pv scaling is set to 1.

I can't work out how predbat is getting to its numbers, they seem to not follow the same formula from the pv10, 50 and 90 values for each slot at all. Plan and solcast for daylight tomorrow attached along with l a log file. 

![Screenshot_2023-12-22-13-37-42-90_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/6fef0ffd-503a-4578-98c5-6fae753edba8)
![Screenshot_2023-12-22-13-38-26-01_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/daa12d70-3ac7-4d23-ad45-57e515c24e59)
![Screenshot_2023-12-22-13-38-35-61_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/7cdebc86-dcda-4f93-b948-32fa578ce3ed)
![Screenshot_2023-12-22-13-38-40-92_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/d132fa6f-322d-4970-adfb-c742470227ea)
![Screenshot_2023-12-22-13-38-50-95_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/a985e23f-81f1-4aba-b518-1ab30bce6dc7)
[appdaemon.log](https://github.com/springfall2008/batpred/files/13752889/appdaemon.log)

**Comment by Philhews** [comment]
Metric 10 weight is 0.2 if that matters.

**Comment by Philhews** [comment]
I wonder if there's a time shift going on somehow, I have 0.02 in the plan for the 7:30 slot this morning where all values in the solcast slot are 0

**Comment by springfall2008** [comment]
Hopefully fixed in the latest release

**Comment by Philhews** [comment]
Yep, looks better, thanks

**Comment by springfall2008** [comment]
Hopefully fixed this in release now: https://github.com/springfall2008/batpred/releases/tag/v7.14.25
