### ISSUE TITLE
dashboard.yaml not updated

### ISSUE THREAD

**Issue by markbw999** [springfall2008/batpred#531]
Hi Trefor, I just up dated to v7.14.24 and noticed the dashboard is missing some entities. I went to update it from the normal location but it hasn't been updated since 14 Dec. Has it moved somewhere else?
Thanks, Mark

**Comment by springfall2008** [comment]
It probably got moved to the homeassistant directory ?

**Comment by markbw999** [comment]
Thanks. Found it in config alongside the main HA yaml files.
