### ISSUE TITLE
Charging limited to 2500w

### ISSUE THREAD

**Issue by dandwhelan** [springfall2008/batpred#534]
**Describe the bug**

On my givenergy my charge rate is set to 3600 as I'm on a 5k hybrid charger gen 2.
Yet for some reason it seems to only charge at 2500w. 
![Screenshot_20231226_142603_Home Assistant](https://github.com/springfall2008/batpred/assets/79152287/264b5675-d320-4583-916a-9dc0255ac8d6)

![Screenshot_20231226_142843_Home Assistant](https://github.com/springfall2008/batpred/assets/79152287/012d0d98-c9aa-4ea4-b67f-62a2b196fd7e)
![Screenshot_20231226_142644_Home Assistant](https://github.com/springfall2008/batpred/assets/79152287/ccecbaaf-08c7-4b70-a62e-51fe4294cffc)

**Expected behavior**
I've set the charge limit to 3600w as a precaution as it still only charged at 2500w.

**Predbat version**

Latest 

**Environment details**

- Inverter and battery setup
H5 g2. 8.2kw battery 
- Standard HAOS installer or Docker
Haos standard
- Anything else?

**Comment by springfall2008** [comment]
Can you post a log please, at any time would do as the inverter details are logged?

**Comment by dandwhelan** [comment]
[appdaemon.zip](https://github.com/springfall2008/batpred/files/13773586/appdaemon.zip)
^^ latest log attached

**Comment by dandwhelan** [comment]
I can see a few 

New Inverter 0 with soc_max 8.19 kWh nominal_capacity 8.19 kWh battery rate raw 3600.0 w charge rate 3.6 kW
[appdaemon.log.1.zip](https://github.com/springfall2008/batpred/files/13773596/appdaemon.log.1.zip)

In this log...

**Comment by springfall2008** [comment]
It seems Predbat sees 3600w and your charge rate register is set to 3600 so I don’t think this is Predbat related.

**Comment by dandwhelan** [comment]
Weird. I'll reset my settings on giv and set the charge mode to solar+grid.
I'll let you know how it goes.

**Comment by dandwhelan** [comment]
Last night it seems to have sorted itself out... odd....

Did a few chargers at 2700w and then 3500w

![image](https://github.com/springfall2008/batpred/assets/79152287/79452cfc-1000-4436-8077-3778152c1ae4)
