### ISSUE TITLE
Unnecessary discharging then recharge at higher rate

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#536]
**Describe the bug**
Predbat has been very reliable of late, coping and executing extremely well in the power up and negative agile periods we've had over Christmas.
But this morning at 9:51 the battery was nearly full but Predbat wanted to discharge it to empty at 16.93 export, only then to have to recharge the battery at 16.54-17.64 to then get me through the peak.
This can't have been cost effective.

I turned predbat into read only, stopped the discharge, and then a period of time later was able to turn predbat back on when the plan had evolved to now keep the charge.

**Expected behavior**
Battery held at same level, not discharged until the peak.

**Predbat version**
7.4.22

**Environment details**
Gen 1 hybrid, 5.2 battery.  HAOS.

**Screenshots**
At 9:51
![image](https://github.com/springfall2008/batpred/assets/142018870/ae0ea0bd-e5ff-4bef-b927-036b20c41045)

![image](https://github.com/springfall2008/batpred/assets/142018870/8bbeab49-8a2e-41de-9b07-efcc39d6adba)
![image](https://github.com/springfall2008/batpred/assets/142018870/1d14fcef-2677-4274-9bd1-bea60d6caa30)
![image](https://github.com/springfall2008/batpred/assets/142018870/2d35f234-a62d-416e-924f-e725fcb8dee2)

At 11:11 the plan was now correct:
![image](https://github.com/springfall2008/batpred/assets/142018870/510786c2-756c-448b-b440-d15d90ccf61b)

**Log file**
Looking at the logfile, the 9:05, 9:10, ... 9:25 plans all have no discharging planned as does the run at 9:30.
Then in optimisation at the end of the 9:30 run, in the logfile at 9:31:39 a discharge window is planned for 9:30-11:31.  Predbat switches to discharging and keeps trying to discharge I think until 10:50 when the plan changes to retaining the charge.
[appdaemon.log.2.txt](https://github.com/springfall2008/batpred/files/13772701/appdaemon.log.2.txt)

**Comment by springfall2008** [comment]
I think it's a little marginal with your loss settings of only 4% and no inverter loss. I'd suggest setting an inverter loss of say 4% or a non-zero metric battery cycle (1p or 2p)

**Comment by gcoan** [comment]
> I think it's a little marginal with your loss settings of only 4% and no inverter loss. I'd suggest setting an inverter loss of say 4% or a non-zero metric battery cycle (1p or 2p)

My loss settings are 5% charge and 5% discharge, no inverter loss.

The charge period was planned from 12:30-16:00 (but would finish at around 15:00 when soc reaches 100%).  But in that period, only 12:30 and 13:30 (both at 16.54p) is the import rate lower than the export rate being achieved (if we totally ignore losses).  For all the other periods the import rate is higher than the achieved export rate.

So I don't think its just down to my loss settings.

**Comment by springfall2008** [comment]
I think I see why this happened, at the point the export was picked the plan didn't have a charge afterwards, the charge was added later in the calculation and the discharge isn't removed. I'll have another look as it maybe tweakable

**Comment by gcoan** [comment]
> I think I see why this happened, at the point the export was picked the plan didn't have a charge afterwards, the charge was added later in the calculation and the discharge isn't removed. I'll have another look as it maybe tweakable

Great, thanks.  It sounds quite complicated with these multiple passes, optimisations and things getting added at different stages.  It has pretty much otherwise been fine with Predbat, the plans look sensible enough, just this time it wasn't

**Comment by springfall2008** [comment]
I push some tweaks to main that may or may not make it better, worth a try if you get time.

Yeh it's too complex, I wish I had a simpler solution. I think fboundy was convinced it could be done using a set algorithm of buy/sell prices but every time I go through that idea it falls down on the edge cases.

**Comment by gcoan** [comment]
Ages old, code has moved on now
