### ISSUE TITLE
Switch to Youtube for video hosting

### ISSUE THREAD

**Issue by springfall2008** [springfall2008/batpred#553]
Just a heads up, I'm planning to move all the videos to Youtube shortly, mostly as Loom is a paid for plan and I don't really need to keep it active.

I'd made a start but hit my upload limit for the day.

https://www.youtube.com/channel/UCr3eWnHExUYFi4-8ZUGfNJQ

I'll create a few playlists for commonly needed videos also.

**Comment by gcoan** [comment]
Makes sense.
