### ISSUE TITLE
Exposing Import Optimization threshold as an entity/helper 

### ISSUE THREAD

**Issue by AGLAISTER** [springfall2008/batpred#554]
**Is your feature request related to a problem? Please describe.**
When there is plunge pricing I pretty much always set my load scaling to 1.5 to maximize import, then as the rates increase I reduce the load scaling to avoid charging too much

**Describe the solution you'd like**
I would like to be able to automatically set load scaling based on the optimization threshold
So if the import optimisation threshold could be exposed externally then I could set up my own automation to decide when to increase and decrease the load scaling input

**Comment by springfall2008** [comment]
I think you want 'predbat.rates' there is an attribute called 'threshold'  and also 'min', 'max' and 'average' which give data on the upcoming rates.

However I'm not sure this is a good thing to do, it maybe should you set load_scaling10 higher and adjust the pv10% threshold instead

**Comment by AGLAISTER** [comment]
Hi Trefor,

Thanks for the information.
Load Scaling PV10% is currently set to 1.1 and pv scaling to 1.05

When I've had issues with the plan not reacting to input rates before the advice has always been to increase load scaling so this was why I asked how I could automate this
