### ISSUE TITLE
select.predbat_update entity disappeared from dashboard

### ISSUE THREAD

**Issue by Dave-Parry** [springfall2008/batpred#561]
I added the dashboard.yaml file to a card on my dashboard and all was well, but now select.predbat_update is reported as not available.
On searching it's not listed as an entity and is not now in the yaml file. It must have been there before. Could this have been because predbat did an auto update to v7.14.29?

**Comment by Dave-Parry** [comment]
Also noticed I now don't have the Auto update toggle either.
<img width="531" alt="Screenshot 2023-12-31 at 17 25 09" src="https://github.com/springfall2008/batpred/assets/9755612/f3475675-2975-4a37-a09a-7079c8300a60">

**Comment by Dave-Parry** [comment]
Closed by mistake

**Comment by springfall2008** [comment]
What version are you running, it's saying .29 is the latest but maybe you are on an older version that doesn't have this feature?

**Comment by Dave-Parry** [comment]
It said I was on 29 but I think I saw v21 listed somewhere (I think in appdaemon logs maybe?) just seen a update to 30 which is loading and I seem to have the update sensor now listed.

**Comment by Dave-Parry** [comment]
That seems to have worked. Have both the entities that were missing. Thank you.
