### ISSUE TITLE
Car Charging SOC - Manual SOC Update

### ISSUE THREAD

**Issue by dandwhelan** [springfall2008/batpred#568]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I want to tell Predbat not to check my state of charge after it's updated, as I have a user input SOC. 

I've setup HA/Predbat to charge the car using the cheap slots. The future cheap slots were ignored once the charging started because I assumed it was looking for a SOC change. So the car just keeps charging until it's full. 

**Describe alternatives you've considered**

I've noticed on Predbat that it does calculate the estimated Kws it will be putting into the car. Maybe when the manual SOC is set it uses the estimated KW's? 

**Additional context**

I own an MG 4, which doesn't have feasible integration into Homeassistant. I have created a few helpers in HA which I manually enter the cars SOC. I've also created one for the charge limit and made a toggle when the car is plugged in. In Predbat, I've pointed the configuration on predbat to a manually updated helper. I have no other way to get the SOC from the MG unless.

**Comment by springfall2008** [comment]
Please can you test the version on 'main' which contains this feature, if you turn on switch.predbat_car_charging_manual_soc then Predbat will create input_number.car_charging_manual_soc_kwh which will be your cars current charge level. You need to set this in kWh manually before a charge but Predbat _should_ increment it during a charge session. I've not tested it myself fully so let me know.

**Comment by dandwhelan** [comment]
Thanks for looking at this so quickly. I'll try it out tonight. Should I hash out the old soc input on the app.yaml file now this had been enabled. 

![Screenshot_20240103_065528_Home Assistant~2](https://github.com/springfall2008/batpred/assets/79152287/a64a22aa-da12-4d61-8f6e-ce3a0bc1a9e9)
![Screenshot_20240103_065826_Home Assistant](https://github.com/springfall2008/batpred/assets/79152287/5f26e6e8-d723-4b12-827a-c9dc17a07307)

**Comment by springfall2008** [comment]
The old soc in apps.yaml will be ignored but you can remove it if you like

**Comment by dandwhelan** [comment]
I have the car soc set to 72 and target is 80. The number of kw planned overnight doesn't look right. I'm not sure why it says disabled for the soc... 
![Screenshot_20240103_215132_Home Assistant](https://github.com/springfall2008/batpred/assets/79152287/ccf2d77b-11c3-4152-ad94-27bada8558a0)
[apps (1).txt](https://github.com/springfall2008/batpred/files/13823781/apps.1.txt)
[appdaemon.log](https://github.com/springfall2008/batpred/files/13823782/appdaemon.log)

**Comment by springfall2008** [comment]
The manual soc number is in kWh and the battery size is kWh but the target is in %

**Comment by dandwhelan** [comment]
![Screenshot_20240103_221052_Home Assistant](https://github.com/springfall2008/batpred/assets/79152287/fe956c67-18e6-4554-9fe6-7e3f4cc2bd0d)
Ahhh yes my mistake. I got my calculator out and the car kws charging looks better. I'll report back on the morning how it went.

**Comment by dandwhelan** [comment]
That worked a treat. Thanks a lot.
![Screenshot_20240104_074109_Home Assistant](https://github.com/springfall2008/batpred/assets/79152287/ba1b75fc-cea0-4458-b53b-4f3139557b8a)
 I'm happy you added this feature.
