### ISSUE TITLE
Freeze charge buffer when PV is big

### ISSUE THREAD

**Issue by naltsta** [springfall2008/batpred#582]
**Is your feature request related to a problem? Please describe.**
Both PV and load are variable during each half hour slot. At times load is greater than PV even though total load for the half hour slot is much smaller than total PV

**Describe the solution you'd like**
Some kind of buffer when PV for a lot is greater than load for a slot that makes the inverter idle rather than freeze charge unless something like 2% below the freeze charge SOC

**Describe alternatives you've considered**

**Additional context**
Right now I've just put the kettle on and i'm drawing form the grid. In 2 minutes I'll be exporting again.

**Comment by springfall2008** [comment]
I think this is fixed now with the load divergence model

Old ticket, closing for now. Feel free to open a new ticket on the latest version if still an issue
