### ISSUE TITLE
car_charging_limit overwrites octopus intelligent vehicle charging details

### ISSUE THREAD

**Issue by tim-mawson** [springfall2008/batpred#6]
https://github.com/springfall2008/batpred/blob/0713c71b6b00f4da6de4ca5daf9044711b357f23/predbat.py#L1792

The `car_charge_limit` is read from `app.yaml`, but overwrites the charge limit read from the octopus intelligent details. Probably want to read the "static" value first, then overwrite with the octopus value if available.

**Comment by springfall2008** [comment]
Good point, I've put in a local fix will be in the next submit

**Comment by springfall2008** [comment]
I added a second fix for another case, should be resolved now
