### ISSUE TITLE
Cycling discharge/charge during charge window

### ISSUE THREAD

**Issue by 7Van737** [springfall2008/batpred#600]
**Describe the bug**
I’m on Eco 7 with a 00:30 to 07:30 cheap rate charge window.  I have the ‘Set Charge Low Power Mode’ enabled which is meant to set the charge to make full use of the available charge window.  Generally, predbat fully charges the battery (to 99%) at around 05:30 – and then for the remainder of the cheap rate window it starts cycling between discharging the battery to cover the house load and recharging.  

**Expected behavior**
During the cheap rate charge window all house load should be supplied from the grid and the battery not discharged

**Predbat version**

7.14.36

**Environment details**

AIO
Standard HAOS 

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.

![image](https://github.com/springfall2008/batpred/assets/149843739/6ceb69e6-c763-4d19-b45d-6228231f8828)
[appdaemonLog.txt](https://github.com/springfall2008/batpred/files/13876586/appdaemonLog.txt)

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)

**Comment by 7Van737** [comment]
Here are two screenshots of the predbat plan for this mornings charge

![Screenshot_20240109-022021](https://github.com/springfall2008/batpred/assets/149843739/87aaf004-33bc-4572-9fe0-c37c99448708)

![Screenshot_20240109-033825](https://github.com/springfall2008/batpred/assets/149843739/c14e313b-261b-443b-b3ec-784e7d09fcbb)

**Comment by springfall2008** [comment]
This should be fixed in the latest release, it related to 99% charge levels on inverters where the reserve can't be 100%. Please re-test and file a new issue if you see it again.
