### ISSUE TITLE
Very varied plans - changing every run

### ISSUE THREAD

**Issue by naltsta** [springfall2008/batpred#605]
**Describe the bug**
Pretty drastic plan changes every 5 minutes, some of which are notably more expensive than others. Plan changing during slots so very spiky charge profile and over charged this morning compared to best plans I saw last night.

**Expected behavior**
Pick cheapest plan

**Predbat version**
7.14.37

**Environment details**
Gen 1 givenergy via GivTCP and 2x2.6kWh
- Standard HAOS installer
- Anything else?

**Screenshots**
![image](https://github.com/springfall2008/batpred/assets/128919622/e48609a7-58b1-4181-a2aa-4d5196234dbe)
**Log file**

**Comment by springfall2008** [comment]
Can you provide examples of the different predbat plans and maybe a logged? Thanks

**Comment by naltsta** [comment]
![image](https://github.com/springfall2008/batpred/assets/128919622/b4ec1d6f-0d09-47ad-86d4-d2a14f3dbf64)

![image](https://github.com/springfall2008/batpred/assets/128919622/5db3f6f1-904a-4caf-836c-b3e8d2f65861)

Charging plan for tonight - Not as drastic differences as last night. Plenty of PV forecast so charging less in cheaper

**Comment by naltsta** [comment]
I'm still not really sure I totally understand the calibration chart but it doesn't normally look like this

![image](https://github.com/springfall2008/batpred/assets/128919622/8edfb38e-b88e-4e53-aa6a-2da0a61f9d35)

**Comment by springfall2008** [comment]
I'm not sure why the issue happens, but it's been exposed in your system as you have the plan re-calculation time set to 5 minutes rather than the default 10 minutes.

I will still have a look and see if I can find out the root cause, but if you set this time back to 10 it will probably go away
