### ISSUE TITLE
Car kWh not achievable 

### ISSUE THREAD

**Issue by dandwhelan** [springfall2008/batpred#621]
**Describe the bug**
Manual Car Charging Slots change on the number of kWh rounds down from 3.6K kWh to values not achievable unless the Amps were manually controlled via Predbat. 

**Expected behaviour**
Group all the 3.6KW together. 

**Other info**

This bug is not very important. It's just showing a number that's not achievable unless it controls the AMPs. On the other hand I understand Predbat wants to put 10 KW into my car and doesn't want to go under it rather have it over 10KW than under. 
**Predbat version**

v7.14.41

**Environment details**

HASO - 8.2KW BAT - Gen 2 Hyb Inv 

**Screenshots**

![image](https://github.com/springfall2008/batpred/assets/79152287/9d85c534-3762-4245-8e65-743664d915d0)

[appdaemon.log](https://github.com/springfall2008/batpred/files/13941182/appdaemon.log)
[appdaemon1.log](https://github.com/springfall2008/batpred/files/13941183/appdaemon1.log)
[appsyaml.log](https://github.com/springfall2008/batpred/files/13941184/appsyaml.log)

**Comment by dandwhelan** [comment]
It doesnt really matter.. think I'll close this.

**Comment by springfall2008** [comment]
There’s certainly something funny about it, I’ve just not had time to look yet. Lets keep it for when I do

**Comment by springfall2008** [comment]
There was a bug here in the calculations, but it's also worth pointing out the slots for car charging can be less than 30 minutes so lower values are achievable

**Comment by springfall2008** [comment]
Released in: https://github.com/springfall2008/batpred/releases/tag/v7.15.0
