### ISSUE TITLE
Plan issue in 7.14.45 in monitor mode

### ISSUE THREAD

**Issue by dochtie** [springfall2008/batpred#629]
**Describe the bug**
When set to monitor mode the plan in 7.14.45 shows an immediate charge to 100% and then all slots (except 1630) as hold charge 100%. Rolling back to 7.14.44 gives a correct plan. Updating again to 7.14.45 gives the incorrect plan.

**Expected behavior**
In monitor mode the plan shows the correctly in 7.14.44. On 7.14.45 is shows 100% charge and all slots on hold charge except for 16:30.

**Screenshots**
Screenshots of plans
![IMG_6839](https://github.com/springfall2008/batpred/assets/151058448/a7c97f2f-10d7-45c7-b87d-dca819548ace)
![IMG_6841](https://github.com/springfall2008/batpred/assets/151058448/4f7b5082-5809-4fc9-be86-bdc085c82694)

**Log file**
Log file attached
[appdaemon 2.log](https://github.com/springfall2008/batpred/files/13968123/appdaemon.2.log)

**Comment by springfall2008** [comment]
https://github.com/springfall2008/batpred/pull/636

**Comment by springfall2008** [comment]
Released in: https://github.com/springfall2008/batpred/releases/tag/v7.15.0
