### ISSUE TITLE
Duplicate apps.yaml and predbat.py files

### ISSUE THREAD

**Issue by paulmower** [springfall2008/batpred#631]
Hi. Just getting my head around install and running of predbat. One problem I have noticed is that on startup it reports that it "fails the sanity test" as there are multiple copies of predbat.py

![Screenshot 2024-01-18 105007](https://github.com/springfall2008/batpred/assets/125800918/831b61f0-ce9f-4989-888d-571ae5040a1c)

On checking there appear to be multiple copies of apps.yaml too -

![Screenshot 2024-01-18 105421](https://github.com/springfall2008/batpred/assets/125800918/089ca1e4-bebb-473b-98cb-f06174b26fa7)

Which one  is in the correct place and/or is it OK to delete the others? FYI - it seems if I edit one of the apps.yaml files and save it then all instances seem to be updated.

Thanks in anticipation

**Comment by springfall2008** [comment]
Are you sure /config isn't just a link to /homeassistant?

Did you ever update AppDaemon to the latest which uses the add_ons directory?
