### ISSUE TITLE
Suboptimal plan 

### ISSUE THREAD

**Issue by slopemad** [springfall2008/batpred#643]
It's been a while since I've used Predbat in anything other than read only mode, it's charge decisions have been bizarre at times.  This is tonight's plan, where it wants to hold the battery during the expensive part of the evening (say, 15-18p) (thus running off the grid), and charge up whilst prices are still comparatively high (say, 9-14p) and not charging when prices are at their lowest (say, 0p-8p), whilst to me it would be better to let the battery completely run flat this evening, and do a full recharge when prices are lowest (01:30-05:30).

It just feels the plan is more random than based on any kind of calculation, compared to how it used to be.

Logs at https://pastebin.com/U4RRBVVY

I have tweak second pass enabled, best soc keep at 0.5, Battery Cycle Cost set to 
<img width="652" alt="Suboptimal Plan" src="https://github.com/springfall2008/batpred/assets/118896510/d8805439-1509-4b95-94c0-ec42d7b92044">

**Comment by springfall2008** [comment]
Can you try with metric battery cycle at 1.0 or less as I think your value of 3 is skewing towards grid use, it effectively adds 6p per kWh to the cost of using the battery

**Comment by slopemad** [comment]
Well, that's looking more promising.  I guess I misunderstood how it used the metric battery cycle in the calculations, I guess it adds 3p to both charge and discharge?

<img width="740" alt="That's better" src="https://github.com/springfall2008/batpred/assets/118896510/925e2131-6827-4648-a4d6-04a63acc469a">

**Comment by springfall2008** [comment]
Yes correct, the explanation is in the manual but I don’t think it’s clear how this will influence grid use

**Comment by slopemad** [comment]
That said, I've just noticed it's decided the car charge slot should be *now* rather than in the cheap slots :-|

**Comment by springfall2008** [comment]
Do you have car charging plan smart on?

**Comment by springfall2008** [comment]
If so check your ready by time too

**Comment by slopemad** [comment]
Yes, because in the original plan at the top of the thread, the car charges were at the expected slot, but all I changed was the metric battery cost.  Ready Time is set to 07:00:00

**Comment by springfall2008** [comment]
Can you attach a log, something is not right there?

**Comment by slopemad** [comment]
OK, so car charging smart had somehow become off - I've turned it back on and it's fine now.
But the plans are now taking 4-5 minutes to create.
`now complete after 223.270022 seconds (limit=10)`
I have tweak optimisation on, full second pass is off and calculate regions is off too.

It's also doing a lot of charge/discharge in the same slot, which may well not work in reality if the heat pump kicks in, which it's likely to at those prices.  'Calculate charge on discharge' is off.

**Comment by slopemad** [comment]
A log for the last run at 215 seconds... https://pastebin.com/nnfc9gWw

**Comment by springfall2008** [comment]
If you haven’t already maybe try plan forecast hours as 24 to speed things up?

There can only be one charge and one discharge in a 30 minute period and they can’t overlap.


![IMG_3451](https://github.com/springfall2008/batpred/assets/48591903/57e3def2-46fa-4fb8-a671-4c0d3575257f)

**Comment by slopemad** [comment]
The issue was that, for some reason, a load of settings had changed, so smart car charge became disabled, it disabled expert mode (and thus only applied a bunch of defaults, which seem to make the run time substantially longer).  Working much better now.

**Comment by springfall2008** [comment]
Odd, I’ve seen that myself once also but never tracked down why the settings changed

**Comment by gcoan** [comment]
> Yes correct, the explanation is in the manual but I don’t think it’s clear how this will influence grid use

I've just completed documenting a new Predbat FAQ to better explain how the losses and the battery metric work.  Draft here: https://github.com/gcoan/batpred/blob/main/docs/faq.md#the-plan-doesnt-charge-or-discharge-when-i-expect-it-to

Also updated the main customisation text https://github.com/gcoan/batpred/blob/main/docs/customisation.md#battery-loss-options to highlight that the battery metric cost applies to both the charge and the discharge
