### ISSUE TITLE
Unexpected forced discharge

### ISSUE THREAD

**Issue by SJB1235** [springfall2008/batpred#672]
When running in Control and Discharge mode a Discharge session suddenly starts when moments before one was not planned.

I'm on Octopus Flux and have been trying to configure Predbat to not discharge in the peak export session but leave it able to do so if a Savings Session starts. To do this I have set predbat_metric_min_improvement_discharge=30. This works fine on the plan until after 1630 when the plan is recalculated and suddenly 1630-1701 is a discharge slot.  This has happened several times this week.
 
Plan before and during:
![image](https://github.com/springfall2008/batpred/assets/144248687/d411dace-2657-4f5a-8811-1bd3fd1ff9ee)

Predbat version: V7.15.5 and V7.15.2

Environment details:
- Gen 1 3.6kWh Hybrid Inverter and 8.2kWh Battery
- HAOS

Current settings:
![image](https://github.com/springfall2008/batpred/assets/144248687/9a485553-5037-4a04-b4a0-d4ac73a614c9)

[appdaemon.log](https://github.com/springfall2008/batpred/files/14101973/appdaemon.log)

**Comment by springfall2008** [comment]
I would put metric min improvement discharge back to the normal
0.1 but set high rate threshold to say 1.5

**Comment by SJB1235** [comment]
That gave a plan that fully discharges (down to 4%)  the battery between 16:00 and 19:00, I've set it to 2 which seems to give the plan I want.  I've also cleared the Discharge Start and End times on the inverter in case that was causing a problem.
Thanks for responding so quickly.

**Comment by SJB1235** [comment]
Well that worked in stopping the discharge so now just need a Saving Session.  Or should I use the new  rates_export_override instead?

**Comment by springfall2008** [comment]
No I think the 2.0 high rate threshold is fine for saving sessions
