### ISSUE TITLE
Predbat set the inverter to charge in the peak period

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#673]
**Describe the bug**
Predbat has been very reliable and consistent in choosing logical battery activities.

Ordinarily predbat will hold the battery charge in the start of the peak period for the first couple of slots, depending on rates, and then release it to meet house demand at 17:00.  The battery (only a 5.2 so 4.2 usable) then will last me through the worst of the peak rate slots.

But today at 17:35 (in the peak rate period) I got an alert that the battery was being set to charging.

Looking in predbat, this was indeed what was happening, the predbat state was Charging and there was a charge slot set for 17:30-18:00.
![image](https://github.com/springfall2008/batpred/assets/142018870/1e11a68e-1c24-4f84-a687-51c335dae232)

The battery at the time was idle as the soc was close to the target charge of 64%.
![image](https://github.com/springfall2008/batpred/assets/142018870/8d3b8c93-c9e4-4f71-bea5-4eb59b114a6e)

So I left it.

Then when I checked at 17:50 I could see that the battery was now on 60% SoC and was charging at full rate.  The rates didn't make any reason for Predbat to charge at this time.
![image](https://github.com/springfall2008/batpred/assets/142018870/6944480b-9ad2-4e1f-ba8d-35f7bd074d80)

I set the 17:30 slot to Force idle and the Predbat status went to 'hold charging target 0%' which doesn't make any sense.
![image](https://github.com/springfall2008/batpred/assets/142018870/2b6d4131-bcc1-47ff-8051-a4968e8df0b0)

The battery however was discharging to meet house load.
![image](https://github.com/springfall2008/batpred/assets/142018870/53caecee-77a9-42d3-a71e-a1a2053ba117)

**Expected behavior**
No charging in peak rate period when there's no cost reason to do so.

Hold charging at 0% doesn't occur.

**Predbat version**
17.5.5

**Environment details**
HAOS
Gen 1 hybrid, 5.2 battery

**Log file**
[appdaemon (15).log](https://github.com/springfall2008/batpred/files/14103091/appdaemon.15.log)

Current settings:
[24_01_30_19_10_00.txt](https://github.com/springfall2008/batpred/files/14103137/24_01_30_19_10_00.txt)

I recently increased inverter loss from 0 to 0.03 so not sure if this is relevant?

**Comment by springfall2008** [comment]
The only odd thing I can see is combine_charge_slots maybe best set to Off, but I don't see why it would matter. Annoyingly I cleaned up the debug output a bit and now I don't have enough from the log to help that much. If it happens again can you turn on debug enable?

**Comment by springfall2008** [comment]
Try turning combine charge off also.

**Comment by gcoan** [comment]
Yes can turn combine charge off, but the recommendation for agile is to have it set on?

**Comment by springfall2008** [comment]
Hmmm it shouldn’t really matter but in that specific case I think you might have had a 1 hour slot and the charging was in the second half

**Comment by gcoan** [comment]
still don't know why it would want to charge in the peak rate.

Tomorrow's peak period is typical of what Predbat normally does, the battery is at 100% by 16:00, the 4.2kW SoC of my 5.2 is released in the 16:30, 17:30 and 18:00 slots
![image](https://github.com/springfall2008/batpred/assets/142018870/bc57789c-12ff-4979-b382-f45ce22ca7af)

This is with combine charge slots off

The fuller plan with combine charge slots off
![image](https://github.com/springfall2008/batpred/assets/142018870/ce2e3df3-15e7-47ad-9290-79eab60e7c47)

and with combine charge slots back on, a bit more discharge at 11:30 and no partial slot discharge at 13:00. but financially much the same result and the peak is the same
![image](https://github.com/springfall2008/batpred/assets/142018870/ed8165e9-034b-40ba-845d-af194dfbf006)


I'll leave combine charge slots off

**Comment by gcoan** [comment]
I'll close this and reopen if it ever happens again (and I notice it!)
