### ISSUE TITLE
Add option to show predicted remaining battery charge at the end of the day (prior to end of day forced charge/discharge) as a figure

### ISSUE THREAD

**Issue by cjfolkard1** [springfall2008/batpred#69]
I'd like the value of the battery prior to end of day forced charge/discharge so that I can plot this as a gauge on the dashboard (I therefore know how much extra energy I can use in the day as a value to drive automations etc)

**Comment by springfall2008** [comment]
Added in https://github.com/springfall2008/batpred/releases/tag/v6.43
