### ISSUE TITLE
Differentiate between Predbat and nordpool in the HTML plan

### ISSUE THREAD

**Issue by JonathanLew1s** [springfall2008/batpred#699]
**Is your feature request related to a problem? Please describe.**
I have nordpool configured in apps.yaml but cannot tell if the rates displayed in the HTML are based on the predbat logic, based on todays' rates or using the nordpool estimated rates.

**Describe the solution you'd like**
rather than a ? can we have a different character to signify the value is based on nordpool?

**Comment by springfall2008** [comment]
Fixed in v7.15.13
