### ISSUE TITLE
set_window_notify sends notifications to all phones [feature request]

### ISSUE THREAD

**Issue by mervin39** [springfall2008/batpred#7]
When set_window_notify (also set_discharge_notify, set_soc_notify, set_reserve_notify) are set to True, Home Assistant will send a notification to any phones with the companion app installed. This is fine and useful for me, but my SO doesn't need to know the ins and outs of battery charging. It would be great to have section in apps.yaml to configure which devices receive the notification, instead of all-or-nothing

**Comment by treforsouthwell-sifive** [comment]
I'm sure I can do that, I'll put it on the list

**Comment by springfall2008** [comment]
I'm sure I can do that, I'll put it on the list

**Comment by springfall2008** [comment]
Should be ready for testing now

**Comment by mervin39** [comment]
Looks great - testing now. Do you know of an easy way to trigger a notification?

**Comment by springfall2008** [comment]
I normally change my set_window_minutes to 1000 and then toggle on or off scheduled charging (so the tool has to changed it back)

**Comment by mervin39** [comment]
Yep that did it. Notifications were sent to only the devices in the list.
Thank you!
