### ISSUE TITLE
Wrong unit for calculate plan every n minutes

### ISSUE THREAD

**Issue by dochtie** [springfall2008/batpred#708]
**Describe the bug**

Calculate plan had the units in kWh rather than mins.

![IMG_7007](https://github.com/springfall2008/batpred/assets/151058448/7139eaf3-c703-44b1-ba36-c47fc4546e7b)

**Comment by gcoan** [comment]
Nice spot !

**Comment by springfall2008** [comment]
Fixed in v7.15.13
