### ISSUE TITLE
Repeated Errors during low power mode

### ISSUE THREAD

**Issue by dochtie** [springfall2008/batpred#714]
**Describe the bug**
During low power mode my inverter often will not accept the charge value Predbat tries to set. This causes predbat to repeatedly try before finally reporting ‘charging with errors check log’.

2024-02-04 14:36:15.877554 INFO pred_bat: Inverter 0 current charge rate is 478 and new target is 625
2024-02-04 14:37:18.232641 INFO pred_bat: WARN: Inverter 0 set charge rate 625 via REST failed got 478

**Expected behavior**
I don’t know if there is a set of values my inverter will accept. If not then predbat should accept a rate within a certain range rather than keep trying to change it. 

**Predbat version**

7.15.12

**Environment details**

- All in One
- HAOS

**Screenshots**
![IMG_7009](https://github.com/springfall2008/batpred/assets/151058448/df9e2425-05ee-40e2-b1fd-51aaa5470b72)

**Log file**
[appdaemon 3.log](https://github.com/springfall2008/batpred/files/14157287/appdaemon.3.log)

**Comment by springfall2008** [comment]
Fixed in v7.15.13

**Comment by dochtie** [comment]
Within the hour 🤯
