### ISSUE TITLE
Nordpool, It shows the same price today and tomorrow but it doesn't work between 00:00 - 07:00

### ISSUE THREAD

**Issue by JohanAlvedal** [springfall2008/batpred#718]
**Describe the bug**
Now when I start reviewing I see that after 00:00-07:00 it shows -0.10 ? so after 00:00 it is wrong. Once the times are shown, it is the same price as today's.
It shows the same price today and tomorrow but it doesn't work between 00:00 - 07:00
**Expected behavior**
It should show today's price and after 00:00 tomorrow's price.

**Predbat version**
7.15.12

![predbat 2](https://github.com/springfall2008/batpred/assets/25838439/7e54fd6d-6a8f-43cf-a8b6-f632ed204a67)

![predbat 3](https://github.com/springfall2008/batpred/assets/25838439/d4793cae-1dfe-4a65-97c7-b28df2c4edeb)

**Comment by springfall2008** [comment]
Can you show the matching data for this?

**Comment by JohanAlvedal** [comment]
You can try installing nordpool in dim HA and see how it looks. No registration etc. is needed.
I have added everything to the sensor at the following link.
[https://pastebin.pl/view/a340ee94](url)

![predbat 4](https://github.com/springfall2008/batpred/assets/25838439/b76e985a-0573-49fb-9816-9f93711b4c9b)

**Comment by JohanAlvedal** [comment]
It's better than before but the same price as today after 00:00 (Tuesday)

Predbat v7.15.15

![cost1](https://github.com/springfall2008/batpred/assets/25838439/3296d86e-744d-43f9-920e-ed5d8d133bca)
![cost2](https://github.com/springfall2008/batpred/assets/25838439/72990054-a640-4e9b-a26a-55ff3a9ded50)

**Comment by springfall2008** [comment]
Isn’t this because the nordpool data runs out and then predbat just repeats it?

**Comment by JohanAlvedal** [comment]
Yes, it might be. But sometime after 13:00, tomorrow's prices are included.

**Comment by springfall2008** [comment]
I'm struggling to understand if there is still an issue or if this is working as expected?

BTW: Predbat also has Nordpool access but it's used to adjust Octopus Agile data.

**Comment by JohanAlvedal** [comment]
Hello
Yes, right now it's a problem if you expect to charge the battery after 00:00 predbat don't know what the real price is. I fully understand that this is not priority 1 for you, so right now I'm "playing" a bit with this. However, it would be fun if you could get it started as I know that there are probably some who would appreciate it if this got started with nordpool and Huawei inverters. I'm still struggling to get started with the charging schedule, nothing is happening yet. However, I think it may have to do with my sensor not having enough history yet. I'll read and check out your videos tonight. 
(Unfortunately, as far as I know, there is no Octopus Agile data for us Swedes)

**Comment by springfall2008** [comment]
I figured it out now, the tomorrow data is under raw_tomorrow, will release a fix shortly.

**Comment by springfall2008** [comment]
https://github.com/springfall2008/batpred/releases/tag/v7.15.19
