### ISSUE TITLE
Incorrect Cost Calculation in HTML Plan

### ISSUE THREAD

**Issue by JonathanLew1s** [springfall2008/batpred#720]
**Describe the bug**
At 23:30 tonight the rate is £0.00, the plan somehow calculates the cost of charging in this slot as 47p.

**Predbat version**

7.15.13

**Screenshots**
![image](https://github.com/springfall2008/batpred/assets/34936213/1eba7610-ca31-456f-9150-c955b8ac9413)

**Log file**

[_appdaemon_logs-11.txt](https://github.com/springfall2008/batpred/files/14157903/_appdaemon_logs-11.txt)

**Comment by springfall2008** [comment]
This is your standarding change!

**Comment by JonathanLew1s** [comment]
Sorry.

**Comment by gcoan** [comment]
JonathanI deleted the standing charge sensor in my apps.yaml so my Predbat plan matches my energy dashboard and only has consumption costs. Not much I can do to optimise the standing charge and I felt it distorted the dataOn 4 Feb 2024, at 18:47, JonathanLew1s ***@***.***> wrote:﻿
Sorry.

**Comment by JonathanLew1s** [comment]
Historically it's been commented out. Updated my apps.yaml last week, to align with upstream, and forgot about standing charge.

**Comment by gcoan** [comment]
Ha ! 

Well if that's the only thing you got wrong with the apps.yaml, it's a good result
