### ISSUE TITLE
(Minor) missing Nordpool rate for 23:30pm

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#730]
**Describe the bug**
Not sure if it is a formatting error or a genuinely missing rate, but with the change to see where future rates are being populated from, it appears that the 23:00 rate and 00:00 tomorrow night are both coming from Nordpool, but the 23:30 is coming from Predbat repeating today's rate

Not sure whether this is a formatting error in the plan or a loop issue in the norddata retrieval.  Can't see anything in the log that suggests the data is missing

Low priority issue

**Expected behavior**
23:30 rate populated from Norddata as are the 00:30, 01:30, etc, up to when they are populated by Octopus

**Predbat version**
7.15.16

**Screenshots**
![image](https://github.com/springfall2008/batpred/assets/142018870/9155ffab-41cb-4178-8a0d-8f374b38adf1)
![image](https://github.com/springfall2008/batpred/assets/142018870/bb80f2d6-fe3b-425b-98c1-ac511427435a)

**Comment by gcoan** [comment]
Logfile if you need it
[appdaemon (25).log](https://github.com/springfall2008/batpred/files/14179699/appdaemon.25.log)

**Comment by springfall2008** [comment]
It's certainly has a bug, need to figure out what causes it.

**Comment by springfall2008** [comment]
Good spot, this was a nasty wrapping bug and also there was an issue with some of the rates getting overriden by the average. Hopefully better now

**Comment by springfall2008** [comment]
https://github.com/springfall2008/batpred/releases/tag/v7.15.18

**Comment by gcoan** [comment]
Thanks Trefor, I'll have a look tomorrow but am sure it'll be fixed.

Cheers
