### ISSUE TITLE
Status Description confusing

### ISSUE THREAD

**Issue by pacemaker82** [springfall2008/batpred#744]
Can we take a look at or confirm the following status description, as a layman it seems confusing or counter-intuitive. Example:

From: https://springfall2008.github.io/batpred/what-does-predbat-do/#predbat-status

> Freeze discharging
> This is the same as Idle (Eco) mode but with **charging disabled.** The battery is covering the load but as charging is disabled, any solar generated will be exported.

Bold for emphasis. If the status is "freeze discharging", my expectation is that the battery discharging is disabled, when in fact CHARGING is disabled, discharging **_is_** happening to the house and is not "frozen". 

In this status mode "Freeze Discharging" the _actual_ behaviour is that discharging is enabled, and charging is disabled. So the description is correct, but doesnt align with the status as written in my opinion

**Comment by springfall2008** [comment]
I see where you are coming from, the idea is that freeze charging is when you charge but the charge level is frozen while freeze discharge is when you discharge but the discharge level is frozen. 

In freeze discharging the battery is in discharge mode, while in freeze charging the battery is in charge mode.

**Comment by pacemaker82** [comment]
Thanks, so I have this in my plan:

<img width="471" alt="Screenshot 2024-02-10 at 09 42 01" src="https://github.com/springfall2008/batpred/assets/157808562/7e9b07af-0d91-4f6e-b4d5-546931557753">

You mentioned:
> freeze discharge is when you discharge but the discharge level is frozen.

As I dont see a limit set, how is the level frozen in this case?

**Comment by springfall2008** [comment]
>As I dont see a limit set, how is the level frozen in this case?

Effectively its the current SOC as the limit, it means we only exoport excess solar rather than the battery.

**Comment by gcoan** [comment]
I have updated the docs to expand the explanation of what the freeze modes do.
