### ISSUE TITLE
Predbat 7.15.21 stuck in install state

### ISSUE THREAD

**Issue by pacemaker82** [springfall2008/batpred#751]
**Describe the bug**
The installation of 7.15.21 is stuck on an installing state, have received two messages on my phone saying it installed, but predbat seems top be offline, the plan is null.

**Expected behavior**
clean installation

**Predbat version**

7.15.21 

**Environment details**

Home Assistant Green, 

**Screenshots**

<img width="556" alt="Screenshot 2024-02-11 at 20 33 21" src="https://github.com/springfall2008/batpred/assets/157808562/c2d57aac-6277-4679-8263-3fd4dde46d50">

<img width="1032" alt="Screenshot 2024-02-11 at 20 34 53" src="https://github.com/springfall2008/batpred/assets/157808562/e31364c9-2292-4fcc-a56b-aeb3ff481e32">

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)

**Comment by gcoan** [comment]
My 7.15.21 upgrade installed flawlessly and is running fine.

It looks like the upgrade process within HA has got stuck

Can you try shutting down the AppDaemon or Predbat-AppDaemon add-on (depending on what you are using, I suspect its the latter) and restart it, to see if that brings it back to life?

Maybe then try a full shutdown and restart of Home assistant and all the add-on's to clear the stuck status

**Comment by pacemaker82** [comment]
The restart of the app daemon fixed it

**Comment by gcoan** [comment]
Great, glad you were able to sort it out
