### ISSUE TITLE
Battery not planning to charge

### ISSUE THREAD

**Issue by gmarchment** [springfall2008/batpred#756]
Hi there,

Batpred has been working perfectly until yesterday - there were quite a few updates which I triggered (HA Core, some of the supporting integrations) and Batpred is set to automatically update.

Last night the battery didn't set to charge, and it's not looking like it will plan to charge this evening either.  Any ideas?

<img width="1014" alt="image" src="https://github.com/springfall2008/batpred/assets/151647330/06116b03-b05a-40bd-96a6-40104a73aa62">

<img width="546" alt="image" src="https://github.com/springfall2008/batpred/assets/151647330/033404da-7c0a-4561-9d51-a1b7d943c34c">

**Comment by springfall2008** [comment]
The error in your status is of concern, is your apps.yaml correct and you don't have duplicate versions?

Also is predbat mode set to control charge?

**Comment by gmarchment** [comment]
> The error in your status is of concern, is your apps.yaml correct and you don't have duplicate versions?
> 
> Also is predbat mode set to control charge?

It's weird, as the apps.yaml is definitely right, and there's only one version.

**Comment by gmarchment** [comment]
Aha - for some reason Mode had been set to Monitor rather than Control Charge & Discharge.  Thanks Trefor.
