### ISSUE TITLE
Expose notification config so it can be defined.

### ISSUE THREAD

**Issue by mehstg** [springfall2008/batpred#76]
Currently all notifications go to `notify.notify`. Would it be possible to make this a configurable option as `notify` sends to all "people" in HA. Had a look at the code and it looks like some of the work for this has already been done, it's just not exposed in a way we can configure.

**Comment by treforsouthwell-sifive** [comment]
You can configure this in apps.yaml just not inside the HA GUI right now

**Comment by mehstg** [comment]
Apologies. I just found it commented out in `apps.yaml`. I'll leave the issue open if you want to add to the HA gui, else happy for you to close.
