### ISSUE TITLE
Multiple instances of batpred

### ISSUE THREAD

**Issue by Ed-M72** [springfall2008/batpred#78]
Hi Trefor,

To run multiple instances of batpred do I just need to duplicate apps.yaml and in the second one change the name of the two following tags below?

pred_bat2:
  module: predbat
  class: PredBat

  prefix: predbat2

**Comment by springfall2008** [comment]
I think both configs can go in the same apps.yml And yes a different prefix for the second one.I’d be interested to understand your use case On 13 Sep 2023, at 20:01, Ed Mellodew ***@***.***> wrote:﻿
Hi Trevor,
To run multiple instances of batpred do I just need to duplicate apps.yaml and in the second one change the name of the two following tags below?
pred_bat2:
module: predbat
class: PredBat
prefix: predbat2

**Comment by Ed-M72** [comment]
To clarify, do I also need to change pred_bat to pred_bat2?

A predbat for each phase.  And on the car charging, I assume I would use the total for the phase rather than the total for the charger?  I might need a bit of help on this as I test.

**Comment by springfall2008** [comment]
Yes I think pred_bat2 is correct.

Yes for car charging I guess it's the total for the phase too.

Can you not combine the phases, e.g. just use one Predbat and multiple inverters?

**Comment by springfall2008** [comment]
Closing for now, feel free to open a new ticket for anything new
