### ISSUE TITLE
Make the Predbat plan more configurable

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#782]
**Is your feature request related to a problem? Please describe.**
Suggestion from the GivEnergy community forum that the predbat plan be user configurable as to the order of columns.   Would like the order to specify the column sequence according to user preference.

**Describe the solution you'd like**
New apps.yaml config item to define the column sequence for the predbat plan.
Default to the existing, but user can set to their preferred sequence if they wish.

For example, the apps.yaml config could look like this:
plan_display:
  - last_updated_fmt: %D %H:%M
  - plan_columns: Import:Export:State:Limit:PV:Car:iBoost:Load:SOC:Cost:Total
  - kwh_rounding: 1

where:
- last_updated_fmt is a standard unix date format string to display 'last updated' in, if set to "none" then the line is omitted from the plan, default to current format
- plan_columns: a colon separated list of columns to be displayed. Default to current list of columns.  Any columns not included are nor displayed
- kwh_rounding: number of decimal places to round the kWh values to. Default 2dp

**Describe alternatives you've considered**
User can restyle the plan using CSS but this doesn't easily give the ability to change the sequence of columns

Maybe ability for users to have their own 'state' text/icons in place of the standard

Currency displayed in the total should be retrieved from the HA default, not hard coded to £

**Additional context**
Alternative styled plan example:
![image](https://github.com/springfall2008/batpred/assets/142018870/a9f456d9-d091-435e-8d06-e8d4cf170750)

**Comment by gcoan** [comment]
Further idea for a config option:

only_show_effective_rates: false

Option to only show the effective rates (ie: including losses) not the actual rates if plan_debug is set to true.

**Comment by pacemaker82** [comment]
Just to add - I created the alternative view of the table mentioned above as a custom card.

I am taking the entity HTML `predbat.plan_html` and using javascript to iterate through the table HTML to change it to my liking, adding CSS, SVG and MDI icons. I am working on a second version which is pulling all the data out of the table into JS objects so that I can just have a table of the columns I want (in the order I want). Potentially this could be a solution where the columns and order I want are part of the card YAML. Will share if useful

**Comment by pacemaker82** [comment]
I have this up and running now which allows me to set which columns I want and in which order. The formatting/CSS isnt done but gives a good sense of the kind of flexibility a card could have built in:

<img width="966" alt="Screenshot 2024-02-25 at 18 03 53" src="https://github.com/springfall2008/batpred/assets/157808562/8fe6ee2c-ebc0-4416-a6f6-ccdcf5d2d734">

**Comment by pacemaker82** [comment]
I got this up and running now more fully

https://github.com/pacemaker82/PredBat-Table-Card

**Comment by gcoan** [comment]
Achieved now via the Predbat table card
