### ISSUE TITLE
Add support for Solar Assistant

### ISSUE THREAD

**Issue by xhemp** [springfall2008/batpred#786]
Would be great to have support for Solar Assistant ( https://solar-assistant.io/ ). It supports many types of inverters and the beta version has a proper power management that works fine with Growatt (my case) inverters as well.
I saw another issue opened here for Huaweii ( #684 )  so I will try to play a bit with the template yaml and see where I get, just wanted to get this on the radar (and also confirm if this is something doable or not).
Thanks!

**Comment by springfall2008** [comment]
Could make sense, but can share details on how to control it in HA?

**Comment by xhemp** [comment]
Hey, thanks for getting back to me!
So the way I use SA with Home Assistant via MQTT:
For example, there's a switch called Work mode priority, there you select Load first, Battery first or Grid first. That is tied to the device_mode topic on MQTT.
Attached is a screenshot of all the MQTT topics for Solar Assistant:

<img width="405" alt="Screenshot 2024-03-03 at 22 11 01" src="https://github.com/springfall2008/batpred/assets/13650956/b3e4ac9a-a349-4ff1-ae07-f3521747e5a6">

If you need anything else or have any other questions, let me know.

**Comment by springfall2008** [comment]
Do these MQTT topics appear as HA entities?

I would need a list of HA entities that hold the basic information required for apps.yaml together with some example automations used to charge and force discharge the battery

**Comment by xhemp** [comment]
They do, yes and sure thing, here's the entities list: 
[entities_list.txt](https://github.com/springfall2008/batpred/files/14480640/entities_list.txt)
Please, let me know if you need anything else!

**Comment by springfall2008** [comment]
I guess I don't really know what these do without context.

Can you take this template and try to map these sensors to the line items listed here: 

https://github.com/springfall2008/batpred/blob/main/templates/solaredge.yaml

Then if you can create a simple automation in HA to start and stop charging the battery from grid and to discharge the battery to the grid that can go into the configuration also.

**Comment by xhemp** [comment]
@springfall2008 Sure thing, I am abroad this week but I will give this a go next week, thanks!

**Comment by xhemp** [comment]
Those are the sensor values I came up with ( I added a few questions to understand what's the need on some of them):

  battery_rate_max:
    - number.growatt_spa_battery_first_stop_charge
  charge_rate: ( In percentage works? Mine, in watts, is 3kW/h charge)
    - number.growatt_spa_free_mode_charge_rate
  discharge_rate: ( In percentage works? Mine, in watts, is 3kW/h discharge)
    - number.growatt_spa_free_mode_discharge_rate
  battery_power:
    - sensor.growatt_spa_battery_power
  pv_power:
    - sensor.growatt_spa_pv_power
  soc_max: (is this the maximum in watts? Mine is 6kW, as the charge/discharge rate, if needed, 
            I can create a custom template with those values set)
    - sensor.?

For the automation, here they are:

  # Services to control charging/discharging
    service: select.select_option
    entity_id: "select.growatt_spa_work_mode_priority"
    option: "Battery first"
  charge_stop_service:
    service: select.select_option
    entity_id: "select.growatt_spa_work_mode_priority"
    option: "Load first"
  discharge_start_service:
    service: select.select_option
    entity_id: "select.growatt_spa_work_mode_priority"
    option: "Grid first"

Let me know if this is what you were looking for and if you need any changes or an explanation.

**Comment by springfall2008** [comment]
charge_rate - should be a setting in Watts e.g. 3000=3kW.
You can just hard-wire it as 3000 for now
discharge_rate - as charge rate

soc_max is a value in kWh which is the size of the battery e.g. 10 would be a 10 kWh battery

On the services, does Grid first force the battery to discharge at full rate?

**Comment by xhemp** [comment]
> charge_rate - should be a setting in Watts e.g. 3000=3kW.
> You can just hard-wire it as 3000 for now
> discharge_rate - as charge rate
> 
> soc_max is a value in kWh which is the size of the battery e.g. 10 would be a 10 kWh battery
> 
> On the services, does Grid first force the battery to discharge at full rate?

Thanks for clarifying.
Grid first forces the battery to discharge at whatever percentage is set on another sensor ( number.growatt_spa_grid_first_discharge_rate ).

**Comment by xhemp** [comment]
I would love to get this one sorted, any help is appreciated!

**Comment by springfall2008** [comment]
Did you ever get this to work?

**Comment by xhemp** [comment]
I didn't, no, but I am keen on trying again

**Comment by springfall2008** [comment]
The service API is a bit more comprehensive now e.g. for Solax we configure apps.yaml as

```yaml
  # Service for start/stop
  charge_start_service:
    service: select.select_option
    entity_id: select.solax_manual_mode_select
    option: "Force Charge"
  charge_stop_service:
    service: select.select_option
    entity_id: select.solax_manual_mode_select
    option: "Stop Charge and Discharge"
  discharge_start_service:
    service: select.select_option
    entity_id: select.solax_manual_mode_select
    option: "Force Discharge"
```

**Comment by xhemp** [comment]
Thanks for that, I will have a go on this next week and let you know.

**Comment by xhemp** [comment]
I tried to change the SX4 template to this:

https://pastebin.com/2Jf07e8F

Got an error for InverterType so not sure on what I need to set it there.
Anything else I need to change, do you think?

**Comment by xhemp** [comment]
managed to add SA (Solar Assistant) to the config.py, same as the SX4 and was able to pass the inverter type error.
Looks like it's working just confirming if it's doing what it's supposed to do now, will update you later today.

**Comment by xhemp** [comment]
Something I also realised is that the holidays days left are not decreasing at midnight (I'm not at home at the moment).

**Comment by xhemp** [comment]
Looks like the errors I am getting above happen when the inverter has to be set to export, when I check Solar Assistant, it doesn't show it exporting so I am unable to export it, unfortunately.

**Comment by xhemp** [comment]
@springfall2008 I would really appreciate if you can add the SA config (with all false at the moment) to the config.py for now.
