### ISSUE TITLE
Low power charging

### ISSUE THREAD

**Issue by FarmingMartin** [springfall2008/batpred#838]
Is it possible to adjust the battery charge Amps from maximum for Solis Inverters using the SolaX modhub and Solcast integrations according to energy price and predicted solar forecast. At at present any charge window charges at maximum Amps which sometimes leaves no spare battery capacity for solar charge later in the day resulting in solar being exported, for free if you don't have an export tarriff, which defeats the whole idea of saving money as you have paid to charge from the grid.

**Comment by springfall2008** [comment]
This PR may fix this issue; https://github.com/springfall2008/batpred/pull/843
