### ISSUE TITLE
Predbat mode changes on reboot

### ISSUE THREAD

**Issue by colinm1** [springfall2008/batpred#841]
**Describe the bug**
When Home Assistant is restarted Predbat mode changes to Monitor from Control Charge & Discharge

**Expected behavior**
Mode to remain as previously defined

**Predbat version**
7.16.5

**Environment details**

- Inverter and battery setup: Givenergy 3.6 gen 2 hybrid
- Standard HAOS installer or Docker: HAOS
- Anything else?

[appdaemon.log](https://github.com/springfall2008/batpred/files/14589657/appdaemon.log)

**Comment by danbloor** [comment]
I found this same issue today

**Predbat version**
7.16.1

**Environment details**

- Inverter and battery setup: GivEnergy AIO
- Standard HAOS installer or Docker: HAOS (seperate AppDaemon not combined)

**Comment by springfall2008** [comment]
I might have an idea as to the issue, pushing a fix

**Comment by colinm1** [comment]
Still hasn't fixed for me. I'm on 7.16.7 and still rebooting to monitor.

**Comment by mpartington** [comment]
Not fixed for me either, although I see a different set of settings change (occasionally) following a reboot.  For me it turns expert mode off and inverter notifications on (hence I know it's done it).  There may be some others as well.  Log attached, this happened shortly before 10:25 on 22-03 (today).

At 10.25, I selected a pre-saved setting via the drop down to restore to my preferences.

[appdaemon.log](https://github.com/springfall2008/batpred/files/14721204/appdaemon.log)

**Comment by colinm1** [comment]
> Not fixed for me either (7.16.8), although I see a different set of settings change (occasionally) following a reboot. For me it turns expert mode off and inverter notifications on (hence I know it's done it). There may be some others as well, however I remain in charge/discharge mode. Log attached, this happened shortly before 10:25 on 22-03 (today).
> 
> At 10.25, I selected a pre-saved setting via the drop down to restore to my preferences.
> 
> [appdaemon.log](https://github.com/springfall2008/batpred/files/14721204/appdaemon.log)

It also changes expert mode  for me. I now have an automation to revert the settings if it detects a change.

**Comment by colinm1** [comment]
It also changes expert mode for me. I now have an automation to revert the settings if it detects a change.

**Comment by springfall2008** [comment]
This should be fixed now, I re-wrote the settings to be saved to a file
