### ISSUE TITLE
Notifications spamming

### ISSUE THREAD

**Issue by bowen159** [springfall2008/batpred#842]
**Describe the bug**
HA is sending push notifications every 5 minutes even though the inverter state hasn't changed and battery percentage is the same. This seems to happen when freezing discharging.

**Expected behavior**
I notification should only occur or could be configured to only send if the inverter state changes.

**Predbat version**

v7.16.5

**Environment details**

- Giv Hybrid Gen1 5kwh and 8.2kwh Gen battery
- HAOS VM on Proxmox

Example of the issue
![Screenshot_2024-03-13-13-54-12-88_c3a231c25ed346e59462e84656a70e50~2](https://github.com/springfall2008/batpred/assets/100224765/c1145862-e5bc-41c6-856f-8340f30eb615)

**Log file**
Can't get the logs just now. Can add later if still required.

**Comment by springfall2008** [comment]
Fix on 'main' for testing

**Comment by gcoan** [comment]
Thanks, I'm installing it now and will let you know how I get on.

Was seeing multiple repeated messages every 5 minutes this morning for Discharging, Hold Charging and Charging so be good to see this cured.
Idle seems to be the only status that doesn't repeat that I can see.

**Comment by gcoan** [comment]
The charging notification text is different, I thought it was showing current soc to target soc but the figures seemed wrong.
![image](https://github.com/springfall2008/batpred/assets/142018870/c6b5756f-8830-4ee5-bca7-bc86fdb8a788)
![image](https://github.com/springfall2008/batpred/assets/142018870/d61fffdb-8335-48a8-9ed6-56a94effd0a1)

Wondering this morning if it's target soc for the two inverters which is exciting if it is 

Overnight definitely less notifications and isn't the repeated identical notifications.
![image](https://github.com/springfall2008/batpred/assets/142018870/1838c124-9480-4d37-b81d-dd19b26d0cd9)

Although could be argued that the notifications with same Hold Charging but different targets could be suppressed and swap between Charging and Hold Charging also candidates for basically being the same.
But overall much better

**Comment by springfall2008** [comment]
I've made a new release, I still need to clean up dual inverter notifications however

**Comment by gcoan** [comment]
I'll put the new release in then thanks
