### ISSUE TITLE
Odd discharge pattern with IO

### ISSUE THREAD

**Issue by adamwylde** [springfall2008/batpred#85]
Hi @springfall2008 

I followed your guide and video on setting up IO having switched from Flux, and have therefore set my settings as per https://github.com/springfall2008/batpred#cheap-night-rate-with-a-good-export-rate-eg-intelligent-with-octopus-outgoing

I kinda expected that predbat would schedule export at the end of the window thus minimising the risk of running out, but it seems to be scheduling a few random tiny discharge_best drops throughout the window with the final large one ending half an hour before the low rate kicks in:

![image](https://github.com/springfall2008/batpred/assets/39195357/475a503d-4b8d-4a91-bd97-30fed58c3856)

Does that seem right?

Thanks

Adam

**Comment by springfall2008** [comment]
If the export slot line is above the red line then it's export freeze, where it stops the battery charging and instead exports all solar to the grid. It's actually more efficient to do it this way as you avoid charging and discharging losses from the battery. You can turn this on and off with the export freeze option in HA.

**Comment by springfall2008** [comment]
BTW: You might want to check you have turned off 'combine discharge slots'

**Comment by adamwylde** [comment]
Ah I see so avoiding charging only to discharge it later! Genius.

No further questions. Thanks again!

(combine discharge slots is off already)
