### ISSUE TITLE
Update notifications contain changelog for previous update

### ISSUE THREAD

**Issue by ablack89** [springfall2008/batpred#853]
**Describe the bug**
When an update to predbat is available the notification from Home Assistant contains a changelog, but this changelog is actually the one for the currently installed (out of date) version. The changelog for the new version is only shown in the version information after the update has been completed.

**Expected behavior**
The changelog shown on the update notification would allow the changes in the latest (yet to be installed) version.

**Predbat version**

7.16.5

**Environment details**

- installed using appdaemon-predbat

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)

**Comment by ablack89** [comment]
I have captured a screenshot of the update notification before the upgrade to 7.16.7:
![Screenshot 2024-03-17 at 16 16 30](https://github.com/springfall2008/batpred/assets/41829275/a8a7b77f-ef0a-4415-a766-abe10d8b7c3b)
And immediately after installing the update:
![Screenshot 2024-03-17 at 16 20 02](https://github.com/springfall2008/batpred/assets/41829275/f34d554d-53ff-48b2-98c6-696069c1b1ef)

**Comment by springfall2008** [comment]
Fix now on 'main' will be released soon

**Comment by springfall2008** [comment]
https://github.com/springfall2008/batpred/releases/tag/v7.16.8

**Comment by ablack89** [comment]
Good work, thanks.
