### ISSUE TITLE
Constant hold charge at 100%

### ISSUE THREAD

**Issue by Philhews** [springfall2008/batpred#858]
**Describe the bug**
After charging to 100 the current slot is always set to hold charge 100 even when the grid cost is higher than the export of excess solar (even to the point of the first expensive agile slot) 

**Expected behavior**
When grid import cost goes above export price the system should be idle to allow battery use and refill rather than forcing grid use at expensive rates. 

**Predbat version**

7.16.7

**Environment details**

- hybrid 3.6 gen 2, 9.5kwh battery
- Standard HAOS 
- Anything else?

**Screenshots**
![Screenshot_2024-03-17-09-45-48-42_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/cb9770de-8a1c-4fc0-8278-1bd4aa8c33f1)

**Log file**
[appdaemon.log](https://github.com/springfall2008/batpred/files/14626949/appdaemon.log)

**Comment by springfall2008** [comment]
I think this is due to having "metric_min_improvement(-0.4 p)" meaning you will charge now even if it costs 0.4p extra.

Can you try setting it back to 0?

**Comment by Philhews** [comment]
Don't think that's helped. 
![Screenshot_2024-03-17-10-33-28-05_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/d986eead-47ce-4165-9b58-cd56f5ef0ea7)

**Comment by Philhews** [comment]
Log file from it too
[appdaemon.log](https://github.com/springfall2008/batpred/files/14627080/appdaemon.log)

**Comment by Philhews** [comment]
Having forced an idle and used some battery it seems it's happy to leave it on idle when below 100
![Screenshot_2024-03-17-12-32-20-42_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/2b16bbc6-a370-4516-8ef6-b564f55fa84f)

**Comment by springfall2008** [comment]
Can you try changing 'metric_battery_value_scaling' to 1.0?

**Comment by springfall2008** [comment]
Also I have a new release coming that might help with this too..

**Comment by springfall2008** [comment]
Please try this one: https://github.com/springfall2008/batpred/releases/tag/v7.16.8

**Comment by Philhews** [comment]
Battery value scaling at 1, metric min improvement set to 0 and updated to .8 seems to look more sensible as an ahead plan, will leave it and keep an eye on what it does during the day. 
![Uploading Screenshot_2024-03-18-09-23-36-93_c3a231c25ed346e59462e84656a70e50.jpg…]()

**Comment by Philhews** [comment]
Having pulled in nord pool rates it went back to hold charge on an expensive slot. (10.10 plan). Changing metric min improvement to -0.2 removed the charges except on the current slot which is over 16p import. 
![Screenshot_2024-03-18-10-14-45-53_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/36b75fc1-742e-45e4-a697-407ac5379323)
![Screenshot_2024-03-18-10-18-29-28_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/dc995053-32c8-403e-a1d3-dffab024f5ac)
[appdaemon.log](https://github.com/springfall2008/batpred/files/14634687/appdaemon.log)

**Comment by Philhews** [comment]
Initially the hold charge went away at 4pm,but at 5 past it calculated and put it back in. This results in anything over solar pulling at 26p which can't be the best plan? 
![Screenshot_2024-03-18-16-08-36-52_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/117396644/b82955c8-b2d4-4971-adfd-ff649c0038de)
[appdaemon.log](https://github.com/springfall2008/batpred/files/14639281/appdaemon.log)

**Comment by springfall2008** [comment]
Closing this old ticket, please open a new one if you have an up to date question
