### ISSUE TITLE
Load "prediction" too high with anything other than "days_previous" set to 7

### ISSUE THREAD

**Issue by pacemaker82** [springfall2008/batpred#860]
**Describe the bug**
I have been using `days_previous` set to 7 since install. I have IOG and charge my car every night. I have noticed that my load prediction during the night doesnt seem to include the car charging load. Below is the prediction with `days_previous` set to "7"

<img width="1194" alt="Screenshot 2024-03-17 at 10 06 42" src="https://github.com/springfall2008/batpred/assets/157808562/0b9f167d-ab39-4c70-88d8-78782563177d">

So today I've been experimenting using multiple `days_previous` and I get really high loads during the IOG charge window. Here I am using `days_previous` with just "2"

<img width="1190" alt="Screenshot 2024-03-17 at 10 10 05" src="https://github.com/springfall2008/batpred/assets/157808562/0d65928f-59b5-4d8d-aefc-beed68b1f223">

Regardless of what I use other than "7", I get really high loads during the IOG charge time. Is something off here? I wanted to set my `days_previous` to 2,3,4,5,6,7,8 to average out my load over the week, which works great for all the times except the IOG cheap slot timing where the load prediction goes really high.

Its almost like the car charge isnt included when I use "7" but is included if I use any other value for `days_previous`.

I charge my car every night. 7 days ago I used 18kWh to charge the car in the charge window which definitely isnt seen in the load prediction in the first screenshot.

Right now there is no planned car charge for tonight. Not sure if that matters (car column is hidden)

**Expected behavior**
I am not sure - clarity on if the load includes the car load or not, and therefore why using "7" shows a low load, but any other value shows a high load.

**Predbat version**

7.16.7

**Environment details**

- Inverter and battery setup: AC-3, 9.5kWh batt GE
- Standard HAOS installer or Docker: HAOS
- Anything else?

**Screenshots**
above

**Comment by springfall2008** [comment]
Do you have car_charging_energy set correcting in apps.yaml?

**Comment by pacemaker82** [comment]
Ahhhh, thank you that was it. The sensor I had set was related to tesla integration which I uninstalled. Changed it to the new sensor and working great now!

This is for `days_previous` 2,3,4,5,6,7,8
<img width="923" alt="Screenshot 2024-03-17 at 10 36 31" src="https://github.com/springfall2008/batpred/assets/157808562/20a40d44-28f1-46ef-94f9-ed850d61a40d">
