### ISSUE TITLE
Battery charge mode

### ISSUE THREAD

**Issue by mjs7uk** [springfall2008/batpred#863]
Hi first thanks for a great tool and all of your efforts in producing and supporting this.

Would it be possible to get switch.predbat_plan_debug available in non expert mode as it really helps understand why the plan might be the way it is.

Second thing and sorry if this operator error, given the current rates on flux with losses it does not make sense to do a full charge over night, really it looks like you you should do a enough of a charge to get to the point where the solar produces enough to cover house load and start charging the battery, and then only do an export to get to the next charge point

``

 
![Screenshot_2024-03-17-17-23-15-68_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/136758169/c3acf6d5-9dc8-470c-922b-b616e4a2a5e5)

**Comment by gcoan** [comment]
Have a look at this faq on tuning the predbat plan https://springfall2008.github.io/batpred/faq/#the-plan-doesnt-charge-or-discharge-when-i-expect-it-to

It's likely you might need to tweak your loss percentages. What are they currently set to ?

**Comment by mjs7uk** [comment]
Hi currently set to 5,5,5. I have enphase micro inverters that output ac. I am running in non expert mode.

All the others seam to match the suggested settings
![Screenshot_2024-03-17-18-42-15-96_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/136758169/29651ed7-8fe9-46ee-98e4-467506c0a436)

**Comment by gcoan** [comment]
5,5,5 is reasonable and should model correctly whether Flux is worthwhile to charge overnight or not.

Is it possible to copy the predbat plan so we can see the detailed numbers.

I *think* what I am seeing is:
- an overnight charge to full battery
- then the SoC dropping down (using the cheaper stored electricity) in the morning to about half full
- solar generation then starts to reverse the red line, filling the battery up to 100% just before the Flux peak period
- exporting during the flux peak period to about half-full
- house load then emptying the remainder of the battery to end of the night

If I've interpreted the graph correctly then this is a reasonable plan.  You look to have high morning load and only just enough solar to then recoup the battery up to 100% before the evening peak

**Comment by mjs7uk** [comment]
Hi thanks for looking at this, here is the plan (3 images for each).have switched to expert mode to.get the losses, the first plan (first 3 images) is with no best max soc set the second I set it to 7 just to see if my thinking that it did not need a full charge was roughly right it looks like they come out pretty close 
![Screenshot_2024-03-17-20-21-34-80_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/136758169/f054f29d-7443-4b3d-8715-de2c28fb3ba6)
![Screenshot_2024-03-17-20-21-49-35_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/136758169/acd11899-c327-4317-970b-a81be1eebe0b)
![Screenshot_2024-03-17-20-21-57-64_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/136758169/5d839fb9-203c-4057-aa2d-ba878dd358f5)
![Screenshot_2024-03-17-20-24-07-73_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/136758169/f43f0d27-4ffe-4b07-b387-87cf74bbfc07)
![Screenshot_2024-03-17-20-24-16-74_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/136758169/b248794d-32b8-4832-b150-78ff6121d47b)
![Screenshot_2024-03-17-20-24-25-62_c3a231c25ed346e59462e84656a70e50](https://github.com/springfall2008/batpred/assets/136758169/4066b8ed-2de4-4225-9bee-9897b655de5b)

**Comment by gcoan** [comment]
Looking at the first plan, it is much as I thought it was.  There isn't that much peak rate discharge, just a bit of excess to get your battery to a level that will take you through to the next overnight charge.

There is potential for the overnight charge to not be as big as it is as there's 4 hours of export in the afternoon when the battery is at 100%.  But conversely the solar might not be as good as predicted and your house load could be higher, so some contingency in the plan isn't an absolutely bad thing.

**Comment by springfall2008** [comment]
Closing this old ticket, please open a new one if you have an up to date question
