### ISSUE TITLE
Failed to update SetReserve.

### ISSUE THREAD

**Issue by rsarwar87** [springfall2008/batpred#879]
**Describe the bug**
Changed to Warn - Inverter 0 REST failed to setReserve to 100 got 4
message pops up since updating to the latest version from 7.15.7 a couple of days ago. noticed it today.

also noticed that at the begining of each run, the reserve level is set to 4 which is accepted, and then at the end of the run, the code tries to set it to 100, which then fails.

tried to add a 10 second delay to setReserve, did not work. all using rest

**Expected behavior**
no warning message

**Predbat version**
latest 7.16.8

**Environment details**
- Inverter and battery setup : 3.6kw hybrid + 5.2 kwhr battery
- Docker
- it is not an intermittent connection issue as all relevant systems are on 1gige link, and the HA is running on a ryzen 8 with 32 gb ram. error only started after the update.

**Comment by RobinCu** [comment]
See the recommended fix here: https://github.com/springfall2008/batpred/issues/878

**Comment by springfall2008** [comment]
For reference in apps.yaml add:

```
  # Workaround to limit the maximum reserve setting, some inverters won't allow 100% to be set
  # Comment out if your inverter allows 100%
  inverter_reserve_max : 98
```
