### ISSUE TITLE
Car Charge Rate Threshold

### ISSUE THREAD

**Issue by campbellcopeland** [springfall2008/batpred#885]
**Is your feature request related to a problem? Please describe.**
When setting car target SOC this sometimes means Agile charge slots are selected at a higher than desirable rate. I mitigate this by reducing the target SOC so only slots below my threshold are used.

**Describe the solution you'd like**
I’d like a rate threshold so that even although a target SOC is set, only slots below the threshold are planned - resulting in not reaching the target SOC but not charging during slots that are more expensive than desired. 

**Describe alternatives you've considered**
Alternative would be to manually select a lower target SOC so than only Agile slots below threshold are used. I could add this to a variable and including in my automation but the PredBat plan will still show that car charging is intended. 

**Additional context**
Essentially, I don’t want to charge at rates above Go i.e. 9p/kWh. Depending on starting and target SOC, this sometimes means slots above this are planned. I’d like an override to prevent more expensive slots being planned - with the knowledge that I won’t reach target SOC - which works for my use case due to infrequency EV usage and willing to charge small amounts over several days when cheapest.

**Comment by springfall2008** [comment]
Seems like a good suggestion, I'll consider it on the backlog

**Comment by mpartington** [comment]
+1 for this. 

Having been on Agile for a week, being able to select a full number of slots below a particular price is something that I've had to try and iterate by adjusting the SoC target up/down.  This would be a great suggestion

**Comment by springfall2008** [comment]
https://github.com/springfall2008/batpred/releases/tag/v7.16.9

**Comment by campbellcopeland** [comment]
Seems to be working great.
