### ISSUE TITLE
Clocks changing

### ISSUE THREAD

**Issue by slopemad** [springfall2008/batpred#898]
Is there a potential issue with Predbat with clocks going forwards tonight?  I ask because:

<img width="186" alt="Screenshot 2024-03-30 at 19 00 11" src="https://github.com/springfall2008/batpred/assets/118896510/2cfea3d6-d5b9-469d-9da1-892ba052cd45">

There is, of course, no actual 1am and 1:30 am slot, and the 2am localtime price of 18.04 is showing at 1am...  Similarly, the 4pm peak price is showing at 3pm...

**Comment by gcoan** [comment]
I saw that the peak prices were starting at 3pm as well. I guess it makes sense in terms of being X hours away.

I'm assuming that when the clock jumps forward predbat will just jump forward and adjust to the new time. Same as if the PC was switched off for an hour 

When the clocks went back in October the octopus integration had duplicates of 1am and it all seemed to work out OK

**Comment by gcoan** [comment]
Mmm, ok so there is some strange behaviour in the predbat plan

The Octopus agile rates don't actually have a 1:00 and 1:30 slot

![image](https://github.com/springfall2008/batpred/assets/142018870/388a77ed-5856-42a3-8044-d7fba2790f57)

But predbat doesn't expect that and sets the 1:00 price to the 2:00 price from octopus 

![image](https://github.com/springfall2008/batpred/assets/142018870/253317e6-9eca-42e3-a4e8-2170a9a50b98)

Which kind of makes sense even if the times in the plan are wrong

But only a once a year issue

**Comment by springfall2008** [comment]
I think it's fine as the calculations are done internally based on time since midnight, its just the output plan doesn't localise the times?

**Comment by springfall2008** [comment]
Closing this old ticket, please open a new one if you have an up to date question
