### ISSUE TITLE
Chart Data

### ISSUE THREAD

**Issue by zubrusaurus11** [springfall2008/batpred#90]
I think the data behind a few of my charts might not be correct. I know i'm an above average user for energy but surely these figures aren't correct?
Background - 16kWp in solar panels, 2 x AC Coupled Inverters and 2 x 9.5kWh batteries.
<img width="491" alt="Screenshot 2023-09-21 at 15 50 24" src="https://github.com/springfall2008/batpred/assets/135059461/bdb7a3f0-2e8e-4389-a41a-431bb11731a4">
<img width="494" alt="Screenshot 2023-09-21 at 15 50 14" src="https://github.com/springfall2008/batpred/assets/135059461/ccc92e33-5a54-45c5-b8ed-e96b08850612">
<img width="492" alt="Screenshot 2023-09-21 at 15 50 02" src="https://github.com/springfall2008/batpred/assets/135059461/c6e7494d-d93d-4d41-990a-5629fa9531da">
Log file - 
[a0d7b954_appdaemon_2023-09-21T16-00-18.004Z.log](https://github.com/springfall2008/batpred/files/12686810/a0d7b954_appdaemon_2023-09-21T16-00-18.004Z.log)

Any help would be very much appreciated :)

**Comment by springfall2008** [comment]
your load data looks crazy, what sensor are you using and can you show it in HA?

**Comment by springfall2008** [comment]
As in do you have this in apps.yaml:

  load_today: 
    - sensor.givtcp_{geserial}_load_energy_today_kwh

**Comment by zubrusaurus11** [comment]
> your load data looks crazy, what sensor are you using and can you show it in HA?

Using: predbat.best_load_energy
<img width="572" alt="Screenshot 2023-09-21 at 17 16 29" src="https://github.com/springfall2008/batpred/assets/135059461/0a6cc8b1-d85e-411f-afc2-e2fad4e0672a">

**Comment by springfall2008** [comment]
You can't set load_today in apps.yaml to point to a predbat sensor, it needs to point to the GivTCP load energy today in kWh sensor

**Comment by springfall2008** [comment]
![image](https://github.com/springfall2008/batpred/assets/48591903/90dff626-dc46-4edc-89a1-5374c2252fc0)
This is the correct one for me

**Comment by zubrusaurus11** [comment]
> You can't set load_today in apps.yaml to point to a predbat sensor, it needs to point to the GivTCP load energy today in kWh sensor

ah okay. as I have 2 inverters, I should just choose the master inverter?

**Comment by springfall2008** [comment]
Yes, the master inverter - they both see the same import/export/load anyhow.

**Comment by zubrusaurus11** [comment]
> Yes, the master inverter - they both see the same import/export/load anyhow.
Gotcha. Should all entities be GivTCP?
<img width="392" alt="Screenshot 2023-09-21 at 17 40 27" src="https://github.com/springfall2008/batpred/assets/135059461/385b8943-8a37-4c62-8dd2-e339a5e12524">

For the imort/export entities, the GivTCP entities seem to be way off?
<img width="565" alt="Screenshot 2023-09-21 at 17 41 29" src="https://github.com/springfall2008/batpred/assets/135059461/c9a486a2-3096-452c-b8ec-19f2b6534876">

**Comment by springfall2008** [comment]
This is the template:

  load_today: 
    - sensor.givtcp_{geserial}_load_energy_today_kwh
  import_today: 
    - sensor.givtcp_{geserial}_import_energy_today_kwh
  export_today: 
    - sensor.givtcp_{geserial}_export_energy_today_kwh

These three should be GivTCP entities

**Comment by springfall2008** [comment]
That said your Import today looks corrupted, that big spike will confuse things massively.

**Comment by springfall2008** [comment]
Closing this ticket, mostly as it's GivTCP related I'm afraid
