### ISSUE TITLE
HACS install error: Repository structure for v7.16.10 is not compliant

### ISSUE THREAD

**Issue by glynhudson** [springfall2008/batpred#906]
**Describe the bug**
Trying to add batpred as a HACS custom repo results in this error 

**Expected behavior**
It should be possible to install via HACS 

**Predbat version**
Trying to install latest version 

**Environment details**

- Inverter and battery setup: N/A
- Docker HA core: 2024.3.0, frontend: 20240306.0
-  HACS 1.34.0

**Screenshots**

![Screenshot 2024-04-02 02 06 08](https://github.com/springfall2008/batpred/assets/758844/43ba10fd-1de3-4bc2-8884-df3f89ef09bf)

**Log file**

**Comment by springfall2008** [comment]
Did you enable AppDaemon in HACS first?

**Comment by glynhudson** [comment]
Ah yes, good point. I had to install AppDaemon manually, since I'm running a docker version of HA. I've now also installed batpred manually, and it seems to be working. Thanks for your help.
