### ISSUE TITLE
Chosen charge slots not optimised for cost

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#911]
**Describe the bug**
Predbat is not selecting the cheapest slots to charge.
I've suspected this behaviour for a while, but yesterday I screenshot the plan and have compared it to what Predbat actually did.

Basically it charged up on the slots times I have highlighted in PURPLE, but some of these (1.30 and 2am particularly) were more expensive than later slots.

2am slot was originally planned as discharge, but Predbat must have changed the plan, so the battery was full by 02.15. It then holds charge at lower prices, when it would have been more cost effective to charge.

**Expected behavior**
Choose the cheapest slots when multiple are available and hold or discharge (depending on price) for the others

**Predbat version**
V7.16.10

**Environment details**
- Standard HAOS installer 

**Screenshots**
Settings in log file, but
Combine charge slots is off as is any second pass optimisation.

![Screenshot_2024-04-03-22-17-37-458_io homeassistant companion android~4](https://github.com/springfall2008/batpred/assets/106986397/31b34fb3-32f6-41e5-b567-61b98a2a7e7e)

![Screenshot_2024-04-04-05-20-49-577_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/deed12a9-b906-4719-8100-e3d634ae9919)

It did briefly drop to zero in the more expensive slot, but then carried on
![Screenshot_2024-04-04-05-56-30-564_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/78130dd6-a98d-41aa-a0bd-65423c17205a)

**Log file**
[appdaemon (3).log](https://github.com/springfall2008/batpred/files/14861453/appdaemon.3.log)

**Comment by mpartington** [comment]
Obviously it's got this almost right and the cost impact is small, but it appears to point to something not quite right in the optimisation.

**Comment by Mikebert4** [comment]
I'm seeing similar behaviour.

Here's my plan for today - PredBat is charging in the red-bordered slots, but it would be more cost effective to hold over these and charge in the green-bordered slots.

![image](https://github.com/springfall2008/batpred/assets/344660/05fbaa84-42d3-4ece-9177-c63fb1e599bb)


Settings wise, I'm identical to OP, excepting that I have "set_dicsharge_during_charge" and "set_discharge_freeze" both as False.

**Comment by mpartington** [comment]
Mine did similar last night. Charged at 23.30, rather than holding to 02.30.

It did occasionally generate a plan that did hold, but seemed to revert and favour to the earlier charge option

![Screenshot_2024-04-21-11-34-27-039_com google android apps photos](https://github.com/springfall2008/batpred/assets/106986397/338c1f2b-1ae7-46d0-b014-42cbbd945e4d)

**Comment by mpartington** [comment]
Much better and more recent example. The plan was never choosing the lowest rates.tomcharge at, but then it must have got even worse after I went to bed, as it charged up at almost the highest rates in the period (23.30 to 00.30), rather than using those highlighted in green.

It needs to hold until later, as per my markup.

![Screenshot_2024-04-25-06-15-08-693_io homeassistant companion android~2](https://github.com/springfall2008/batpred/assets/106986397/1a8f5684-1600-4d50-a453-4a0dce54d5a2)
![Screenshot_2024-04-24-20-26-52-385_io homeassistant companion android~3](https://github.com/springfall2008/batpred/assets/106986397/5ff52f56-1d4c-44a4-b18f-8483aee831dd)
![Screenshot_2024-04-24-17-25-44-349_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/60f76fd7-c337-4663-896a-20e46aa53ed8)

**Comment by mpartington** [comment]
Here's the ned debug files for the period. Unfortunately the main log has overwritten (as running debug it quickly fills and overwrites)
[predbat_debug_01_00_00.zip](https://github.com/springfall2008/batpred/files/15105332/predbat_debug_01_00_00.zip)

**Comment by gcoan** [comment]
> Unfortunately the main log has overwritten (as running debug it quickly fills and overwrites)

If you edit the AppDaemon.yaml config file (in /addon_configs/... appdaemon - depending on which AppDaemon approach you have used)

Can change the number and size of log files retained:

```yaml
# write log records to a file, retaining 20 versions, rather than the standard appdaemon log
logs:
  main_log:
    filename: /homeassistant/appdaemon/appdaemon.log
    log_generations: 20
    log_size: 5000000
```

**Comment by mpartington** [comment]
[predbat_debug_info.zip](https://github.com/springfall2008/batpred/files/15108412/predbat_debug_info.zip)

**Comment by mpartington** [comment]
This has been fixed
