### ISSUE TITLE
input_number.predbat_car_charging_manual_soc_kwh' needs rounding to 1 decimal place

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#923]
**Describe the bug**
As per ritle

**Expected behavior**
Rounded to a reasonable number of decimal.places

**Predbat version**
V7.16.11

![Screenshot_2024-04-06-14-44-58-962_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/71ab9995-6816-4ba2-9139-9d10b316bda6)

**Comment by springfall2008** [comment]
Fix mode main for testing

**Comment by springfall2008** [comment]
Fix now released
