### ISSUE TITLE
How to handle a firmware update with Predbat?

### ISSUE THREAD

**Issue by jeldwendean** [springfall2008/batpred#929]
There's a new BMS version for the GivEnergy AIO. If I want to update, do I need to do anything on the Predbat side?

**Comment by gcoan** [comment]
You shouldn’t need to, but might be worth holding off or asking on the givenergy forum to check whether anyone else has had any experience of it with givtcp.Predbat itself wouldn’t normally notice any changes, its all hidden behind givtcp.A BMS version can often require a full battery calibration when it is installed so you might want to think about the timing of this, when the discharge then charge runs.Predbat will notice that a battery calibration is underway, will pause its scheduled battery activity and set battery discharge and charge to maximum values.When I had new BMS firmware installed (not on an AIO) this was about lunchtime so it was going to discharge into the peak then recharge in the peak - not ideal.I set predbat to read only, then manually adjusted the battery discharge rate so the battery would last me through the peak.  I then set the charge rate to zero, ran on grid through the evening, then set the charge rate back up to max to do the full battery charge overnight.CheersOn 9 Apr 2024, at 20:25, Dean Hobden ***@***.***> wrote:﻿
There's a new BMS version for the GivEnergy AIO. If I want to update, do I need to do anything on the Predbat side?

**Comment by gcoan** [comment]
> Ok great, if Predbat knows when a calibration is taking place then I'll kick the upgrade off tonight 

Yes Predbat knows when the calibration is taking place

https://springfall2008.github.io/batpred/faq/#warn-inverter-is-in-calibration-mode

Good luck
