### ISSUE TITLE
Appdaemon-predbat install

### ISSUE THREAD

**Issue by jaseHA** [springfall2008/batpred#932]
**Describe the bug**
Trying to install AppDaemon- predbat, getting an error message and it fails to install the Predbat integration part

**Expected behavior**
It is not creating the Predbat log files or config

**Predbat version** 7.16.7

**Environment details**

- Giv AIO, Givtcp installed. 
- Standard HAOS pi4
- Previously run Predbat successfully, uninstalled Sept 2023

**Screenshots**
Log file image from add-on start up
[appdaemon with predbat install error.pdf](https://github.com/springfall2008/batpred/files/14932856/appdaemon.with.predbat.install.error.pdf)

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)

**Comment by gcoan** [comment]
Can you make another screen shot showing all the error messages please, its truncated after the first part of the error.

Useful to see the full stack trace and what the underlying error is, at the moment can only see that appdaemon failed.

Thanks!
