### ISSUE TITLE
Midnight (or earliest ?) slot not selected for car or iboost charging, despite being cheaper

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#935]
**Describe the bug**
As discussed on FB, it selects the 23.30 slot in preference to the cheaper one at 00.00.  If you force idle the 23.30 slot, then it does select it.   Also tried changing the max charge unit cost to -1p, no effect.

**Expected behavior**
Choose the cheapest slot for car charging and iboost

Also, it would be nice if iboost could have a max slot price, like the car charging. That way could better target the lowest prices, rather than just any that are cheaper than gas

**Predbat version**
v7.16.12

**Screenshots**
<img width="449" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/2ef662cd-cecf-4d4e-a6ec-9b2755ab5980">

with slot forced idle
<img width="506" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/eef92f60-776f-4316-a6a2-fa356967acdd">

settings
<img width="294" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/b869ad49-3840-48a1-a1c8-e85211d74d04">

<img width="398" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/0818bb6b-6086-4ee0-bb7e-8e7b9a904250">

**Log file**
Period of interest is around 9pm, where we were running different scenarios
[appdaemon.log](https://github.com/springfall2008/batpred/files/14937583/appdaemon.log)

**Comment by mpartington** [comment]
Just added the requirement for another charge slot and it does select it, but still has a preference for the earlier cheaper slot
<img width="395" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/2bb5fed7-c1f6-4257-aa37-dda3da463ad4">

**Comment by mpartington** [comment]
Similar tonight, but 23.30 slot this time. Have upped the daily target, but no change 

![Screenshot_2024-04-11-22-25-24-572_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/c4252771-da05-4109-8b48-b96c69277011)

**Comment by springfall2008** [comment]
Fix now released
