### ISSUE TITLE
REST failed to setReserve

### ISSUE THREAD

**Issue by Surb109** [springfall2008/batpred#937]
**Describe the bug**
Getting status message "Warn - Inverter 0 REST failed to setReserve to 100 got 4".
Issue started randonly around 8am this morning.
I have restarted GivTCP/Homeassistant and appdaemon, but issue persists.

**Expected behavior**
Description of current action being performed without errors

**Predbat version**
v7.16.12

**Environment details**

- Givenergy AIO 13.4kWH battery
- Running Home Assistant container in Docker
- Using GivTCP integration

**Screenshots**
<img width="252" alt="image" src="https://github.com/springfall2008/batpred/assets/65631626/91122541-bce9-469d-acac-b07832f7b318">
<img width="432" alt="image2" src="https://github.com/springfall2008/batpred/assets/65631626/400f81da-4a9e-485d-aff2-cf8436262474">

**Log file**
Log Files covering today (11/04/2024)
[appdaemon.log](https://github.com/springfall2008/batpred/files/14945013/appdaemon.log)

**Comment by RobinCu** [comment]
This should sort it: https://github.com/springfall2008/batpred/issues/879

**Comment by Surb109** [comment]
Thanks Robin for the prompt response.

I have made the suggested change and it's now seems to be working correctly.


I'll try and do a better job of searching the issues before logging a ticket. I did try but didn't find anything similar 🙂
________________________________

**Comment by RobinCu** [comment]
No problem. Working out the correct search term can be a challenge in itself!

**Comment by gcoan** [comment]
I plan to put together a 'quick reference' for different inverter types as to specific predbat configuration values to be set.  Try to make it easier for others to find these things than them being buried in the docs
