### ISSUE TITLE
Setting discharge window is resetting Force Discharge to False

### ISSUE THREAD

**Issue by sparks1372** [springfall2008/batpred#95]
I have noticed that if it is currently within the discharge window, and the recalc wants to update the start or end time, sending that instruction to GivTCP appears to disable Force Discharge. This means the invertor stops exporting until the next recalc cycle at which point the Force Discharge setting is re-enabled.
This is similar to something I recall happening when I was hand rolling automations for charging/discharging so it could be the result of a GivTCP bug but if batpred checked, and updated if necessary, the Force Discharge setting after the discharge window has been set the impact would be minimised.

Alternatively, would it be worth separating the optimisation and actions (setting the correct values) into separate loops? This would mean you could rerun the calculations at a lower frequency, but have a higher frequency loop to check the values match the output of the last optimisation. The log currently seems to occaionally have workarounds for different bugs logged out which this could also take out of the optimisation loop.

**Comment by sparks1372** [comment]
Thinking about it, the split of the optimisation and action of setting values would also address #94

**Comment by springfall2008** [comment]
I don't see this issue myself, are you using REST mode or not?

**Comment by springfall2008** [comment]
e.g.here's my log of inverter mode: 
![image](https://github.com/springfall2008/batpred/assets/48591903/750b1a7c-a7e2-422d-81c3-e7af1a453600)

**Comment by sparks1372** [comment]
No I am not using REST mode, it is using the entities from MQTT. I will provide a similar screenshot later today, my inverter also ends up in Unknown state which I believe is as a result of the disabling of Force Discharge which I mention.
You may want to obscure your inverter serial number in your screenshot

**Comment by sparks1372** [comment]
As you can see the status is flicking between Timed Export and Unknown, and this appears to be related to when the end of the discharge cycle is being set, sometime successfully to 1900 and other times failing and resetting to 0700. I had similar issues with my custom automation when setting the charging/discharging windows so had to set the start and end with a 30 second gap in between.
Just to confirm, there are no automations active so the only process which is setting these values is batpred.

![image](https://github.com/springfall2008/batpred/assets/977934/9170ed21-f1b0-4f1d-b6f0-db542a31bf4c)
![image](https://github.com/springfall2008/batpred/assets/977934/4f4efedb-2a8f-4463-a44e-c916b0fb1bfc)

**Comment by sparks1372** [comment]
I have moved over to using REST and will report back if that avoids these issues

**Comment by springfall2008** [comment]
I don’t get the issue with rest, see if it solves it. If so we should probably report this as a bug to GivTCP

**Comment by springfall2008** [comment]
Did that solve it?

**Comment by sparks1372** [comment]
Yeah rest has been working fine
