### ISSUE TITLE
Predbat fails to install on HA 24.4.3

### ISSUE THREAD

**Issue by mauriceatkinson** [springfall2008/batpred#954]
I added the repository to HA but when running the install I receive the message
Failed to Install
The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 python3-dev=3.11.8-r0 && echo "Step1"' returned a non-zero code: 2

**Comment by springfall2008** [comment]
I believe this is already fixed, please try again
