### ISSUE TITLE
Incorrect energy requirement calculated for Predbat led Car Charging using Manual SOC

### ISSUE THREAD

**Issue by mpartington** [springfall2008/batpred#956]
**Describe the bug**
It appears Predbat is incorrectly calculating car charging losses, leading to an incorrect number of kWh being scheduled 

For example, the screenshot shows I set a manual SoC level of 45.3kWh and I have hardcoded my car battery capacity to 52kWh in apps.yaml.  Therefore I need 6.7kWh + losses

My losses are set to 5%, so:
6.7 x 1.05 = 7.04 kWh, but Predbat schedules 6.78 kWh (too low)

I then tried 20% losses
6.7 x 1.2 = 8.04 kWh, but Predbat schedules 8.38 (too high)

I then tried 0% losses and Predbat correctly schedules 6.7kWh

**Expected behavior**
Correctly calculate charge required

**Predbat version**

v7.16.15

**Environment details**

- Standard HAOS installer or Docker

**Screenshots**
<img width="186" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/b14ffe99-3d70-43c8-b42d-ac70200a6903">

<img width="197" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/3fdc483f-bab1-4ba3-b29c-abe785499469">

<img width="290" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/a5f62b2c-907a-4047-a0c8-9486782316f0">

**Log file**
[appdaemon.log](https://github.com/springfall2008/batpred/files/14972130/appdaemon.log)

**Comment by mpartington** [comment]
Strangely the amount of kWh needed seems accurate on this trial (with 5% losses). However there seems to be an issue with the slot cost sorting. The cheaper slot should be more utilised
![Screenshot_2024-04-15-19-12-35-385_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/888daca1-0579-4fd1-b9ab-0bc6559c3504)

**Comment by mpartington** [comment]
Another thing that seems to be happening almost every time (which didn't used to) is the first time you change the input number, it pumps back to the original value
<img width="785" alt="image" src="https://github.com/springfall2008/batpred/assets/106986397/a485c6f0-8173-4496-9a26-fad3608a6802">

**Comment by springfall2008** [comment]
Fix now on main for testing
