### ISSUE TITLE
Predbat not taking advantage of available plunge price periods for car charging

### ISSUE THREAD

**Issue by njhcarroll** [springfall2008/batpred#960]
**Describe the bug**
When there are plunge price periods on Octopus agile, I've noticed that the car charging slots selected by predbat can include non-plunge price periods when there are still available slots resulting in the charging cost being higher than is necessary.

**Expected behavior**
Predbat would use all available plunge price slots (within the time by which charging should be complete) before going on to include the cheapest non-plunge price slots

**Predbat version**

v7.16.15

**Environment details**

not relevant for this.

**Screenshots**
![image](https://github.com/springfall2008/batpred/assets/14128500/29e4f94a-ae4e-4ee6-a54f-adb905b4731c)

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)
[appdaemon.log](https://github.com/springfall2008/batpred/files/14983787/appdaemon.log)

**Comment by njhcarroll** [comment]
Should add that target car charging complete is set for 9am

**Comment by mpartington** [comment]
Saw the same behaviour yesterday on the -0.64 slot
![Screenshot_2024-04-15-19-12-35-385_io homeassistant companion android](https://github.com/springfall2008/batpred/assets/106986397/7b60d236-35b8-488a-bb5d-fe1b10a5f523)

**Comment by springfall2008** [comment]
Maybe fixed on main now with this PR: https://github.com/springfall2008/batpred/pull/977
