### ISSUE TITLE
Easy way to compare historical actual usage with forecast usage

### ISSUE THREAD

**Issue by bensebborn** [springfall2008/batpred#971]
When initially configuring things, it would be great to be able to compare the predictions with the actual figures.

Looking at some of the default graphs provided and I can see actual verses predicted are on the graphs, but they don’t both show. Historically, for example, if I wanted to compare PV output this morning with what was predicted, it doesn’t seem to be possible on the graphs currently because the prediction only shows in the future and the actual only shows in the past

What would be great is to have a graph that just shows historic data and plots both the actual and predicted for that period

I can have a go at creating the graphs, if someone could confirm that all the data is there to be able to do it?

**Comment by springfall2008** [comment]
Have you looked at the calibration chart?

**Comment by bensebborn** [comment]
I have, just getting my head around it as documentation was a bit brief. Will keep reading up.
