### ISSUE TITLE
Factor in cost of cycles/battery wear and tear

### ISSUE THREAD

**Issue by Meatballs1** [springfall2008/batpred#981]
Batteries have a finite lifetime, and generally guaranteed for x cycles. One example metric of the cost of charging/discharging a battery is:

`Cost / (capacity * DoD * max cycles * efficiency loss)` which works out at about 6p/kWh for my setup. 

There's probably other ways to estimate this, and I suspect the batteries will carry on for a while after their charge cycles just at reduced capacity, however, I'm not sure batpred takes this into account in the modelling?

**Describe the solution you'd like**
A configurable input value that adds a cost/kWh to charging.

**Comment by RobinCu** [comment]
Yes, this feature exists in expert mode (input_number.predbat_metric_battery_cycle).

**Comment by RobinCu** [comment]
More info here: https://springfall2008.github.io/batpred/customisation/

**Comment by Meatballs1** [comment]
Perfect thank you
